#----------------------------------------------------------------------
# set the library name here
#----------------------------------------------------------------------
PRJ_NAME = IPP_COMMON

#----------------------------------------------------------------------
# add/delete source files here
#----------------------------------------------------------------------
SRC = \
      IPPManager.c \
      sen_cmd.c \
      ImageAlgInfor.c \
      IPPBuffer.c \
      DataStamp.c \
      dzoom.c \
      Dcout.c \
      IPPCtrl.c \
      prv_common.c \
      cap_common.c \
      sen_common.c \
      cal_common.c \
      sen_isr.c \
      IPP_Debug.c \
      cal_api.c \
      dpc_alg.c
ASM =

#----------------------------------------------------------------------
# set the include directory here
#----------------------------------------------------------------------
INC_DIR = .. \
	../../../../../Include \

#----------------------------------------------------------------------
# set the image output directory here
#----------------------------------------------------------------------
IMG_BASE_DIR = ../../../..

#----------------------------------------------------------------------
# add additional C and assembly flags here
#----------------------------------------------------------------------
CFLAGS_D =
ASMFLAGS_D =

CFLAGS_R =
ASMFLAGS_R =

#----------------------------------------------------------------------
# include common parts of the makefile
#----------------------------------------------------------------------
MAKE_COMMON_DIR = ../../../../../MakeCommon
include $(MAKE_COMMON_DIR)/OutputLib.txt


