//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "NVTToolCommand.h"
#include "UIFlowWndPrintRes.c"
//-------------------------------------------------------------------------------------------------
#include "Utility.h"
#include "UIFlow.h"
//#include "UIMenuPrintSettings.h"
//#include "UIMenuWndPrint.h"
//#include "UIMenuWndPrint_PrintSetting.h"
//#include "UIMenuWndPrint_SelectImages.h"
//#include "UIMenuWndPrint_Confirm.h"
//-------------------------------------------------------------------------------------------------
#define UIPRINT_DPS_EVENT_AMOUNT    5
//-------------------------------------------------------------------------------------------------
static UINT32 UIPrintDpsEventCount = 0;
static UINT32 UIPrintDpsEventRead = 0;
static UINT32 UIPrintDpsEventWrite = 0;
static DPS_EVENT_ID UIPrintDpsEvent[UIPRINT_DPS_EVENT_AMOUNT];
DPS_CAPABILITY_INFO UIPrintDpsCapa;
//-------------------------------------------------------------------------------------------------
void UIPrint_ResetCappability(void)
{
    UIPRINT_MSG(("UIPRINT_M:UIPrint_ResetCappability\r\n"));

    Ux_SendEvent(
        &UIPrintObjCtrl,
        NVTEVT_PRINT_SET_JOB_CONFIG,
        2,
        DPS_CAPITEM_QUALITY,
        DPS_CAP_QUALITY_DEF);
    Ux_SendEvent(
        &UIPrintObjCtrl,
        NVTEVT_PRINT_SET_JOB_CONFIG,
        2,
        DPS_CAPITEM_PAPERTYPE,
        DPS_CAP_PAPERTYPE_DEF);
    Ux_SendEvent(
        &UIPrintObjCtrl,
        NVTEVT_PRINT_SET_JOB_CONFIG,
        2,
        DPS_CAPITEM_PAPERSIZE,
        DPS_CAP_PAPERSIZE_DEF);
    Ux_SendEvent(
        &UIPrintObjCtrl,
        NVTEVT_PRINT_SET_JOB_CONFIG,
        2,
        DPS_CAPITEM_DATEPRINTS,
        DPS_CAP_DATEPRINT_DEF);
    Ux_SendEvent(
        &UIPrintObjCtrl,
        NVTEVT_PRINT_SET_JOB_CONFIG,
        2,
        DPS_CAPITEM_NAMEPRINTS,
        DPS_CAP_NAMEPRINT_DEF);
    Ux_SendEvent(
        &UIPrintObjCtrl,
        NVTEVT_PRINT_SET_JOB_CONFIG,
        2,
        DPS_CAPITEM_IMGOPT,
        DPS_CAP_IMGOPT_DEF);
    Ux_SendEvent(
        &UIPrintObjCtrl,
        NVTEVT_PRINT_SET_JOB_CONFIG,
        2,
        DPS_CAPITEM_LAYOUTS,
        DPS_CAP_LAYOUT_DEF);
    Ux_SendEvent(
        &UIPrintObjCtrl,
        NVTEVT_PRINT_SET_JOB_CONFIG,
        2,
        DPS_CAPITEM_FIXSIZE,
        DPS_CAP_FIXSIZE_DEF);
}
//-------------------------------------------------------------------------------------------------
void UIPrint_ShowNotification(
    UIMenuWndPrint_Confirm_STATE_ENUM   State,
    DPS_EVENT_ID                        EventId)
{
    UIPRINT_MSG(("UIPRINT_M:UIPrint_ShowNotification:State=%d,EventId=%d\r\n",State,EventId));

    switch(EventId)
    {
        case DPS_EVENT_END:
        {
            Ux_CloseWindow(&UIMenuWndPrintCtrl, 1, DPS_EVENT_END);
            UxState_SetData(
                &UIFlowWndPrint_PicBridge_Text_StatusCtrl,
                MNU_CURITM,
                UIFlowWndPrint_PicBridge_Text_Status_STRID_PLEASE_WAIT);
            break;
        }

        case DPS_EVENT_DISCONNET_ENABLE:
        case DPS_EVENT_WARNING:
        case DPS_EVENT_WARNING_PAPER:
        case DPS_EVENT_WARNING_PAPER_EMPTY:
        case DPS_EVENT_WARNING_PAPER_LOAD:
        case DPS_EVENT_WARNING_PAPER_EJECT:
        case DPS_EVENT_WARNING_PAPER_MEDIA:
        case DPS_EVENT_WARNING_PAPER_JAM:
        case DPS_EVENT_WARNING_PAPER_NEARLY_EMPTY:
        case DPS_EVENT_WARNING_PAPER_NOT_FOUND:
        //Warning:Ink:23
        case DPS_EVENT_WARNING_INK:
        case DPS_EVENT_WARNING_INK_EMPTY:
        case DPS_EVENT_WARNING_INK_LOW:
        case DPS_EVENT_WARNING_INK_WASTE:
        //Warning:Hardware:27
        case DPS_EVENT_WARNING_HARDWARE:
        case DPS_EVENT_WARNING_HARDWARE_FATAL_ERROR:
        case DPS_EVENT_WARNING_HARDWARE_SERVICE_CALL:
        case DPS_EVENT_WARNING_HARDWARE_UNAVAILABLE:
        case DPS_EVENT_WARNING_HARDWARE_BUSY:
        case DPS_EVENT_WARNING_HARDWARE_LEVER:
        case DPS_EVENT_WARNING_HARDWARE_COVER_OPEN:
        case DPS_EVENT_WARNING_HARDWARE_MARKING_AGENT:
        case DPS_EVENT_WARNING_HARDWARE_INK_OPEN:
        case DPS_EVENT_WARNING_HARDWARE_NO_INK:
        //Warning:File:37
        case DPS_EVENT_WARNING_FILE:
        case DPS_EVENT_WARNING_FILE_PRINTINFO:
        case DPS_EVENT_WARNING_FILE_DECODE:
        //Fatal Error:Paper:40
        case DPS_EVENT_ERROR:
        case DPS_EVENT_ERROR_PAPER:
        case DPS_EVENT_ERROR_PAPER_EMPTY:
        case DPS_EVENT_ERROR_PAPER_LOAD:
        case DPS_EVENT_ERROR_PAPER_EJECT:
        case DPS_EVENT_ERROR_PAPER_MEDIA:
        case DPS_EVENT_ERROR_PAPER_JAM:
        case DPS_EVENT_ERROR_PAPER_NEARLY_EMPTY:
        case DPS_EVENT_ERROR_PAPER_NOT_FOUND:
        //Fatal Error:Ink:49
        case DPS_EVENT_ERROR_INK:
        case DPS_EVENT_ERROR_INK_EMPTY:
        case DPS_EVENT_ERROR_INK_LOW:
        case DPS_EVENT_ERROR_INK_WASTE:
        //Fatal Error:Hardware:53
        case DPS_EVENT_ERROR_HARDWARE:
        case DPS_EVENT_ERROR_HARDWARE_FATAL_ERROR:
        case DPS_EVENT_ERROR_HARDWARE_SERVICE_CALL:
        case DPS_EVENT_ERROR_HARDWARE_UNAVAILABLE:
        case DPS_EVENT_ERROR_HARDWARE_BUSY:
        case DPS_EVENT_ERROR_HARDWARE_LEVER:
        case DPS_EVENT_ERROR_HARDWARE_COVER_OPEN:
        case DPS_EVENT_ERROR_HARDWARE_MARKING_AGENT:
        case DPS_EVENT_ERROR_HARDWARE_INK_OPEN:
        case DPS_EVENT_ERROR_HARDWARE_NO_INK:
        //Fatal Error:File:63
        case DPS_EVENT_ERROR_FILE:
        case DPS_EVENT_ERROR_FILE_PRINTINFO:
        case DPS_EVENT_ERROR_FILE_DECODE:
        //Unknow Error status:66
        case DPS_EVENT_UNKNOWN_ERROR_STATUS:
        //XML syntax error:67
        case DPS_EVENT_XML_SYNTAX_ERROR:
        {
            Ux_OpenWindow(&UIMenuWndPrint_ConfirmCtrl, 2, State, EventId);
            break;
        }

        default:
        {
            break;
        }
    }
}
//-------------------------------------------------------------------------------------------------
void UIFlowWndPrint_OnPrintDpsEvent_ResetCapa(void)
{
    UINT32  i;
    //-------------------------------------------------------------------------------------------------
    UIPRINT_MSG(("UIPRINT_M:UIFlowWndPrint_OnPrintDpsEvent_ResetCapa:Quality=0x%08X\r\n",UIPrintDpsCapa.qualities));
    for(i=0; i<UIMenuWndPrint_PrintSetting_Quality_Menu_MAX; i++)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Quality_MenuCtrl,
            i,
            MNUITM_STATUS,
            STATUS_DISABLE);
    }

    UxMenu_SetItemData(
        &UIMenuWndPrint_PrintSetting_Quality_MenuCtrl,
        UIMenuWndPrint_PrintSetting_Quality_Menu_STRID_DEFAULT,
        MNUITM_STATUS,
        STATUS_ENABLE);

    if(UIPrintDpsCapa.qualities & DPS_CAP_QUALITY_NOR)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Quality_MenuCtrl,
            UIMenuWndPrint_PrintSetting_Quality_Menu_STRID_NORMAL,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.qualities & DPS_CAP_QUALITY_DRA)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Quality_MenuCtrl,
            UIMenuWndPrint_PrintSetting_Quality_Menu_STRID_ECONOMY,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.qualities & DPS_CAP_QUALITY_FIN)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Quality_MenuCtrl,
            UIMenuWndPrint_PrintSetting_Quality_Menu_STRID_FINE,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }
    //-------------------------------------------------------------------------------------------------
    UIPRINT_MSG(("UIPRINT_M:UIFlowWndPrint_OnPrintDpsEvent_ResetCapa:PaperType=0x%08X\r\n",UIPrintDpsCapa.paperTypes));
    for(i=0; i<UIMenuWndPrint_PrintSetting_PaperType_Menu_MAX; i++)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperType_MenuCtrl,
            i,
            MNUITM_STATUS,
            STATUS_DISABLE);
    }

    UxMenu_SetItemData(
        &UIMenuWndPrint_PrintSetting_PaperType_MenuCtrl,
        UIMenuWndPrint_PrintSetting_PaperType_Menu_STRID_DEFAULT,
        MNUITM_STATUS,
        STATUS_ENABLE);

    if(UIPrintDpsCapa.paperTypes & DPS_CAP_PAPERTYPE_PLA)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperType_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperType_Menu_STRID_PLAIN_PAPER,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperTypes & DPS_CAP_PAPERTYPE_PHO)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperType_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperType_Menu_STRID_PHOTO_PAPER,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperTypes & DPS_CAP_PAPERTYPE_FPHO)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperType_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperType_Menu_STRID_FAST_PHOTO,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }
    //-------------------------------------------------------------------------------------------------
    UIPRINT_MSG(("UIPRINT_M:UIFlowWndPrint_OnPrintDpsEvent_ResetCapa:PaperSize=0x%08X\r\n",UIPrintDpsCapa.paperSizes));
    UIPRINT_MSG(("UIPRINT_M:UIFlowWndPrint_OnPrintDpsEvent_ResetCapa:PaperSizeMore=0x%08X\r\n",UIPrintDpsCapa.paperSizesMore));
    for(i=0; i<UIMenuWndPrint_PrintSetting_PaperSize_Menu_MAX; i++)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            i,
            MNUITM_STATUS,
            STATUS_DISABLE);
    }

    UxMenu_SetItemData(
        &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
        UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_DEFAULT,
        MNUITM_STATUS,
        STATUS_ENABLE);

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_01L)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_L,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_02L)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_2L,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_POS)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_POSTCARD,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_CARD)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_CARD,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_150)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_100X150,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_4x6)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_4X6,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_8x10)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_8X10,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_LET)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_LETTER,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_11x17)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_11X17,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_A0)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A0,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_A1)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A1,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_A2)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A2,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }
    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_A3)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A3,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_A4)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A4,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_A5)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A5,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_A6)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A6,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_A7)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A7,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_A8)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A8,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_A9)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A9,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_B0)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B0,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_B1)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B1,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_B2)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B2,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_B3)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B3,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_B4)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B4,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_B5)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B5,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_B6)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B6,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_B7)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B7,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_B8)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B8,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizes & DPS_CAP_PAPERSIZE_B9)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B9,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizesMore & DPS_CAP_PAPERSIZE_89RO)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_L_ROLLS,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizesMore & DPS_CAP_PAPERSIZE_127RO)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_2L_ROLLS,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizesMore & DPS_CAP_PAPERSIZE_100RO)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_4_ROLLS,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.paperSizesMore & DPS_CAP_PAPERSIZE_210RO)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A4_ROLLS,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }
    //-------------------------------------------------------------------------------------------------
    UIPRINT_MSG(("UIPRINT_M:UIFlowWndPrint_OnPrintDpsEvent_ResetCapa:DatePrint=0x%08X\r\n",UIPrintDpsCapa.datePrints));
    for(i=0; i<UIMenuWndPrint_PrintSetting_DatePrint_Menu_MAX; i++)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_DatePrint_MenuCtrl,
            i,
            MNUITM_STATUS,
            STATUS_DISABLE);
    }

    UxMenu_SetItemData(
        &UIMenuWndPrint_PrintSetting_DatePrint_MenuCtrl,
        UIMenuWndPrint_PrintSetting_DatePrint_Menu_STRID_DEFAULT,
        MNUITM_STATUS,
        STATUS_ENABLE);

    if(UIPrintDpsCapa.datePrints & DPS_CAP_DATEPRINT_ON)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_DatePrint_MenuCtrl,
            UIMenuWndPrint_PrintSetting_DatePrint_Menu_STRID_ON,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.datePrints & DPS_CAP_DATEPRINT_OFF)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_DatePrint_MenuCtrl,
            UIMenuWndPrint_PrintSetting_DatePrint_Menu_STRID_OFF,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }
    //-------------------------------------------------------------------------------------------------
    UIPRINT_MSG(("UIPRINT_M:UIFlowWndPrint_OnPrintDpsEvent_ResetCapa:FilenamePrint=0x%08X\r\n",UIPrintDpsCapa.fileNamePrints));
    for(i=0; i<UIMenuWndPrint_PrintSetting_FilenamePrint_Menu_MAX; i++)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FilenamePrint_MenuCtrl,
            i,
            MNUITM_STATUS,
            STATUS_DISABLE);
    }

    UxMenu_SetItemData(
        &UIMenuWndPrint_PrintSetting_FilenamePrint_MenuCtrl,
        UIMenuWndPrint_PrintSetting_FilenamePrint_Menu_STRID_DEFAULT,
        MNUITM_STATUS,
        STATUS_ENABLE);

    if(UIPrintDpsCapa.fileNamePrints & DPS_CAP_NAMEPRINT_ON)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FilenamePrint_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FilenamePrint_Menu_STRID_ON,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fileNamePrints & DPS_CAP_NAMEPRINT_OFF)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FilenamePrint_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FilenamePrint_Menu_STRID_OFF,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }
    //-------------------------------------------------------------------------------------------------
    UIPRINT_MSG(("UIPRINT_M:UIFlowWndPrint_OnPrintDpsEvent_ResetCapa:ImageOptimizes=0x%08X\r\n",UIPrintDpsCapa.imgOpti));
    for(i=0; i<UIMenuWndPrint_PrintSetting_ImageOptimizes_Menu_MAX; i++)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_ImageOptimizes_MenuCtrl,
            i,
            MNUITM_STATUS,
            STATUS_DISABLE);
    }

    UxMenu_SetItemData(
        &UIMenuWndPrint_PrintSetting_ImageOptimizes_MenuCtrl,
        UIMenuWndPrint_PrintSetting_ImageOptimizes_Menu_STRID_DEFAULT,
        MNUITM_STATUS,
        STATUS_ENABLE);

    if(UIPrintDpsCapa.imgOpti & DPS_CAP_IMGOPT_ON)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_ImageOptimizes_MenuCtrl,
            UIMenuWndPrint_PrintSetting_ImageOptimizes_Menu_STRID_ON,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.imgOpti & DPS_CAP_IMGOPT_OFF)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_ImageOptimizes_MenuCtrl,
            UIMenuWndPrint_PrintSetting_ImageOptimizes_Menu_STRID_OFF,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }
    //-------------------------------------------------------------------------------------------------
    UIPRINT_MSG(("UIPRINT_M:UIFlowWndPrint_OnPrintDpsEvent_ResetCapa:Layout=0x%08X\r\n",UIPrintDpsCapa.layouts));
    for(i=0; i<UIMenuWndPrint_PrintSetting_Layout_Menu_MAX; i++)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Layout_MenuCtrl,
            i,
            MNUITM_STATUS,
            STATUS_DISABLE);
    }

    UxMenu_SetItemData(
        &UIMenuWndPrint_PrintSetting_Layout_MenuCtrl,
        UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_DEFAULT,
        MNUITM_STATUS,
        STATUS_ENABLE);

    if(UIPrintDpsCapa.layouts & DPS_CAP_LAYOUT_01)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Layout_MenuCtrl,
            UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_1UP,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.layouts & DPS_CAP_LAYOUT_02)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Layout_MenuCtrl,
            UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_2UP,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.layouts & DPS_CAP_LAYOUT_03)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Layout_MenuCtrl,
            UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_3UP,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.layouts & DPS_CAP_LAYOUT_04)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Layout_MenuCtrl,
            UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_4UP,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.layouts & DPS_CAP_LAYOUT_05)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Layout_MenuCtrl,
            UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_5UP,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.layouts & DPS_CAP_LAYOUT_06)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Layout_MenuCtrl,
            UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_6UP,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.layouts & DPS_CAP_LAYOUT_07)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Layout_MenuCtrl,
            UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_7UP,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.layouts & DPS_CAP_LAYOUT_08)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Layout_MenuCtrl,
            UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_8UP,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.layouts & DPS_CAP_LAYOUT_09)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Layout_MenuCtrl,
            UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_9UP,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.layouts & DPS_CAP_LAYOUT_10)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Layout_MenuCtrl,
            UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_10UP,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.layouts & DPS_CAP_LAYOUT_250UP)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Layout_MenuCtrl,
            UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_250UP,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.layouts & DPS_CAP_LAYOUT_IDX)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Layout_MenuCtrl,
            UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_INDEX,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.layouts & DPS_CAP_LAYOUT_NOB)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_Layout_MenuCtrl,
            UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_1UP_BORDERLESS,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }
    //-------------------------------------------------------------------------------------------------
    UIPRINT_MSG(("UIPRINT_M:UIFlowWndPrint_OnPrintDpsEvent_ResetCapa:FixedSize=0x%08X\r\n",UIPrintDpsCapa.fixedSizes));
    for(i=0; i<UIMenuWndPrint_PrintSetting_FixedSize_Menu_MAX; i++)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            i,
            MNUITM_STATUS,
            STATUS_DISABLE);
    }

    UxMenu_SetItemData(
        &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
        UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_DEFAULT,
        MNUITM_STATUS,
        STATUS_ENABLE);

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_2x3)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_25X325,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_3x5)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_35X5,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_4x6)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_4X6,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_5x7)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_2L,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_8x10)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_8X10,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_254)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_254X178,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_110)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_110X74,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_89)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_89X55,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_100)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_POSTCARD,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_6_8)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_6X8,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_7_10)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_7X10,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_9_13)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_9X13,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_10_15)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_100X150,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_13_18)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_13X18,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_15_21)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_15X21,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_18_24)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_18X24,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_A4)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_A4,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }

    if(UIPrintDpsCapa.fixedSizes & DPS_CAP_FIXSIZE_LETTER)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,
            UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_LETTER,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }
    //-------------------------------------------------------------------------------------------------
    if(UIPrintDpsCapa.layouts & DPS_CAP_LAYOUT_IDX)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_Menu_MenuCtrl,
            UIMenuWndPrint_Menu_Menu_STRID_PRINT_INDEX,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }
    else
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_Menu_MenuCtrl,
            UIMenuWndPrint_Menu_Menu_STRID_PRINT_INDEX,
            MNUITM_STATUS,
            STATUS_DISABLE);
    }

    if( UIPrintDpsCapa.fileTypes & DPS_CAP_FILETYPES_DPOF &&
        UIPrint_GetDPOFExist())
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_Menu_MenuCtrl,
            UIMenuWndPrint_Menu_Menu_STRID_PRINT_DPOF,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }
    else
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_Menu_MenuCtrl,
            UIMenuWndPrint_Menu_Menu_STRID_PRINT_DPOF,
            MNUITM_STATUS,
            STATUS_DISABLE);
    }

    if(UIPrintDpsCapa.croppings & DPS_CAP_CROPPINGS_ON)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_SelectImages_Menu_MenuCtrl,
            UIMenuWndPrint_SelectImages_Menu_Menu_STRID_CROP,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }
    else
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_SelectImages_Menu_MenuCtrl,
            UIMenuWndPrint_SelectImages_Menu_Menu_STRID_CROP,
            MNUITM_STATUS,
            STATUS_DISABLE);
    }
}
//-------------------------------------------------------------------------------------------------
void UIPrint_AddDpsEvent(DPS_EVENT_ID EventId)
{
    UIPRINT_MSG(("UIPRINT_M:UIPrint_AddDpsEvent:Count=%d,EventId=%d\r\n",UIPrintDpsEventCount,EventId));

    if(UIPrintDpsEventCount < UIPRINT_DPS_EVENT_AMOUNT)
    {
        UIPrintDpsEvent[UIPrintDpsEventWrite]=EventId;

        UIPrintDpsEventWrite++;
        if(UIPrintDpsEventWrite == UIPRINT_DPS_EVENT_AMOUNT)
        {
           UIPrintDpsEventWrite = 0;
        }

        UIPrintDpsEventCount++;
    }
}
//-------------------------------------------------------------------------------------------------
DPS_EVENT_ID UIPrint_GetDpsEvent(void)
{
    DPS_EVENT_ID TempDpsEvent = DPS_EVENT_NONE;

    if(UIPrintDpsEventCount > 0)
    {
        TempDpsEvent = UIPrintDpsEvent[UIPrintDpsEventRead];

        UIPrintDpsEventRead++;
        if(UIPrintDpsEventRead == UIPRINT_DPS_EVENT_AMOUNT)
        {
           UIPrintDpsEventRead = 0;
        }

        UIPrintDpsEventCount--;
    }
    UIPRINT_MSG(("UIPRINT_M:UIPrint_GetDpsEvent:Count=%d,EventId=%d\r\n",UIPrintDpsEventCount,TempDpsEvent));

    return TempDpsEvent;
}
//-------------------------------------------------------------------------------------------------
void UIPrint_PostNextDpsEvent(void)
{
    DPS_EVENT_ID TempDpsEvent = UIPrint_GetDpsEvent();

    UIPRINT_MSG(("UIPRINT_M:UIPrint_PostNextDpsEvent:EventId=%d\r\n",TempDpsEvent));

    if(TempDpsEvent != DPS_EVENT_NONE)
    {
        Ux_PostEvent(NVTEVT_CB_PRINT_DPS_EVENT, 1, TempDpsEvent);
    }
}
//---------------------UIFlowWndPrint Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPrint)
CTRL_LIST_ITEM(UIFlowWndPrint_Panel)
CTRL_LIST_END

//----------------------UIFlowWndPrint Event---------------------------
INT32 UIFlowWndPrint_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPrint_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPrint_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPrint_OnPrintDpsEvent(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPrint)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndPrint_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndPrint_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIFlowWndPrint_OnChildClose)
EVENT_ITEM(NVTEVT_CB_PRINT_DPS_EVENT,UIFlowWndPrint_OnPrintDpsEvent)
EVENT_END

INT32 UIFlowWndPrint_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    Ux_SendEvent(&UIPrintObjCtrl,NVTEVT_PRINT_INIT,0);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPrint_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/11/19#Marx Chiu -begin
    //#NT#Move DPS_Close() to UIFlowWndPrint_OnClose()
    DPS_Close();
    //#NT#2009/11/19#Marx Chiu -end
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    Ux_SendEvent(&UIPrintObjCtrl,NVTEVT_PRINT_CLOSE,0);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPrint_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    Ux_Redraw();
    if(paramNum > 0)
    {
        switch(paramArray[0])
        {
            case DPS_EVENT_CAPABILITY_CHANGED:
            {
                TimerDelayMs(500);
                Ux_SendEvent(
                    &UIPrintObjCtrl,
                    NVTEVT_PRINT_GET_CAPABILITY_ALL,
                    1,
                    (UINT32)(&UIPrintDpsCapa));
                UIFlowWndPrint_OnPrintDpsEvent_ResetCapa();
                Ux_OpenWindow(&UIMenuWndPrintCtrl, 0);
                break;
            }

            default:
            {
                break;
            }
        }
    }
    Ux_Redraw();
    UIPrint_PostNextDpsEvent();
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPrint_OnPrintDpsEvent(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum > 0)
    {
        switch(paramArray[0])
        {
            case DPS_EVENT_INIT_OK:
            {
                if(UIPrint_GetDCFFileAmount() > 0)
                {
                    TimerDelayMs(500);
                    Ux_SendEvent(
                        &UIPrintObjCtrl,
                        NVTEVT_PRINT_GET_CAPABILITY_ALL,
                        1,
                        (UINT32)(&UIPrintDpsCapa));
                    UIFlowWndPrint_OnPrintDpsEvent_ResetCapa();
                    Ux_OpenWindow(&UIMenuWndPrintCtrl, 0);
                }
                else
                {
                    UxState_SetData(
                        &UIFlowWndPrint_PicBridge_Text_StatusCtrl,
                        STATE_CURITEM,
                        UIFlowWndPrint_PicBridge_Text_Status_STRID_NO_IMAGE);
                }
                break;
            }

            case DPS_EVENT_INIT_FAIL:
            {
                UxState_SetData(
                    &UIFlowWndPrint_PicBridge_Text_StatusCtrl,
                    STATE_CURITEM,
                    UIFlowWndPrint_PicBridge_Text_Status_STRID_REMOVEUSBCABLE);
                break;
            }

            default:
            {
                UIPrint_ShowNotification(
                    UIMenuWndPrint_Confirm_STATE_NON_PRINTING,
                    paramArray[0]);
                break;
            }
        }
    }
    Ux_Redraw();
    return NVTEVT_CONSUME;
}
//---------------------UIFlowWndPrint_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPrint_Panel)
CTRL_LIST_ITEM(UIFlowWndPrint_PicBridge_Icon_Static)
CTRL_LIST_ITEM(UIFlowWndPrint_PicBridge_Text_Static)
CTRL_LIST_ITEM(UIFlowWndPrint_PicBridge_Text_Status)
CTRL_LIST_END

//----------------------UIFlowWndPrint_Panel Event---------------------------
EVENT_BEGIN(UIFlowWndPrint_Panel)
EVENT_END

//----------------------UIFlowWndPrint_PicBridge_Icon_Static Event---------------------------
EVENT_BEGIN(UIFlowWndPrint_PicBridge_Icon_Static)
EVENT_END

//----------------------UIFlowWndPrint_PicBridge_Text_Static Event---------------------------
EVENT_BEGIN(UIFlowWndPrint_PicBridge_Text_Static)
EVENT_END

//----------------------UIFlowWndPrint_PicBridge_Text_Status Event---------------------------
EVENT_BEGIN(UIFlowWndPrint_PicBridge_Text_Status)
EVENT_END

