//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupFormatConfirmRes.c"
#include "UIMenuWndSetupFormatConfirm.h"
#include "UIMenuWndSetupFormat.h"
#include "MenuCommonItem.h"
#include "UISystemStatusSettings.h"
#include "UIFlowWndWaitMoment.h"
#include "UIPlayObj.h"
#include "UISystemObj.h"
#include "UIFlow.h"

UINT32 g_u32FormatIndex = 0;

//---------------------UIMenuWndSetupFormatConfirmCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupFormatConfirm)
CTRL_LIST_ITEM(UIMenuWndSetupFormatConfirm_List_Text)
CTRL_LIST_ITEM(UIMenuWndSetupFormatConfirm_Static_Text)
CTRL_LIST_END

//----------------------UIMenuWndSetupFormatConfirmCtrl Event---------------------------
INT32 UIMenuWndSetupFormatConfirm_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_OnKeyDisplay(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupFormatConfirm)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupFormatConfirm_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupFormatConfirm_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndSetupFormatConfirm_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupFormatConfirm_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupFormatConfirm_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupFormatConfirm_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndSetupFormatConfirm_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_DISPLAY,UIMenuWndSetupFormatConfirm_OnKeyDisplay)
EVENT_END

INT32 UIMenuWndSetupFormatConfirm_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/07/28#Chris Chung -begin
    if(paramNum > 0)
    {
        g_u32FormatIndex = paramArray[0];
    }
    g_u32FormatIndex	=1; //always select Ext SD ,jack lan ,
    //#NT#2009/07/28#Chris Chung -end
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/12#Chris Chung -begin
    if(paramNum > 0)
    {
        if(paramArray[0]==NVTRET_WAITMOMENT && paramArray[1]==NVTRET_FORMAT)
        {
            Ux_CloseWindow(&UIMenuWndSetupFormatConfirmCtrl, 0);
        }
        else if(paramArray[0]==NVTRET_ENTER_MENU)
        {
            Ux_RedrawAllWind();
        }
    }
    else
    {
        Ux_RedrawAllWind();
    }
    //#NT#2009/08/12#Chris Chung -end
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndSetupFormatConfirmCtrl, 0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&MenuCommonItemCtrl,0); // close whole tab menu
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_CHANGE_DSCMODE,1,DSCMODE_CHGTO_NEXT);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_OnKeyDisplay(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;

    uiKeyAct = paramArray[0];

    switch(uiKeyAct)
    {
    case NVTEVT_KEY_PRESS:
        Ux_SendEvent(&UISystemObjCtrl,NVTEVT_EXE_DISPLAY,1,DISPLAY_NORMAL);
    break;
    }
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupFormatConfirm_List_TextCtrl Event---------------------------
INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupFormatConfirm_List_Text)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupFormatConfirm_List_Text_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupFormatConfirm_List_Text_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupFormatConfirm_List_Text_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 UINT32  uiKeyAct;

   uiKeyAct = paramArray[0];

    switch(uiKeyAct)
    {
    case NVTEVT_KEY_PRESS:
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
	break;
    	}
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 UINT32  uiKeyAct;

   uiKeyAct = paramArray[0];

    switch(uiKeyAct)
    {
    case NVTEVT_KEY_PRESS:
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
	break;
    	}
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupFormatConfirm_List_Text_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/12#Chris Chung -begin
    if(UxList_GetData(pCtrl,LST_CURITM)==UIMenuWndSetupFormatConfirm_List_Text_STRID_OK)
    {
        if(g_u32FormatIndex==0)
        {
            Ux_OpenWindow(&UIFlowWndWaitMomentCtrl,1,FLOWWAITMOMENT_MSG_PLEASEWAIT);
            Ux_BackgroundPostEvent(NVTEVT_BKW_FORMATNAND);
        }
        else if(g_u32FormatIndex==1)
        {
            if(GetCardStatus() == CARD_REMOVED)
            {
                Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_CARD,FLOWWRNMSG_TIMER_2SEC);
                return NVTEVT_CONSUME;
            }
            else
            {
                if(UI_Validate_Storage(STORAGE_CHECK_LOCKED, NULL) == FALSE)
                {
                    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_LOCKED,FLOWWRNMSG_TIMER_2SEC);
                    return NVTEVT_CONSUME;
                }
            }

            Ux_OpenWindow(&UIFlowWndWaitMomentCtrl,1,FLOWWAITMOMENT_MSG_PLEASEWAIT);
            Ux_BackgroundPostEvent(NVTEVT_BKW_FORMATCARD);
        }
        else
        {
            Ux_CloseWindow(&UIMenuWndSetupFormatConfirmCtrl, 0);
        }
    }
    else
    {
        Ux_CloseWindow(&UIMenuWndSetupFormatConfirmCtrl, 0);
    }
    //#NT#2009/08/12#Chris Chung -end
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupFormatConfirm_Static_TextCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupFormatConfirm_Static_Text)
EVENT_END

