//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupLcdBrightnessRes.c"
#include "UIMenuWndSetupLcdBrightness.h"
#include "MenuCommonItem.h"
#include "UISystemObj.h"

//---------------------UIMenuWndSetupLcdBrgihtnessCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupLcdBrgihtness)
CTRL_LIST_ITEM(UIMenuWndSetupLcdBrgihtness_SlideBar)
CTRL_LIST_ITEM(Arrow_Up)
CTRL_LIST_ITEM(Arrow_Down)
CTRL_LIST_END

//----------------------UIMenuWndSetupLcdBrgihtnessCtrl Event---------------------------
INT32 UIMenuWndSetupLcdBrgihtness_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLcdBrgihtness_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLcdBrgihtness_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLcdBrgihtness_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLcdBrgihtness_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupLcdBrgihtness)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupLcdBrgihtness_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupLcdBrgihtness_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupLcdBrgihtness_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupLcdBrgihtness_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndSetupLcdBrgihtness_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndSetupLcdBrgihtness_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 curStep;

    curStep = SysGetFlag(FL_LCD_BRIGHTNESS);

    if(curStep > LCDBRT_LVL_ID_MAX - 1)
        curStep = LCDBRT_LVL_ID_MAX - 1;
    else if(curStep < LCDBRT_LVL_01)
        curStep = LCDBRT_LVL_01;

    UxSlider_SetData(&UIMenuWndSetupLcdBrgihtness_SlideBarCtrl, SLIDER_CURSTP, curStep);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLcdBrgihtness_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLcdBrgihtness_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&MenuCommonItemCtrl,0); // close whole tab menu
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLcdBrgihtness_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_CHANGE_DSCMODE,1,DSCMODE_CHGTO_NEXT);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLcdBrgihtness_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupLcdBrgihtness_SlideBarCtrl Event---------------------------
INT32 UIMenuWndSetupLcdBrgihtness_SlideBar_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLcdBrgihtness_SlideBar_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLcdBrgihtness_SlideBar_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupLcdBrgihtness_SlideBar)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupLcdBrgihtness_SlideBar_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndSetupLcdBrgihtness_SlideBar_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupLcdBrgihtness_SlideBar_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupLcdBrgihtness_SlideBar_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_STEP,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLcdBrgihtness_SlideBar_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_STEP,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLcdBrgihtness_SlideBar_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 curStep;

    curStep = UxSlider_GetData(pCtrl,SLIDER_CURSTP);

    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_EXE_BRIGHT,1,curStep);
    Ux_CloseWindow(&UIMenuWndSetupLcdBrgihtnessCtrl, 0);
    return NVTEVT_CONSUME;
}
//----------------------Arrow_UpCtrl Event---------------------------
EVENT_BEGIN(Arrow_Up)
EVENT_END

//----------------------Arrow_DownCtrl Event---------------------------
EVENT_BEGIN(Arrow_Down)
EVENT_END

