//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupCommonCarNumberRes.c"
#include "UIMenuWndSetupCommonCarNumber.h"
#include "UIFlow.h"
#include "UISystemStatusSettings.h"

//---------------------UIMenuWndSetupCommonCarNumberCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPCOMMONCARNUMBER_ERROR_MSG        1
#define _UIMENUWNDSETUPCOMMONCARNUMBER_TRACE_MSG        0

/*#if (_UIMENUWNDSETUPCOMMONCARNUMBER_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupCommonCarNumberErrMsg(...)            debug_msg ("^R UIMenuWndSetupCommonCarNumber: "__VA_ARGS__)
#else
#define UIMenuWndSetupCommonCarNumberErrMsg(...)
#endif

#if (_UIMENUWNDSETUPCOMMONCARNUMBER_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupCommonCarNumberTraceMsg(...)          debug_msg ("^B UIMenuWndSetupCommonCarNumber: "__VA_ARGS__)
#else
#define UIMenuWndSetupCommonCarNumberTraceMsg(...)
#endif*/

//---------------------UIMenuWndSetupCommonCarNumberCtrl Global Variables -----------------------------
#define CARNO_LEN		6
#define CARNO_1ST_CNT	31
#define CARNO_1ST_IND	1
#define CARNO_NOR_CNT	36

static CHAR CarNoBuf[CARNO_LEN+1] = {0};
static CHAR CarNoShow[CARNO_LEN][2] = {"A", "A", "A", "A", "A", "A"};
static _ALIGNED(4) const char  CarNoNormalStr[]   = {'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S',
                                                  'T','U','V','W','X','Y','Z','0','1','2','3','4','5','6','7','8','9'};
static int CarNoStrIndex[CARNO_LEN] = {0};	//  Button Control string index
static VControl *CarNoButton[UIMenuWndSetupCommonCarNumber_Tab_MAX]=
{
	&UIMenuWndSetupCommonCarNumber_Button1Ctrl,
	&UIMenuWndSetupCommonCarNumber_Button2Ctrl,
	&UIMenuWndSetupCommonCarNumber_Button3Ctrl,
	&UIMenuWndSetupCommonCarNumber_Button4Ctrl,
	&UIMenuWndSetupCommonCarNumber_Button5Ctrl,
	&UIMenuWndSetupCommonCarNumber_Button6Ctrl,
};
//---------------------UIMenuWndSetupCommonCarNumberCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupCommonCarNumberCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupCommonCarNumberCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupCommonCarNumberCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupCommonCarNumber)
CTRL_LIST_ITEM(UIMenuWndSetupCommonCarNumber_Tab)
CTRL_LIST_END

//----------------------UIMenuWndSetupCommonCarNumberCtrl Event---------------------------
INT32 UIMenuWndSetupCommonCarNumber_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCommonCarNumber_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCommonCarNumber_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCommonCarNumber_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCommonCarNumber_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupCommonCarNumber)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupCommonCarNumber_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupCommonCarNumber_OnClose)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndSetupCommonCarNumber_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupCommonCarNumber_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupCommonCarNumber_OnKeyMode)
EVENT_END

static void UIMenuWndSetupCarNumber_UpdateInfo(void)
{
	int i;
	for (i=0; i<UIMenuWndSetupCommonCarNumber_Tab_MAX;  i++)
	{
		UxButton_SetItemData(CarNoButton[i], 0, BTNITM_STRID, Txt_Pointer(CarNoShow[i]));
	}
}

INT32 UIMenuWndSetupCommonCarNumber_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	int i;
	int j;
	memset(CarNoBuf, 0, CARNO_LEN+1);
	strncpy(CarNoBuf, SysGetNZHCarNoStamp(), CARNO_LEN+1);
	// Default Car no ¾©B00000
	for (i=0; i<CARNO_LEN; i++)
	{
		for (j=0; j<CARNO_NOR_CNT; j++)
		{
			if (CarNoBuf[i] == CarNoNormalStr[j])
			{
				CarNoStrIndex[i] = j;
				break;
			}
		}
		if (j >= CARNO_NOR_CNT)
		{
			CarNoStrIndex[i] = 0;
		}
		CarNoShow[i][0] = CarNoNormalStr[CarNoStrIndex[i]];
	}
	UIMenuWndSetupCarNumber_UpdateInfo();
	UxTab_SetData(&UIMenuWndSetupCommonCarNumber_TabCtrl, TAB_FOCUS, 0);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCommonCarNumber_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCommonCarNumber_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	int i;

	for (i=0; i<CARNO_LEN; i++)
	{
		CarNoBuf[i] = CarNoShow[i][0];
	}
	CarNoBuf[i] = '\0';
	SysSetNZHCarNoStamp(CarNoBuf);
	Ux_CloseWindow(pCtrl, 0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCommonCarNumber_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIMenuWndSetupCommonCarNumber_OnKeyShutter2(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndSetupCommonCarNumber_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	int i;

	for (i=0; i<CARNO_LEN; i++)
	{
		CarNoBuf[i] = CarNoShow[i][0];
	}
	CarNoBuf[i] = '\0';
	SysSetNZHCarNoStamp(CarNoBuf);
	
	Ux_SendEvent(&UISystemObjCtrl,NVTEVT_CHANGE_DSCMODE,1,DSCMODE_CHGTO_NEXT);
    	return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupCommonCarNumber_TabCtrl Event---------------------------
INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyMenu(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupCommonCarNumber_Tab)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupCommonCarNumber_Tab_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupCommonCarNumber_Tab_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupCommonCarNumber_Tab_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndSetupCommonCarNumber_Tab_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupCommonCarNumber_Tab_OnKeyMenu)
EVENT_END

static void _update_Tab_Button_index(VControl *pCtrl, int derc)
{
	UINT32 CurTabIndex = 0;
	CurTabIndex = UxTab_GetData(pCtrl, TAB_FOCUS);
	if (derc == -1)//up
	{
		if (CarNoStrIndex[CurTabIndex] == 0)
		{
			CarNoStrIndex[CurTabIndex] = CARNO_NOR_CNT-1;
		}
		else
		{
			CarNoStrIndex[CurTabIndex]--;
		}
	}
	else // down
	{

		if (CarNoStrIndex[CurTabIndex] == CARNO_NOR_CNT-1)
		{
			CarNoStrIndex[CurTabIndex] = 0;
		}
		else
		{
			CarNoStrIndex[CurTabIndex]++;
		}
	}
	CarNoShow[CurTabIndex][0] = CarNoNormalStr[CarNoStrIndex[CurTabIndex]];
	UxButton_SetItemData(CarNoButton[CurTabIndex], 0, BTNITM_STRID, Txt_Pointer(CarNoShow[CurTabIndex]));
}

INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiKeyAct = paramArray[0];
	switch (uiKeyAct)
	{
		case NVTEVT_KEY_PRESS:
		{
			_update_Tab_Button_index(pCtrl, -1);
			break;
		}
	}
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiKeyAct = paramArray[0];
	switch (uiKeyAct)
	{
		case NVTEVT_KEY_PRESS:
		{
			_update_Tab_Button_index(pCtrl, 1);
			break;
		}
	}
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCommonCarNumber_Tab_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UIMenuWndSetupCommonCarNumber_Tab_OnKeyRight(pCtrl, paramNum, paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupCommonCarNumber_Button1Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCommonCarNumber_Button1)
EVENT_END

//----------------------UIMenuWndSetupCommonCarNumber_Button2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCommonCarNumber_Button2)
EVENT_END

//----------------------UIMenuWndSetupCommonCarNumber_Button3Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCommonCarNumber_Button3)
EVENT_END

//----------------------UIMenuWndSetupCommonCarNumber_Button4Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCommonCarNumber_Button4)
EVENT_END

//----------------------UIMenuWndSetupCommonCarNumber_Button5Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCommonCarNumber_Button5)
EVENT_END

//----------------------UIMenuWndSetupCommonCarNumber_Button6Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCommonCarNumber_Button6)
EVENT_END

