//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPLCDBRIGHTNESSRES_H
#define UIMENUWNDSETUPLCDBRIGHTNESSRES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_ITEM_RECT(CMD_Rectangle,Rect3,56,50,304,208,272,0,5,255,0,0,0)
SHOW_MAP_BEGIN(Skin1)
SHOW_MAP_BODY(Rect3)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin1,0,0,319,239)

SHOW_ITEM_RECT(CMD_Rectangle,Rect7,0,0,161,21,16,0,3,0,0,0,0)
SHOW_MAP_BEGIN(Skin5)
SHOW_MAP_BODY(Rect7)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin5,0,0,161,21)

SHOW_ITEM_RECT(CMD_Rectangle,Thumb9Rect,0,0,15,21,0,0,3,3,0,0,0)
SHOW_MAP_BEGIN(Thumb9)
SHOW_MAP_BODY(Thumb9Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Thumb9,0,0,15,21)

SHOW_MAP_BEGIN(Track8)
SHOW_MAP_BODY(Thumb9)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Track8,0,0,161,21)

SHOW_MAP_BEGIN(Normal4)
SHOW_MAP_BODY(Skin5)
SHOW_MAP_BODY(Track8)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal4,100,82,261,103)

SHOW_MAP_BEGIN(UIMenuWndSetupLcdBrgihtness_SlideBar)
SHOW_MAP_BODY(Normal4)
SHOW_MAP_END

DECLARE_EVENT(UIMenuWndSetupLcdBrgihtness_SlideBar)
CTRL_LIST_BEGIN(UIMenuWndSetupLcdBrgihtness_SlideBar)
CTRL_LIST_END

CREATE_SLIDER_DATA(UIMenuWndSetupLcdBrgihtness_SlideBar,SLIDER_HORIZONTAL, 0,10)
CREATE_SLIDER_CTRL(UIMenuWndSetupLcdBrgihtness_SlideBar,UIMenuWndSetupLcdBrgihtness_SlideBar,0,100,82,261,103)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle,Skin11Rect,0,0,28,29,0,0,255,255,0,0,0)
SHOW_MAP_BEGIN(Skin11)
SHOW_MAP_BODY(Skin11Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin11,0,0,28,29)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon12, 0, 1, 27,28, ICONID_NULL,83886080,0,0,0,0,0,0,0)
SHOW_MAP_BEGIN(Normal10)
SHOW_MAP_BODY(Skin11)
SHOW_MAP_BODY(Icon12)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal10,268,79,296,108)

SHOW_MAP_BEGIN(Arrow_Up)
SHOW_MAP_BODY(Normal10)
SHOW_MAP_END

DECLARE_EVENT(Arrow_Up)
CREATE_STATIC_DATA(Arrow_Up,ICON_INCREASE)
CREATE_STATIC_CTRL(Arrow_Up,0,268,79,296,108)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle,Skin15Rect,0,0,29,27,0,0,255,255,0,0,0)
SHOW_MAP_BEGIN(Skin15)
SHOW_MAP_BODY(Skin15Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin15,0,0,29,27)

SHOW_ITEM_IMAGE(CMD_Image|CMD_ITEM,Icon16, 6, 6, 21,21, ICONID_NULL,83886080,0,0,0,0,0,17,0)
SHOW_MAP_BEGIN(Normal14)
SHOW_MAP_BODY(Skin15)
SHOW_MAP_BODY(Icon16)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal14,63,79,92,106)

SHOW_MAP_BEGIN(Arrow_Down)
SHOW_MAP_BODY(Normal14)
SHOW_MAP_END

DECLARE_EVENT(Arrow_Down)
CREATE_STATIC_DATA(Arrow_Down,ICON_DECREASE)
CREATE_STATIC_CTRL(Arrow_Down,0,63,79,92,106)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(UIMenuWndSetupLcdBrgihtness)
SHOW_MAP_BODY(Skin1)
SHOW_MAP_END

DECLARE_EVENT(UIMenuWndSetupLcdBrgihtness)
DECLARE_CTRL_LIST(UIMenuWndSetupLcdBrgihtness)
CREATE_CTRL(UIMenuWndSetupLcdBrgihtness,UIMenuWndSetupLcdBrgihtness,CTRL_WND,NULL,0 ,0,0,319,239)
#endif
