//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPLCDBRIGHTNESS_H
#define UIMENUWNDSETUPLCDBRIGHTNESS_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupLcdBrgihtnessCtrl;//Panel type 

extern VControl UIMenuWndSetupLcdBrgihtness_SlideBarCtrl;//SliderBar type 

extern VControl Arrow_UpCtrl;//Static type 

extern VControl Arrow_DownCtrl;//Static type 

#endif
