//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPLOADERVERSION_H
#define UIMENUWNDSETUPLOADERVERSION_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupLoaderVersionCtrl;//Panel type 

extern VControl UIMenuSetupLoaderNameTextCtrl;//Static type 

extern VControl UIMenuSetupFWNameTextCtrl;//Static type 

extern VControl UIMenuSetupLoaderVersionTextCtrl;//Static type 

extern VControl UIMenuSetupBuildDateTextCtrl;//Static type 

extern VControl UIMenuSetupBuildTimeTextCtrl;//Static type 

#endif
