//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDWRNSTRGHOTPLUG_H
#define UIFLOWWNDWRNSTRGHOTPLUG_H

#include "UIFramework.h"


//-----------------------------------------------------------------------------
// UIFlowWndWrnStrgHotPlug User Definitions
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// UIFlowWndWrnStrgHotPlug ToolGen
//-----------------------------------------------------------------------------
extern VControl UIFlowWndWrnStrgHotPlugCtrl;

extern VControl UIFlowWndWrnStrgHotPlug_StatusTXT_MsgCtrl;

typedef enum
{
UIFlowWndWrnStrgHotPlug_StatusTXT_Msg_STRID_TOINTERNAL,
UIFlowWndWrnStrgHotPlug_StatusTXT_Msg_STRID_TOSD,
UIFlowWndWrnStrgHotPlug_StatusTXT_Msg_MAX
}UIFlowWndWrnStrgHotPlug_StatusTXT_Msg_Setting;

//-----------------------------------------------------------------------------
// UIFlowWndWrnStrgHotPlug User Functions
//-----------------------------------------------------------------------------

#endif
