//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDFWVERSION_H
#define UIFLOWWNDFWVERSION_H

#include "UIFramework.h"

extern VControl UIFlowWndFwVersionCtrl;//Panel type 

extern VControl UIFlowWndFwVersion_StaticTextCtrl;//Static type 

extern VControl UIFlowWndConfigFwVersion_StaticTextCtrl;//Static type 

#endif
