//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "NVTToolCommand.h"
#include "UIFlowWndFwVersionRes.c"
#include "UIFlow.h"
#include "FwVersion.h"
#include "UIConfig.h"
//---------------------UIFlowWndFwVersionCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndFwVersion)
CTRL_LIST_ITEM(UIFlowWndFwVersion_StaticText)
CTRL_LIST_ITEM(UIFlowWndConfigFwVersion_StaticText)
CTRL_LIST_END

//----------------------UIFlowWndFwVersionCtrl Event---------------------------
INT32 UIFlowWndFwVersion_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndFwVersion_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndFwVersion)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndFwVersion_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndFwVersion_OnClose)
EVENT_END

INT32 UIFlowWndFwVersion_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    static UCHAR FwVersion[32];
    static UCHAR ConfigFwVersion[32];
    UINT32 uhSelect = 0;

    if(paramNum != 0)
        uhSelect= paramArray[0];

    UxCtrl_SetShow(&UIFlowWndFwVersion_StaticTextCtrl, TRUE);
    UxCtrl_SetShow(&UIFlowWndConfigFwVersion_StaticTextCtrl, TRUE);

//    sprintf(FwVersion,"%s",GetUIConfigSoftwareVer());
    sprintf((char*)FwVersion,"%s","APC3.2011.09.21");
    UxStatic_SetData(&UIFlowWndConfigFwVersion_StaticTextCtrl,STATIC_VALUE,Txt_Pointer(FwVersion));

    sprintf((char*)FwVersion,"%s",DSC_FW_VERSION_STR);
    UxStatic_SetData(&UIFlowWndFwVersion_StaticTextCtrl,STATIC_VALUE,Txt_Pointer(FwVersion));

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndFwVersion_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndFwVersion_StaticTextCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndFwVersion_StaticText)
EVENT_END

//----------------------UIFlowWndConfigFwVersion_StaticTextCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndConfigFwVersion_StaticText)
EVENT_END

