//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDWAITMOMENTAPI_H
#define UIFLOWWNDWAITMOMENTAPI_H

typedef enum
{
    FLOWWAITMOMENT_MSG_PLEASEWAIT    = 0,
    FLOWWAITMOMENT_MSG_MAX
} FLOWWAITMOMENT_MSG;

#endif
