#include "UIResource.h"

#define COLOR_IDX_BLUE 0x005AD565 //32 64 FE
#define COLOR_IDX_GREEN 0x0024537E //00 D2 32
#define COLOR_IDX_RED 0x00E65D5D //EB 1E 1E

PALETTE_ITEM gMenuBluePalette[1]=
{
PALETTE_MAKE(BLEND_OPAQUE_100, BLINK_OFF, COLOR_IDX_BLUE),
};
PALETTE_ITEM gMenuGreenPalette[1]=
{
PALETTE_MAKE(BLEND_OPAQUE_100, BLINK_OFF, COLOR_IDX_GREEN),
};
PALETTE_ITEM gMenuRedPalette[1]=
{
PALETTE_MAKE(BLEND_OPAQUE_100, BLINK_OFF, COLOR_IDX_RED),
};

