//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPLAYPROTECT_H
#define UIMENUWNDPLAYPROTECT_H

#include "UIFramework.h"

extern VControl UIMenuWndPlayProtectCtrl;//Panel type 

extern VControl UIMenuWndPlayProtect_PanelCtrl;//Panel type 

extern VControl UIMenuWndPlayProtect_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPlayProtect_Menu_STRID_LOCKONE,
UIMenuWndPlayProtect_Menu_STRID_UNLOCKONE,
UIMenuWndPlayProtect_Menu_STRID_LOCKALL,
UIMenuWndPlayProtect_Menu_STRID_UNLOCKALL,
UIMenuWndPlayProtect_Menu_MAX
}UIMenuWndPlayProtect_Menu_Setting;

#endif
