//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPLAYQUICKDEL_H
#define UIMENUWNDPLAYQUICKDEL_H

#include "UIFramework.h"

extern VControl UIMenuWndPlayQuickDelCtrl;//Panel type 

extern VControl UIMenuWndPlayQuickDel_StatusCtrl;//Status type 

typedef enum
{
UIMenuWndPlayQuickDel_Status_ICON_MODE_PLAYBACK,
UIMenuWndPlayQuickDel_Status_ICON_FILE_VIDEO,
UIMenuWndPlayQuickDel_Status_MAX
}UIMenuWndPlayQuickDel_Status_Setting;

extern VControl UIMenuWndPlayQuickDel_PanelCtrl;//Panel type 

extern VControl UIMenuWndPlayQuickDel_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPlayQuickDel_Menu_STRID_DELETECURRENT,
UIMenuWndPlayQuickDel_Menu_STRID_DELETEALL,
UIMenuWndPlayQuickDel_Menu_MAX
}UIMenuWndPlayQuickDel_Menu_Setting;

#endif
