//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPLAYQUICKCONFIRMDEL_H
#define UIMENUWNDPLAYQUICKCONFIRMDEL_H

#include "UIFramework.h"

extern VControl UIMenuWndPlayQuickConfirmDelCtrl;//Panel type 

extern VControl UIMenuWndPlayQuickConfirmDel_PanelCtrl;//Panel type 

extern VControl UIMenuWndPlayQuickConfirmDel_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPlayQuickConfirmDel_Menu_STRID_CANCEL,
UIMenuWndPlayQuickConfirmDel_Menu_STRID_OK,
UIMenuWndPlayQuickConfirmDel_Menu_MAX
}UIMenuWndPlayQuickConfirmDel_Menu_Setting;

extern VControl UIMenuWndPlayQuickConfirmDel_StatusTextCtrl;//Status type 

typedef enum
{
UIMenuWndPlayQuickConfirmDel_StatusText_STRID_ERASE_THIS,
UIMenuWndPlayQuickConfirmDel_StatusText_STRID_ERASE_ALL,
UIMenuWndPlayQuickConfirmDel_StatusText_MAX
}UIMenuWndPlayQuickConfirmDel_StatusText_Setting;

#endif
