//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPLAYCOPYTOCARD_H
#define UIMENUWNDPLAYCOPYTOCARD_H

#include "UIFramework.h"

extern VControl UIMenuWndPlayCopyToCardCtrl;//Panel type 

extern VControl UIMenuWndPlayCopyToCard_PanelCtrl;//Panel type 

extern VControl UIMenuWndPlayCopyToCard_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPlayCopyToCard_Menu_STRID_CANCEL,
UIMenuWndPlayCopyToCard_Menu_STRID_ALL_IMAGES,
UIMenuWndPlayCopyToCard_Menu_MAX
}UIMenuWndPlayCopyToCard_Menu_Setting;

#endif
