//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPlayCopyToCardRes.c"
#include "UIMenuWndPlayCopyToCard.h"
#include "UIPlayObj.h"
#include "UISystemStatusSettings.h"
#include "UIFlowWndWaitMoment.h"
#include "UISystemObj.h"
#include "MenuCommonItem.h"
#include "UIFlow.h"

//---------------------UIMenuWndPlayCopyToCardCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayCopyToCard)
CTRL_LIST_ITEM(UIMenuWndPlayCopyToCard_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPlayCopyToCardCtrl Event---------------------------
INT32 UIMenuWndPlayCopyToCard_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayCopyToCard_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayCopyToCard_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayCopyToCard_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayCopyToCard_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayCopyToCard_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayCopyToCard_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayCopyToCard)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPlayCopyToCard_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPlayCopyToCard_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndPlayCopyToCard_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPlayCopyToCard_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPlayCopyToCard_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPlayCopyToCard_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPlayCopyToCard_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPlayCopyToCard_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxMenu_SetData(&UIMenuWndPlayCopyToCard_MenuCtrl, MNU_CURITM, 0);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayCopyToCard_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayCopyToCard_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/04#Chris Chung -begin
    if(paramNum > 0)
    {
        if(paramArray[0]==NVTRET_WAITMOMENT)
        {
            if(paramArray[1]==NVTRET_COPY2CARD)
            {
                Ux_CloseWindow((VControl *)(&UIMenuWndPlayCopyToCardCtrl), 0);
            }
            else if(paramArray[1]==NVTRET_COPY2CARDFULL)
            {
                Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_FULL,FLOWWRNMSG_TIMER_2SEC);
            }
        }
        else if(paramArray[0]==NVTRET_ENTER_MENU)
        {
            Ux_RedrawAllWind();
        }
    }
    else
    {
        Ux_RedrawAllWind();
    }
    //#NT#2009/08/04#Chris Chung -end
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayCopyToCard_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow((VControl *)(&UIMenuWndPlayCopyToCardCtrl), 0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayCopyToCard_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&MenuCommonItemCtrl,0); // close whole tab menu
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayCopyToCard_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_CHANGE_DSCMODE,1,DSCMODE_CHGTO_NEXT);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayCopyToCard_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPlayCopyToCard_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayCopyToCard_Panel)
CTRL_LIST_ITEM(UIMenuWndPlayCopyToCard_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPlayCopyToCard_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayCopyToCard_Panel)
EVENT_END

//----------------------UIMenuWndPlayCopyToCard_MenuCtrl Event---------------------------
INT32 UIMenuWndPlayCopyToCard_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayCopyToCard_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayCopyToCard_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayCopyToCard_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPlayCopyToCard_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPlayCopyToCard_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPlayCopyToCard_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPlayCopyToCard_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayCopyToCard_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayCopyToCard_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/03#Chris Chung -begin
    if(UxMenu_GetData(pCtrl,MNU_CURITM)==UIMenuWndPlayCopyToCard_Menu_STRID_ALL_IMAGES)
    {
        if(GetCardStatus() == CARD_REMOVED)
        {
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_CARD,FLOWWRNMSG_TIMER_2SEC);
            return NVTEVT_CONSUME;
        }
        else
        {
            if(UI_Validate_Storage(STORAGE_CHECK_ERROR, NULL) == FALSE)
            {
                Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_ERR,FLOWWRNMSG_TIMER_2SEC);
                return NVTEVT_CONSUME;
            }

            if(UI_Validate_Storage(STORAGE_CHECK_LOCKED, NULL) == FALSE)
            {
                Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_LOCKED,FLOWWRNMSG_TIMER_2SEC);
                return NVTEVT_CONSUME;
            }
        }

        Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_EXE_COPY2CARD,0);
        Ux_OpenWindow(&UIFlowWndWaitMomentCtrl,1,FLOWWAITMOMENT_MSG_PLEASEWAIT);
    }
    else
    {
        Ux_CloseWindow((VControl *)(&UIMenuWndPlayCopyToCardCtrl), 0);
    }
    //#NT#2009/08/03#Chris Chung -end
    return NVTEVT_CONSUME;
}
