//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPLAYDPOF_H
#define UIMENUWNDPLAYDPOF_H

#include "UIFramework.h"

extern VControl UIMenuWndPlayDPOFCtrl;//Panel type 

extern VControl UIMenuWndPlayDPOF_PanelCtrl;//Panel type 

extern VControl UIMenuWndPlayDPOF_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPlayDPOF_Menu_STRID_SELECT_IMAGES,
UIMenuWndPlayDPOF_Menu_STRID_ALL_IMAGES,
UIMenuWndPlayDPOF_Menu_MAX
}UIMenuWndPlayDPOF_Menu_Setting;

#endif
