//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPlayQuickConfirmDelRes.c"
#include "UIMenuWndPlayQuickConfirmDel.h"
#include "UIPlayObj.h"
#include "UIFlowWndPlay.h"
#include "UIMenuWndPlayQuickDel.h"
#include "UISystemStatusSettings.h"
#include "UIFlowWndWaitMoment.h"
#include "UISystemObj.h"
#include "UIFlow.h"

//---------------------UIMenuWndPlayQuickConfirmDelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayQuickConfirmDel)
CTRL_LIST_ITEM(UIMenuWndPlayQuickConfirmDel_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPlayQuickConfirmDelCtrl Event---------------------------
INT32 UIMenuWndPlayQuickConfirmDel_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickConfirmDel_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickConfirmDel_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickConfirmDel_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickConfirmDel_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickConfirmDel_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickConfirmDel_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayQuickConfirmDel)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPlayQuickConfirmDel_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPlayQuickConfirmDel_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndPlayQuickConfirmDel_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPlayQuickConfirmDel_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPlayQuickConfirmDel_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPlayQuickConfirmDel_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPlayQuickConfirmDel_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPlayQuickConfirmDel_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/05#Chris Chung -begin
    UxMenu_SetData(&UIMenuWndPlayQuickConfirmDel_MenuCtrl, MNU_CURITM, 0);

    if(paramNum > 0)
    {
        UxState_SetData(&UIMenuWndPlayQuickConfirmDel_StatusTextCtrl,STATE_CURITEM,paramArray[0]);
    }
    else
    {
        UIPLAY_ERR(("UIMenuWndPlayConfirmDel_OnOpen: param error\r\n"));
    }
    //#NT#2009/08/05#Chris Chung -end

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickConfirmDel_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickConfirmDel_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/07/29#Chris Chung -begin
    if(paramNum > 0)
    {
        if(paramArray[0]==NVTRET_WAITMOMENT && paramArray[1]==NVTRET_DELETEALL)
        {
            Ux_CloseWindow((VControl *)(&UIMenuWndPlayQuickDelCtrl),1,NVTRET_DELETEALL);
        }
    }
    else
    {
        Ux_RedrawAllWind();
    }
    //#NT#2009/07/29#Chris Chung -end
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickConfirmDel_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow((VControl *)(&UIMenuWndPlayQuickConfirmDelCtrl), 0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickConfirmDel_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow((VControl *)(&UIMenuWndPlayQuickDelCtrl), 0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickConfirmDel_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_CHANGE_DSCMODE,1,DSCMODE_CHGTO_NEXT);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickConfirmDel_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPlayQuickConfirmDel_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayQuickConfirmDel_Panel)
CTRL_LIST_ITEM(UIMenuWndPlayQuickConfirmDel_Menu)
CTRL_LIST_ITEM(UIMenuWndPlayQuickConfirmDel_StatusText)
CTRL_LIST_END

//----------------------UIMenuWndPlayQuickConfirmDel_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayQuickConfirmDel_Panel)
EVENT_END

//----------------------UIMenuWndPlayQuickConfirmDel_MenuCtrl Event---------------------------
INT32 UIMenuWndPlayQuickConfirmDel_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickConfirmDel_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickConfirmDel_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayQuickConfirmDel_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPlayQuickConfirmDel_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPlayQuickConfirmDel_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPlayQuickConfirmDel_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPlayQuickConfirmDel_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickConfirmDel_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickConfirmDel_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/07/27#Chris Chung -begin
    if(UxMenu_GetData(pCtrl,MNU_CURITM)==UIMenuWndPlayQuickConfirmDel_Menu_STRID_OK)
    {
        if(UI_Validate_Storage(STORAGE_CHECK_LOCKED, NULL) == FALSE)
        {
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_LOCKED,FLOWWRNMSG_TIMER_2SEC);
            return NVTEVT_CONSUME;
        }

        switch(UxState_GetData(&UIMenuWndPlayQuickConfirmDel_StatusTextCtrl,STATE_CURITEM))
        {
        case UIMenuWndPlayQuickConfirmDel_StatusText_STRID_ERASE_THIS:

            if(UIPlay_GetData(PLAY_LOCKSTATUS))
            {
                Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_FILE_PROTECTED,FLOWWRNMSG_TIMER_2SEC);
                return NVTEVT_CONSUME;
            }

            Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_EXE_DEL,1,0);
            Ux_CloseWindow((VControl *)(&UIMenuWndPlayQuickDelCtrl),1,NVTRET_DELETE);
            break;
        case UIMenuWndPlayQuickConfirmDel_StatusText_STRID_ERASE_ALL:
            Ux_OpenWindow(&UIFlowWndWaitMomentCtrl,1,FLOWWAITMOMENT_MSG_PLEASEWAIT);
            Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_EXE_DEL,1,1);
            break;
        default:
            debug_err(("UIMenuWndPlayQuickConfirmDel_Menu_OnKeyEnter: status text error\r\n"));
        }
    }
    else
    {
        Ux_CloseWindow((VControl *)(&UIMenuWndPlayQuickDelCtrl), 0);
    }
    //#NT#2009/07/27#Chris Chung -end
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPlayQuickConfirmDel_StatusTextCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayQuickConfirmDel_StatusText)
EVENT_END

