//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndTouchTest_CalRes.c"
#include "UIFlowWndTouchTest_Cal.h"
//-------------------------------------------------------------------------------------------------
#include "Gesture_Public.h"
#include "KeyScanTsk.h"

static volatile BOOL UIFlowWndTouchTest_TLCal = FALSE;
static volatile BOOL UIFlowWndTouchTest_BRCal = FALSE;
static UINT32 UIFlowWndTouchTest_TimerId = TIMER_NULL;
//---------------------UIFlowWndTouchTest_CalCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndTouchTest_Cal)
CTRL_LIST_ITEM(UIFlowTouchTest_Cal_Panel)
CTRL_LIST_ITEM(UIFlowTouchTest_Cal_Static_TL)
CTRL_LIST_ITEM(UIFlowTouchTest_Cal_Static_BR)
CTRL_LIST_ITEM(UIFlowTouchTest_Cal_Status)
CTRL_LIST_END

//----------------------UIFlowWndTouchTest_CalCtrl Event---------------------------
INT32 UIFlowWndTouchTest_Cal_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndTouchTest_Cal_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndTouchTest_Cal)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndTouchTest_Cal_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndTouchTest_Cal_OnClose)
EVENT_END

INT32 UIFlowWndTouchTest_Cal_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    KeyScan_SetDetTP(FALSE);
    TimerDelayMs(100);
    UIFlowWndTouchTest_TimerId = KeyScan_startTimer(20, NVTEVT_SELFTIMER, TIMER_TYPE_CONTINUE);
    if(UIFlowWndTouchTest_TimerId == TIMER_NULL)
    {
        debug_err(("UIFlowWndTouchTest_Cal_OnOpen:Timer is null\r\n"));
    }

    UIFlowWndTouchTest_TLCal = FALSE;
    UIFlowWndTouchTest_BRCal = FALSE;
    UxState_SetItemData(
        &UIFlowTouchTest_Cal_StatusCtrl,
        0,
        STATE_ITEM_STRID,
        Txt_Pointer("Please touch Top-Left red point."));
    Ux_Redraw();

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndTouchTest_Cal_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------UIFlowTouchTest_Cal_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowTouchTest_Cal_Panel)
CTRL_LIST_END

//----------------------UIFlowTouchTest_Cal_PanelCtrl Event---------------------------
INT32 UIFlowTouchTest_Cal_Panel_OnTimer(VControl *, UINT32, UINT32 *);
INT32 UIFlowTouchTest_Cal_Panel_OnTouchPanelDoubleClick(VControl *, UINT32, UINT32 *);
INT32 UIFlowTouchTest_Cal_Panel_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowTouchTest_Cal_Panel)
EVENT_ITEM(NVTEVT_TIMER,UIFlowTouchTest_Cal_Panel_OnTimer)
EVENT_ITEM(NVTEVT_DOUBLECLICK,UIFlowTouchTest_Cal_Panel_OnTouchPanelDoubleClick)
EVENT_ITEM(NVTEVT_RELEASE,UIFlowTouchTest_Cal_Panel_OnTouchPanelRelease)
EVENT_END

INT32 UIFlowTouchTest_Cal_Panel_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //debug_msg(("UIFlowTouchTest_Cal_Panel_OnTimer:%d-%d\r\n",paramNum,paramArray[0]));
    if( paramNum == 1 &&
        paramArray[0] == NVTEVT_SELFTIMER)
    {
        if(UIFlowWndTouchTest_TLCal)
        {
            if(UIFlowWndTouchTest_BRCal)
            {
                KeyScan_stopTimer(&UIFlowWndTouchTest_TimerId);
                if(UIFlowWndTouchTest_TimerId != TIMER_NULL)
                {
                    debug_err(("UIFlowTouchTest_Cal_Panel_OnTimer:Timer is not null\r\n"));
                }
            }
            else
            {
                if(Gesture_DetCalData(GESTURE_CAL_TYPE_BOTTOM_RIGHT))
                {
                    UIFlowWndTouchTest_BRCal = TRUE;
                    Gesture_Cal();
                    KeyScan_SetDetTP(TRUE);
                    UxState_SetItemData(
                        &UIFlowTouchTest_Cal_StatusCtrl,
                        0,
                        STATE_ITEM_STRID,
                        Txt_Pointer("Touch calibration finish!"));
                    Ux_Redraw();
                }
            }
        }
        else
        {
            if(Gesture_DetCalData(GESTURE_CAL_TYPE_TOP_LEFT))
            {
                KeyScan_SetDetTP(TRUE);
                UIFlowWndTouchTest_TLCal = TRUE;
                KeyScan_stopTimer(&UIFlowWndTouchTest_TimerId);
                UxState_SetItemData(
                    &UIFlowTouchTest_Cal_StatusCtrl,
                    0,
                    STATE_ITEM_STRID,
                    Txt_Pointer("Please touch Bottom-Right red point."));
                Ux_Redraw();
            }
        }
    }
    return NVTEVT_CONSUME;
}
INT32 UIFlowTouchTest_Cal_Panel_OnTouchPanelDoubleClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if( UIFlowWndTouchTest_TLCal &&
        UIFlowWndTouchTest_BRCal)
    {
        Ux_CloseWindow((VControl *)(&UIFlowWndTouchTest_CalCtrl), 0);
        Ux_Redraw();
    }
    return NVTEVT_CONSUME;
}
INT32 UIFlowTouchTest_Cal_Panel_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if( UIFlowWndTouchTest_TLCal &&
        !UIFlowWndTouchTest_BRCal)
    {
        KeyScan_SetDetTP(FALSE);
        TimerDelayMs(100);
        UIFlowWndTouchTest_TimerId = KeyScan_startTimer(20, NVTEVT_SELFTIMER, TIMER_TYPE_CONTINUE);
    }
    return NVTEVT_CONSUME;
}
//----------------------UIFlowTouchTest_Cal_Static_TLCtrl Event---------------------------
EVENT_BEGIN(UIFlowTouchTest_Cal_Static_TL)
EVENT_END

//----------------------UIFlowTouchTest_Cal_Static_BRCtrl Event---------------------------
EVENT_BEGIN(UIFlowTouchTest_Cal_Static_BR)
EVENT_END

//----------------------UIFlowTouchTest_Cal_StatusCtrl Event---------------------------
EVENT_BEGIN(UIFlowTouchTest_Cal_Status)
EVENT_END

