//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDTOUCHTEST_CALRES_H
#define UIFLOWWNDTOUCHTEST_CALRES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_MAP_BEGIN(Skin1)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin1,0,0,319,239)

SHOW_ITEM_RECT(CMD_Rectangle,Skin2Rect,0,0,319,239,0,0,2,2,0,0,0)
SHOW_MAP_BEGIN(Skin2)
SHOW_MAP_BODY(Skin2Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin2,0,0,319,239)

SHOW_MAP_BEGIN(UIFlowTouchTest_Cal_Panel)
SHOW_MAP_BODY(Skin2)
SHOW_MAP_END

DECLARE_EVENT(UIFlowTouchTest_Cal_Panel)
DECLARE_CTRL_LIST(UIFlowTouchTest_Cal_Panel)
CREATE_CTRL(UIFlowTouchTest_Cal_Panel,UIFlowTouchTest_Cal_Panel,CTRL_WND,NULL,0 ,0,0,319,239)
SHOW_ITEM_RECT(CMD_Rectangle,Skin4Rect,0,0,9,9,0,0,3,3,0,0,0)
SHOW_MAP_BEGIN(Skin4)
SHOW_MAP_BODY(Skin4Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin4,0,0,9,9)

SHOW_ITEM_TEXT(CMD_Text|CMD_ITEM,Text6,0,0,9,9,STRID_NULL,0,0,0,0,1,1,1,0,0,17,0,0,0,0)
SHOW_MAP_BEGIN(Normal3)
SHOW_MAP_BODY(Skin4)
SHOW_MAP_BODY(Text6)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal3,0,0,9,9)

SHOW_MAP_BEGIN(UIFlowTouchTest_Cal_Static_TL)
SHOW_MAP_BODY(Normal3)
SHOW_MAP_END

DECLARE_EVENT(UIFlowTouchTest_Cal_Static_TL)
CREATE_STATIC_DATA(UIFlowTouchTest_Cal_Static_TL,STRID_NULL)
CREATE_STATIC_CTRL(UIFlowTouchTest_Cal_Static_TL,0,0,0,9,9)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle,Skin9Rect,0,0,9,9,0,0,3,3,0,0,0)
SHOW_MAP_BEGIN(Skin9)
SHOW_MAP_BODY(Skin9Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin9,0,0,9,9)

SHOW_ITEM_TEXT(CMD_Text|CMD_ITEM,Text11,0,0,9,9,STRID_NULL,0,0,0,0,1,1,1,0,0,17,0,0,0,0)
SHOW_MAP_BEGIN(Normal8)
SHOW_MAP_BODY(Skin9)
SHOW_MAP_BODY(Text11)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal8,310,230,319,239)

SHOW_MAP_BEGIN(UIFlowTouchTest_Cal_Static_BR)
SHOW_MAP_BODY(Normal8)
SHOW_MAP_END

DECLARE_EVENT(UIFlowTouchTest_Cal_Static_BR)
CREATE_STATIC_DATA(UIFlowTouchTest_Cal_Static_BR,)
CREATE_STATIC_CTRL(UIFlowTouchTest_Cal_Static_BR,0,310,230,319,239)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle,Skin14Rect,0,0,299,49,0,0,2,2,0,0,0)
SHOW_MAP_BEGIN(Skin14)
SHOW_MAP_BODY(Skin14Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin14,0,0,299,49)

SHOW_ITEM_TEXT(CMD_Text|CMD_ITEM,Text16,0,0,299,49,STRID_NULL,0,0,0,0,1,1,1,256,0,17,0,0,0,0)
SHOW_MAP_BEGIN(Normal13)
SHOW_MAP_BODY(Skin14)
SHOW_MAP_BODY(Text16)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal13,9,95,308,144)

CREATE_STATE_ITEM_DATA(STRID_NULL17,STRID_NULL,ICONID_NULL,NULL) 
SHOW_MAP_BEGIN(UIFlowTouchTest_Cal_Status)
SHOW_MAP_BODY(Normal13)
SHOW_MAP_END

DECLARE_EVENT(UIFlowTouchTest_Cal_Status)
STATE_LIST_BEGIN(UIFlowTouchTest_Cal_Status)
STATE_LIST_ITEM(STRID_NULL17)
STATE_LIST_END

CREATE_STATE_DATA(UIFlowTouchTest_Cal_Status,0)
CREATE_STATE_CTRL(UIFlowTouchTest_Cal_Status,0,9,95,308,144)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(UIFlowWndTouchTest_Cal)
SHOW_MAP_BODY(Skin1)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndTouchTest_Cal)
DECLARE_CTRL_LIST(UIFlowWndTouchTest_Cal)
CREATE_CTRL(UIFlowWndTouchTest_Cal,UIFlowWndTouchTest_Cal,CTRL_WND,NULL,0 ,0,0,319,239)
#endif
