//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDTOUCHTEST_H
#define UIFLOWWNDTOUCHTEST_H

#include "UIFramework.h"

extern VControl UIFlowWndTouchTestCtrl;//Panel type 

extern VControl UIFlowTouchTest_PanelCtrl;//Panel type 

extern VControl UIFlowTouchTest_MenuCtrl;//Menu type 

typedef enum
{
UIFlowTouchTest_Menu_STRID_A0,
UIFlowTouchTest_Menu_STRID_A1,
UIFlowTouchTest_Menu_STRID_A2,
UIFlowTouchTest_Menu_STRID_A3,
UIFlowTouchTest_Menu_MAX
}UIFlowTouchTest_Menu_Setting;

extern VControl UIFlowTouchTest_Status_MenuCtrl;//Status type 

typedef enum
{
UIFlowTouchTest_Status_Menu_STRID_A0,
UIFlowTouchTest_Status_Menu_STRID_A1,
UIFlowTouchTest_Status_Menu_STRID_A2,
UIFlowTouchTest_Status_Menu_STRID_A3,
UIFlowTouchTest_Status_Menu_MAX
}UIFlowTouchTest_Status_Menu_Setting;

extern VControl UIFlowTouchTest_Button_UpCtrl;//Button type 

extern VControl UIFlowTouchTest_Button_DownCtrl;//Button type 

extern VControl UIFlowTouchTest_StatusCtrl;//Status type 

typedef enum
{
UIFlowTouchTest_Status_STRID_NULL,
UIFlowTouchTest_Status_MAX
}UIFlowTouchTest_Status_Setting;

extern VControl UIFlowTouchTest_ScrollBarCtrl;//ScrollBar type 

#endif
