//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDTOUCHTEST_CAL_H
#define UIFLOWWNDTOUCHTEST_CAL_H

#include "UIFramework.h"

extern VControl UIFlowWndTouchTest_CalCtrl;//Panel type 

extern VControl UIFlowTouchTest_Cal_PanelCtrl;//Panel type 

extern VControl UIFlowTouchTest_Cal_Static_TLCtrl;//Static type 

extern VControl UIFlowTouchTest_Cal_Static_BRCtrl;//Static type 

extern VControl UIFlowTouchTest_Cal_StatusCtrl;//Status type 

typedef enum
{
UIFlowTouchTest_Cal_Status_STRID_NULL,
UIFlowTouchTest_Cal_Status_MAX
}UIFlowTouchTest_Cal_Status_Setting;

#endif
