//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndTouchTestRes.c"
#include "UIFlowWndTouchTest.h"
//-------------------------------------------------------------------------------------------------
#include "UIFlowWndTouchTest_Cal.h"
#define UIFlowWndTouchTest_SCROLLBAR_THUMB_WIDTH    40
static UINT8 UIFlowWndTouchTest_Count[10];
//-------------------------------------------------------------------------------------------------
void UIFlowWndTouchTest_FixScrollBarThumbPos(UINT32* pData)
{
    if((*pData) <= (UIFlowWndTouchTest_SCROLLBAR_THUMB_WIDTH/2))
    {
       (*pData) = 0; 
    }
    else
    {
       (*pData) -= (UIFlowWndTouchTest_SCROLLBAR_THUMB_WIDTH/2); 
    }
}
//-------------------------------------------------------------------------------------------------
void UIFlowWndTouchTest_RefreshStatus(void)
{
    sprintf((char*)UIFlowWndTouchTest_Count,"%d",UxScrollBar_GetData(&UIFlowTouchTest_ScrollBarCtrl,SCRBAR_CURSTP));
    UxState_SetItemData(
        &UIFlowTouchTest_StatusCtrl,
        0,
        STATE_ITEM_STRID,
        Txt_Pointer(UIFlowWndTouchTest_Count));
    Ux_Redraw();
}
//---------------------UIFlowWndTouchTestCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndTouchTest)
CTRL_LIST_ITEM(UIFlowTouchTest_Panel)
CTRL_LIST_ITEM(UIFlowTouchTest_Menu)
CTRL_LIST_ITEM(UIFlowTouchTest_Status_Menu)
CTRL_LIST_ITEM(UIFlowTouchTest_Button_Up)
CTRL_LIST_ITEM(UIFlowTouchTest_Button_Down)
CTRL_LIST_ITEM(UIFlowTouchTest_Status)
CTRL_LIST_ITEM(UIFlowTouchTest_ScrollBar)
CTRL_LIST_END

//----------------------UIFlowWndTouchTestCtrl Event---------------------------
INT32 UIFlowWndTouchTest_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndTouchTest_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndTouchTest)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndTouchTest_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndTouchTest_OnClose)
EVENT_END

INT32 UIFlowWndTouchTest_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_PRESS,paramNum,paramArray);
    sprintf((char*)UIFlowWndTouchTest_Count,"0");
    UxState_SetItemData(
        &UIFlowTouchTest_StatusCtrl,
        0,
        STATE_ITEM_STRID,
        Txt_Pointer(UIFlowWndTouchTest_Count));
    Ux_Redraw();
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndTouchTest_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------UIFlowTouchTest_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowTouchTest_Panel)
CTRL_LIST_END

//----------------------UIFlowTouchTest_PanelCtrl Event---------------------------
EVENT_BEGIN(UIFlowTouchTest_Panel)
EVENT_END

//----------------------UIFlowTouchTest_MenuCtrl Event---------------------------
INT32 UIFlowTouchTest_Menu_OnTouchPanelDoubleClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowTouchTest_Menu)
EVENT_ITEM(NVTEVT_DOUBLECLICK,UIFlowTouchTest_Menu_OnTouchPanelDoubleClick)
EVENT_END

INT32 UIFlowTouchTest_Menu_OnTouchPanelDoubleClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxState_SetData(
        &UIFlowTouchTest_Status_MenuCtrl,
        STATE_CURITEM,
        UxMenu_GetData(pCtrl, MNU_CURITM));
    return NVTEVT_CONSUME;
}
//----------------------UIFlowTouchTest_Status_MenuCtrl Event---------------------------
INT32 UIFlowTouchTest_Status_Menu_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowTouchTest_Status_Menu)
EVENT_ITEM(NVTEVT_CLICK,UIFlowTouchTest_Status_Menu_OnTouchPanelClick)
EVENT_END

INT32 UIFlowTouchTest_Status_Menu_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowTouchTest_Button_UpCtrl Event---------------------------
INT32 UIFlowTouchTest_Button_Up_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIFlowTouchTest_Button_Up_OnTouchPanelMove(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowTouchTest_Button_Up)
EVENT_ITEM(NVTEVT_PRESS,UIFlowTouchTest_Button_Up_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_MOVE,UIFlowTouchTest_Button_Up_OnTouchPanelMove)
EVENT_END

INT32 UIFlowTouchTest_Button_Up_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  TempStep;

    Ux_DefaultEvent(pCtrl,NVTEVT_PRESS,paramNum,paramArray);

    if(UxScrollBar_GetData(&UIFlowTouchTest_ScrollBarCtrl,SCRBAR_CURSTP) == 0)
    {
        TempStep = 0;
    }
    else
    {
        TempStep = UxScrollBar_GetData(&UIFlowTouchTest_ScrollBarCtrl,SCRBAR_CURSTP)-1;
    }
    UxScrollBar_SetData(&UIFlowTouchTest_ScrollBarCtrl, SCRBAR_CURSTP, TempStep);
    UIFlowWndTouchTest_RefreshStatus();
    return NVTEVT_CONSUME;
}
INT32 UIFlowTouchTest_Button_Up_OnTouchPanelMove(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_MOVE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowTouchTest_Button_DownCtrl Event---------------------------
INT32 UIFlowTouchTest_Button_Down_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIFlowTouchTest_Button_Down_OnTouchPanelMove(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowTouchTest_Button_Down)
EVENT_ITEM(NVTEVT_PRESS,UIFlowTouchTest_Button_Down_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_MOVE,UIFlowTouchTest_Button_Down_OnTouchPanelMove)
EVENT_END

INT32 UIFlowTouchTest_Button_Down_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  TempStep;

    Ux_DefaultEvent(pCtrl,NVTEVT_PRESS,paramNum,paramArray);

    if(UxScrollBar_GetData(&UIFlowTouchTest_ScrollBarCtrl,SCRBAR_CURSTP) > UxScrollBar_GetData(&UIFlowTouchTest_ScrollBarCtrl,SCRBAR_TOTSTP))
    {
        TempStep = UxScrollBar_GetData(&UIFlowTouchTest_ScrollBarCtrl,SCRBAR_TOTSTP);
    }
    else
    {
        TempStep = UxScrollBar_GetData(&UIFlowTouchTest_ScrollBarCtrl,SCRBAR_CURSTP)+1;
    }
    UxScrollBar_SetData(&UIFlowTouchTest_ScrollBarCtrl, SCRBAR_CURSTP, TempStep);
    UIFlowWndTouchTest_RefreshStatus();
    return NVTEVT_CONSUME;
}
INT32 UIFlowTouchTest_Button_Down_OnTouchPanelMove(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_MOVE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowTouchTest_StatusCtrl Event---------------------------
EVENT_BEGIN(UIFlowTouchTest_Status)
EVENT_END

//----------------------UIFlowTouchTest_ScrollBarCtrl Event---------------------------
INT32 UIFlowTouchTest_ScrollBar_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIFlowTouchTest_ScrollBar_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
INT32 UIFlowTouchTest_ScrollBar_OnTouchPanelMove(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowTouchTest_ScrollBar)
EVENT_ITEM(NVTEVT_PRESS,UIFlowTouchTest_ScrollBar_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_RELEASE,UIFlowTouchTest_ScrollBar_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_MOVE,UIFlowTouchTest_ScrollBar_OnTouchPanelMove)
EVENT_END

INT32 UIFlowTouchTest_ScrollBar_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIFlowWndTouchTest_FixScrollBarThumbPos(&(paramArray[1]));
    Ux_DefaultEvent(pCtrl,NVTEVT_PRESS,paramNum,paramArray);
    UIFlowWndTouchTest_RefreshStatus();
    return NVTEVT_CONSUME;
}
INT32 UIFlowTouchTest_ScrollBar_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIFlowWndTouchTest_FixScrollBarThumbPos(&(paramArray[1]));
    Ux_DefaultEvent(pCtrl,NVTEVT_RELEASE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowTouchTest_ScrollBar_OnTouchPanelMove(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIFlowWndTouchTest_FixScrollBarThumbPos(&(paramArray[1]));
    Ux_DefaultEvent(pCtrl,NVTEVT_MOVE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
