//This source code is generated by UI Designer Studio.

#ifndef MENUCOMMONEFFECT_H
#define MENUCOMMONEFFECT_H

#include "UIFramework.h"

extern VControl MenuCommonEffectCtrl;//Panel type 

extern VControl MenuCommonEffect_PanelCtrl;//Panel type 

extern VControl MenuCommonEffect_MenuCtrl;//Menu type 

typedef enum
{
MenuCommonEffect_Menu_STRID_A0,
MenuCommonEffect_Menu_STRID_A1,
MenuCommonEffect_Menu_STRID_A2,
MenuCommonEffect_Menu_STRID_A3,
MenuCommonEffect_Menu_STRID_A4,
MenuCommonEffect_Menu_STRID_A5,
MenuCommonEffect_Menu_STRID_A6,
MenuCommonEffect_Menu_STRID_A7,
MenuCommonEffect_Menu_STRID_A8,
MenuCommonEffect_Menu_STRID_A9,
MenuCommonEffect_Menu_MAX
}MenuCommonEffect_Menu_Setting;

#endif
