//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndUSBRes.c"
#include "UIMenuWndUSB.h"
#include "UISystemObj.h"
#include "PrimaryTsk.h"

//---------------------UIMenuWndUSBCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndUSB)
CTRL_LIST_ITEM(UIMenuWndUSB_Background)
CTRL_LIST_ITEM(UIMenuWndUSB_TitleBar)
CTRL_LIST_ITEM(UIMenuWndUSB_TipsBar)
CTRL_LIST_ITEM(UIMenuWndUSB_Item)
CTRL_LIST_END

//----------------------UIMenuWndUSBCtrl Event---------------------------
INT32 UIMenuWndUSB_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndUSB_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndUSB_OnChildClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndUSB)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndUSB_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndUSB_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndUSB_OnChildClose)
EVENT_END

INT32 UIMenuWndUSB_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndUSB_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndUSB_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndUSB_BackgroundCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndUSB_Background)
CTRL_LIST_END

//----------------------UIMenuWndUSB_BackgroundCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndUSB_Background)
EVENT_END

//---------------------UIMenuWndUSB_TitleBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndUSB_TitleBar)
CTRL_LIST_ITEM(UIMenuWndUSB_TitleName)
CTRL_LIST_END

//----------------------UIMenuWndUSB_TitleBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndUSB_TitleBar)
EVENT_END

//----------------------UIMenuWndUSB_TitleNameCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndUSB_TitleName)
EVENT_END

//---------------------UIMenuWndUSB_TipsBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndUSB_TipsBar)
CTRL_LIST_ITEM(UIMenuWndUSB_UDOKTips)
CTRL_LIST_END

//----------------------UIMenuWndUSB_TipsBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndUSB_TipsBar)
EVENT_END

//---------------------UIMenuWndUSB_UDOKTipsCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndUSB_UDOKTips)
CTRL_LIST_END

//----------------------UIMenuWndUSB_UDOKTipsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndUSB_UDOKTips)
EVENT_END

//----------------------UIMenuWndUSB_ItemCtrl Event---------------------------
INT32 UIMenuWndUSB_Item_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndUSB_Item_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndUSB_Item_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndUSB_Item_OnKeyDisplay(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndUSB_Item)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndUSB_Item_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndUSB_Item_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndUSB_Item_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_DISPLAY,UIMenuWndUSB_Item_OnKeyDisplay)
EVENT_END

INT32 UIMenuWndUSB_Item_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 UINT32  uiKeyAct;

   uiKeyAct = paramArray[0];

    switch(uiKeyAct)
    {
    case NVTEVT_KEY_PRESS:
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
	break;
    	}
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndUSB_Item_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 UINT32  uiKeyAct;

   uiKeyAct = paramArray[0];

    switch(uiKeyAct)
    {
    case NVTEVT_KEY_PRESS:
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
	break;
    	}
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndUSB_Item_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  item;

    item = UxMenu_GetData(pCtrl,MNU_CURITM);
    Ux_CloseWindow(&UIMenuWndUSBCtrl, 0);
    if (item == 2)//pictbridge is usb power
    {
        //Ux_SendEvent(&UISystemObjCtrl,NVTEVT_EXE_USB,1,item);
        KeyScan_SetUSBPower(TRUE);
        KeyScan_EnableAutoPoweroff(TRUE);//jack lan added 2011.11.30			
        Primary_ChangeMode(PRIMARY_MODE_MOVIE);
    }else
    {
        Ux_SendEvent(&UISystemObjCtrl,NVTEVT_EXE_USB,1,item);
    }

    return NVTEVT_CONSUME;
}
INT32 UIMenuWndUSB_Item_OnKeyDisplay(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;

    uiKeyAct = paramArray[0];

    switch(uiKeyAct)
    {
    case NVTEVT_KEY_PRESS:
        Ux_SendEvent(&UISystemObjCtrl,NVTEVT_EXE_DISPLAY,1,DISPLAY_NORMAL);
    break;
    }
    return NVTEVT_CONSUME;
}

