//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPrint_PrintProgressRes.c"
#include "UIMenuWndPrint_PrintProgress.h"
//-------------------------------------------------------------------------------------------------
#include "UIPrintObj.h"
#include "UIFlow.h"

//-------------------------------------------------------------------------------------------------
extern int sprintf(char * /*s*/, const char * /*format*/, ...);
static UINT8 UIMenuWndPrint_PrintProgress_String_PrintCount[10];
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_PrintProgress_Confirm_Menu_Confirm(VControl *pCtrl)
{
    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
    {
        case UIMenuWndPrint_PrintProgress_Confirm_Menu_STRID_CANCEL:
        {
            Ux_OpenWindow(&UIMenuWndPrint_ConfirmCtrl, 1,UIMenuWndPrint_Confirm_STATE_CONFIRM_STOP);
            break;
        }

        default:
        {
            break;
        }
    }

    Ux_Redraw();
}
//---------------------UIMenuWndPrint_PrintProgress Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintProgress)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_Content_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_Confirm_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_Status_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_Progress_Status)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintProgress Event---------------------------
INT32 UIMenuWndPrint_PrintProgress_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintProgress_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintProgress_OnPrintDpsEvent(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_PrintProgress)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPrint_PrintProgress_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPrint_PrintProgress_OnClose)
EVENT_ITEM(NVTEVT_CB_PRINT_DPS_EVENT,UIMenuWndPrint_PrintProgress_OnPrintDpsEvent)
EVENT_END

INT32 UIMenuWndPrint_PrintProgress_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT16 Current, Total;

    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);

    if(paramNum > 0)
    {
        switch(paramArray[0])
        {
            case DPS_EVENT_START_JOB_OK:
            {
                UxState_SetData(
                    &UIMenuWndPrint_PrintProgress_Status_StatusCtrl,
                    STATE_CURITEM,
                    UIMenuWndPrint_PrintProgress_Status_Status_STRID_PRINTING);
                UIPrint_GetJobStatus(&Current, &Total);
                sprintf((char*)UIMenuWndPrint_PrintProgress_String_PrintCount,"%d/%d",Current,Total);
                UxState_SetItemData(
                    &UIMenuWndPrint_PrintProgress_Progress_StatusCtrl,
                    0,
                    STATE_ITEM_STRID,
                    Txt_Pointer(UIMenuWndPrint_PrintProgress_String_PrintCount));
                break;
            }

            default:
            {
                break;
            }
        }
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintProgress_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintProgress_OnPrintDpsEvent(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT16 Current, Total;

    if(paramNum > 0)
    {
        switch(paramArray[0])
        {
            case DPS_EVENT_NOTIFY_JOB:
            {
                UxState_SetData(
                    &UIMenuWndPrint_PrintProgress_Status_StatusCtrl,
                    STATE_CURITEM,
                    UIMenuWndPrint_PrintProgress_Status_Status_STRID_PRINTING);
                UIPrint_GetJobStatus(&Current, &Total);
                sprintf((char*)UIMenuWndPrint_PrintProgress_String_PrintCount,"%d/%d",Current,Total);
                UxState_SetItemData(
                    &UIMenuWndPrint_PrintProgress_Progress_StatusCtrl,
                    0,
                    STATE_ITEM_STRID,
                    Txt_Pointer(UIMenuWndPrint_PrintProgress_String_PrintCount));
                UIPrint_PostNextDpsEvent();
                break;
            }

            case DPS_EVENT_PRINT_FINISH:
            {
                Ux_OpenWindow(&UIMenuWndPrint_ConfirmCtrl, 2,UIMenuWndPrint_Confirm_STATE_PRINTING, paramArray[0]);
                break;
            }

            case DPS_EVENT_DISCONNET_ENABLE:
            {
                UxState_SetData(
                    &UIMenuWndPrint_PrintProgress_Status_StatusCtrl,
                    STATE_CURITEM,
                    UIMenuWndPrint_PrintProgress_Status_Status_STRID_PRINTER_DISCONNECTABLE);
                UIPrint_PostNextDpsEvent();
                break;
            }

            default:
            {
                UIPrint_ShowNotification(
                    UIMenuWndPrint_Confirm_STATE_PRINTING,
                    paramArray[0]);
                break;
            }
        }
    }
    Ux_Redraw();
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPrint_PrintProgress_Content_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintProgress_Content_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintProgress_Content_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_Content_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintProgress_Title_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintProgress_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_Title_Text_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_Title_Icon_Status)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintProgress_Title_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_Title_Panel)
EVENT_END

//----------------------UIMenuWndPrint_PrintProgress_Title_Text_Status Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_Title_Text_Status)
EVENT_END

//----------------------UIMenuWndPrint_PrintProgress_Title_Icon_Status Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_Title_Icon_Status)
EVENT_END

//---------------------UIMenuWndPrint_PrintProgress_End_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintProgress_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_End_Dir_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintProgress_End_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_End_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintProgress_End_Dir_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintProgress_End_Dir_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintProgress_End_Dir_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_End_Dir_Panel)
EVENT_END

//----------------------UIMenuWndPrint_PrintProgress_Confirm_Menu Event---------------------------
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_Confirm_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_UP == UIPRINT_KEYMAP_UP)
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_DOWN == UIPRINT_KEYMAP_DOWN)
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_RIGHT == UIPRINT_KEYMAP_RIGHT)
    UIMenuWndPrint_PrintProgress_Confirm_Menu_Confirm(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ENTER == UIPRINT_KEYMAP_ENTER)
    UIMenuWndPrint_PrintProgress_Confirm_Menu_Confirm(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ZOOMOUT == UIPRINT_KEYMAP_DOWN)
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ZOOMIN == UIPRINT_KEYMAP_UP)
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_SHUTTER2 == UIPRINT_KEYMAP_ENTER)
    UIMenuWndPrint_PrintProgress_Confirm_Menu_Confirm(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPrint_PrintProgress_Status_Status Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_Status_Status)
EVENT_END

//----------------------UIMenuWndPrint_PrintProgress_Progress_Status Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_Progress_Status)
EVENT_END

