//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPrint_Crop.h"
#include "UIMenuWndPrint_CropRes.c"
//-------------------------------------------------------------------------------------------------
#include "GlobalVar.h"
#include "UIFlow.h"
#include "UIPrintObj.h"
#include "UIFlowWndPrint.h"
#include "UIMenuPrintSettings.h"
#include "UIMenuWndPrint.h"

static Ux_RECT UIMenuWndPrint_Crop_WinRect;
static UIMenuWndPrint_Crop_OPER_ENUM UIMenuWndPrint_Crop_Oper;
//-------------------------------------------------------------------------------------------------
//#NT#2011/06/14#Chris Chung -begin
//#NT#The crop rect should refer to the width and height of OSD.
void UIMenuWndPrint_Crop_OnKeyMenu_Function(void)
{
    UIPRINT_CROP_STRUCT TempCrop;

    switch(UIMenuWndPrint_Crop_Oper)
    {
        case UIMenuWndPrint_Crop_OPER_SIZE:
        case UIMenuWndPrint_Crop_OPER_POS:
        {
            TempCrop.CropX = (UIMenuWndPrint_Crop_WinRect.x1 * UIPrint_Playback_GetCurrWidth())/OSD_W;
            TempCrop.CropY = (UIMenuWndPrint_Crop_WinRect.y1 * UIPrint_Playback_GetCurrHeight())/OSD_H;
            TempCrop.CropW = ((UIMenuWndPrint_Crop_WinRect.x2 - UIMenuWndPrint_Crop_WinRect.x1+1)*UIPrint_Playback_GetCurrWidth())/OSD_W;
            TempCrop.CropH = ((UIMenuWndPrint_Crop_WinRect.y2 - UIMenuWndPrint_Crop_WinRect.y1+1)*UIPrint_Playback_GetCurrHeight())/OSD_H;

            UIPrint_Image_SetCrop(&TempCrop);
            Ux_SendEvent(
                &UIPrintObjCtrl,
                NVTEVT_PRINT_SET_JOB_CONFIG,
                2,
                DPS_CAPITEM_CROPPINGS,
                DPS_CAP_CROPPINGS_ON);
            break;
        }

        default:
        {

            break;
        }
    }

    Ux_CloseWindow(&UIMenuWndPrint_CropCtrl, 0);
}
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_Crop_OnKeyEnter_Function(void)
{
    switch(UIMenuWndPrint_Crop_Oper)
    {
        case UIMenuWndPrint_Crop_OPER_NONE:
        {
            UIMenuWndPrint_Crop_Oper = UIMenuWndPrint_Crop_OPER_SIZE;
            break;
        }

        case UIMenuWndPrint_Crop_OPER_SIZE:
        {
            UIMenuWndPrint_Crop_Oper = UIMenuWndPrint_Crop_OPER_POS;
            break;
        }

        case UIMenuWndPrint_Crop_OPER_POS:
        {
            UIMenuWndPrint_Crop_Oper = UIMenuWndPrint_Crop_OPER_SIZE;
            break;
        }

        default:
        {
            break;
        }
    }
}
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_Crop_OnKeyUp_Function(VControl *pCtrl)
{
    switch(UIMenuWndPrint_Crop_Oper)
    {
        case UIMenuWndPrint_Crop_OPER_SIZE:
        {
            if(UIMenuWndPrint_Crop_WinRect.y2 > (UIMenuWndPrint_Crop_WinRect.y1+UIMenuWndPrint_Crop_WIN_STEP))
            {
                UIMenuWndPrint_Crop_WinRect.y2 -= UIMenuWndPrint_Crop_WIN_STEP;
            }
            break;
        }

        case UIMenuWndPrint_Crop_OPER_POS:
        {
            if(UIMenuWndPrint_Crop_WinRect.y1 >= UIMenuWndPrint_Crop_WIN_STEP)
            {
                UIMenuWndPrint_Crop_WinRect.y1 -= UIMenuWndPrint_Crop_WIN_STEP;
                UIMenuWndPrint_Crop_WinRect.y2 -= UIMenuWndPrint_Crop_WIN_STEP;
            }
            break;
        }

        default:
        {
            break;
        }
    }

    UxZoom_SetPosition(
        &UIMenuWndPrint_Crop_ZoomWinCtrl,
        ZOOM_INTERNAL_RECT,
        &UIMenuWndPrint_Crop_WinRect);
    UxCtrl_SetDirty(pCtrl, TRUE);
    Ux_Redraw();
}
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_Crop_OnKeyDown_Function(VControl *pCtrl)
{
    switch(UIMenuWndPrint_Crop_Oper)
    {
        case UIMenuWndPrint_Crop_OPER_SIZE:
        {
            if(UIMenuWndPrint_Crop_WinRect.y2 <= (OSD_H-UIMenuWndPrint_Crop_WIN_STEP))
            {
                UIMenuWndPrint_Crop_WinRect.y2 += UIMenuWndPrint_Crop_WIN_STEP;
            }
            break;
        }

        case UIMenuWndPrint_Crop_OPER_POS:
        {
            if(UIMenuWndPrint_Crop_WinRect.y2 <= (OSD_H-UIMenuWndPrint_Crop_WIN_STEP))
            {
                UIMenuWndPrint_Crop_WinRect.y1 += UIMenuWndPrint_Crop_WIN_STEP;
                UIMenuWndPrint_Crop_WinRect.y2 += UIMenuWndPrint_Crop_WIN_STEP;
            }
            break;
        }

        default:
        {
            break;
        }
    }

    UxZoom_SetPosition(
        &UIMenuWndPrint_Crop_ZoomWinCtrl,
        ZOOM_INTERNAL_RECT,
        &UIMenuWndPrint_Crop_WinRect);
    UxCtrl_SetDirty(pCtrl, TRUE);
    Ux_Redraw();
}
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_Crop_OnKeyRight_Function(VControl *pCtrl)
{
    switch(UIMenuWndPrint_Crop_Oper)
    {
        case UIMenuWndPrint_Crop_OPER_SIZE:
        {
            if(UIMenuWndPrint_Crop_WinRect.x2 <= (OSD_W-UIMenuWndPrint_Crop_WIN_STEP))
            {
                UIMenuWndPrint_Crop_WinRect.x2 += UIMenuWndPrint_Crop_WIN_STEP;
            }
            break;
        }

        case UIMenuWndPrint_Crop_OPER_POS:
        {
            if(UIMenuWndPrint_Crop_WinRect.x2 <= (OSD_W-UIMenuWndPrint_Crop_WIN_STEP))
            {
                UIMenuWndPrint_Crop_WinRect.x1 += UIMenuWndPrint_Crop_WIN_STEP;
                UIMenuWndPrint_Crop_WinRect.x2 += UIMenuWndPrint_Crop_WIN_STEP;
            }
            break;
        }

        default:
        {
            break;
        }
    }

    UxZoom_SetPosition(
        &UIMenuWndPrint_Crop_ZoomWinCtrl,
        ZOOM_INTERNAL_RECT,
        &UIMenuWndPrint_Crop_WinRect);
    UxCtrl_SetDirty(pCtrl, TRUE);
    Ux_Redraw();
}
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_Crop_OnKeyLeft_Function(VControl *pCtrl)
{
    switch(UIMenuWndPrint_Crop_Oper)
    {
        case UIMenuWndPrint_Crop_OPER_SIZE:
        {
            if(UIMenuWndPrint_Crop_WinRect.x2 > (UIMenuWndPrint_Crop_WinRect.x1+UIMenuWndPrint_Crop_WIN_STEP))
            {
                UIMenuWndPrint_Crop_WinRect.x2 -= UIMenuWndPrint_Crop_WIN_STEP;
            }
            break;
        }

        case UIMenuWndPrint_Crop_OPER_POS:
        {
            if(UIMenuWndPrint_Crop_WinRect.x1 >= UIMenuWndPrint_Crop_WIN_STEP)
            {
                UIMenuWndPrint_Crop_WinRect.x1 -= UIMenuWndPrint_Crop_WIN_STEP;
                UIMenuWndPrint_Crop_WinRect.x2 -= UIMenuWndPrint_Crop_WIN_STEP;
            }
            break;
        }

        default:
        {
            break;
        }
    }

    UxZoom_SetPosition(
        &UIMenuWndPrint_Crop_ZoomWinCtrl,
        ZOOM_INTERNAL_RECT,
        &UIMenuWndPrint_Crop_WinRect);
    UxCtrl_SetDirty(pCtrl, TRUE);
    Ux_Redraw();
}
//#NT#2011/06/14#Chris Chung -end
//---------------------UIMenuWndPrint_Crop Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_Crop)
//ZoomWin - begin
CTRL_LIST_ITEM(UIMenuWndPrint_Crop_ZoomWin)
//ZoomWin - end
CTRL_LIST_ITEM(UIMenuWndPrint_Crop_Title_Text_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_Crop_End_Dir_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_Crop Event---------------------------
INT32 UIMenuWndPrint_Crop_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Crop_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Crop_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Crop_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Crop_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Crop_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Crop_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Crop_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Crop_OnPrintDpsEvent(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Crop_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Crop_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Crop_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_Crop)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPrint_Crop_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPrint_Crop_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPrint_Crop_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPrint_Crop_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPrint_Crop_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPrint_Crop_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPrint_Crop_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPrint_Crop_OnKeyMenu)
EVENT_ITEM(NVTEVT_CB_PRINT_DPS_EVENT,UIMenuWndPrint_Crop_OnPrintDpsEvent)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIMenuWndPrint_Crop_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIMenuWndPrint_Crop_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPrint_Crop_OnKeyShutter2)
EVENT_END

//#NT#2011/06/14#Chris Chung -begin
//#NT#modify initial setting
INT32 UIMenuWndPrint_Crop_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);

    UIMenuWndPrint_Crop_Oper = UIMenuWndPrint_Crop_OPER_POS;
    UIMenuWndPrint_Crop_WinRect.x1 = UIMenuWndPrint_Crop_WIN_X1;
    UIMenuWndPrint_Crop_WinRect.y1 = UIMenuWndPrint_Crop_WIN_Y1;
    UIMenuWndPrint_Crop_WinRect.x2 = UIMenuWndPrint_Crop_WIN_X2;
    UIMenuWndPrint_Crop_WinRect.y2 = UIMenuWndPrint_Crop_WIN_Y2;

    UxZoom_SetPosition(
        &UIMenuWndPrint_Crop_ZoomWinCtrl,
        ZOOM_INTERNAL_RECT,
        &UIMenuWndPrint_Crop_WinRect);
    Ux_Redraw();
    return NVTEVT_CONSUME;
}
//#NT#2011/06/14#Chris Chung -end
INT32 UIMenuWndPrint_Crop_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Crop_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_LEFT == UIPRINT_KEYMAP_LEFT)
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_LEFT,paramNum,paramArray);
    UIMenuWndPrint_Crop_OnKeyLeft_Function(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Crop_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_RIGHT == UIPRINT_KEYMAP_RIGHT)
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_RIGHT,paramNum,paramArray);
    UIMenuWndPrint_Crop_OnKeyRight_Function(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Crop_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_UP == UIPRINT_KEYMAP_UP)
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_UP,paramNum,paramArray);
    UIMenuWndPrint_Crop_OnKeyUp_Function(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Crop_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_DOWN == UIPRINT_KEYMAP_DOWN)
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_DOWN,paramNum,paramArray);
    UIMenuWndPrint_Crop_OnKeyDown_Function(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Crop_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ENTER == UIPRINT_KEYMAP_ENTER)
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_ENTER,paramNum,paramArray);
    UIMenuWndPrint_Crop_OnKeyEnter_Function();
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Crop_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_MENU == UIPRINT_KEYMAP_MENU)
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_MENU,paramNum,paramArray);
    UIMenuWndPrint_Crop_OnKeyMenu_Function();
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Crop_OnPrintDpsEvent(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum > 0)
    {
        switch(paramArray[0])
        {
            case DPS_EVENT_CAPABILITY_CHANGED:
            {
                Ux_CloseWindow(&UIMenuWndPrintCtrl, 1, paramArray[0]);
                break;
            }

            default:
            {
                UIPrint_ShowNotification(
                    UIMenuWndPrint_Confirm_STATE_NON_PRINTING,
                    paramArray[0]);
                break;
            }
        }
    }
    Ux_Redraw();
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Crop_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ZOOMOUT == UIPRINT_KEYMAP_DOWN)
    UIMenuWndPrint_Crop_OnKeyDown_Function(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Crop_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ZOOMIN == UIPRINT_KEYMAP_UP)
    UIMenuWndPrint_Crop_OnKeyUp_Function(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Crop_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_SHUTTER2 == UIPRINT_KEYMAP_ENTER)
    UIMenuWndPrint_Crop_OnKeyEnter_Function();
    #endif
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPrint_Crop_Title_Text_Status Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Crop_Title_Text_Status)
EVENT_END

//---------------------UIMenuWndPrint_Crop_End_Dir_Menu_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_Crop_End_Dir_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_Crop_End_Dir_Menu_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Crop_End_Dir_Menu_Panel)
EVENT_END
//ZoomWin - begin
//----------------------ZoomWin Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Crop_ZoomWin)
EVENT_END
//ZoomWin - end

