//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPrint_ConfirmRes.c"
#include "UIMenuWndPrint_Confirm.h"
//-------------------------------------------------------------------------------------------------
#include "UIPrintObj.h"
#include "UIFlow.h"
#include "UIMenuWndPrint_SelectImages.h"
#include "UIMenuWndPrint_PrintAll.h"
#include "UIMenuWndPrint_PrintProgress.h"
#include "UIMenuWndPrint_PrintDPOF.h"
#include "EXTERNS.h"
//-------------------------------------------------------------------------------------------------
static UIMenuWndPrint_Confirm_STATE_ENUM UIMenuWndPrintConfirmState;
static BOOL UIMenuWndPrintConfirmCheck = FALSE;
static DPS_EVENT_ID UIMenuWndPrintConfirmCurrDpsEvent = DPS_EVENT_NONE;
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_Confirm_Confirm_Menu_Confirm(VControl *pCtrl)
{
    switch(UIMenuWndPrintConfirmState)
    {
        case UIMenuWndPrint_Confirm_STATE_CONFIRM_NORMAL:
        {
            switch(UxMenu_GetData(pCtrl,MNU_CURITM))
            {
                case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK:
                {
                    Ux_CloseWindow(&UIMenuWndPrint_SelectImagesCtrl,0);
                    Ux_SendEvent(&UIPrintObjCtrl,NVTEVT_PRINT_START_PRINT,0);
                    break;
                }

                case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL:
                {
                    Ux_CloseWindow(&UIMenuWndPrint_ConfirmCtrl,0);
                    break;
                }

                default:
                {
                    break;
                }
            }
            break;
        }

        case UIMenuWndPrint_Confirm_STATE_CONFIRM_ALL:
        {
            switch(UxMenu_GetData(pCtrl,MNU_CURITM))
            {
                case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK:
                {
                    Ux_CloseWindow(&UIMenuWndPrint_PrintAllCtrl,0);
                    Ux_SendEvent(&UIPrintObjCtrl,NVTEVT_PRINT_START_ALL,0);
                    break;
                }

                case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL:
                {
                    Ux_CloseWindow(&UIMenuWndPrint_ConfirmCtrl,0);
                    break;
                }

                default:
                {
                    break;
                }
            }
            break;
        }

        case UIMenuWndPrint_Confirm_STATE_CONFIRM_INDEX:
        {
            Ux_CloseWindow(&UIMenuWndPrint_ConfirmCtrl,0);
            switch(UxMenu_GetData(pCtrl,MNU_CURITM))
            {
                case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK:
                {
                    Ux_SendEvent(&UIPrintObjCtrl,NVTEVT_PRINT_START_INDEX,0);
                    break;
                }

                case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL:
                {
                    break;
                }

                default:
                {
                    break;
                }
            }
            break;
        }

        case UIMenuWndPrint_Confirm_STATE_CONFIRM_DPOF:
        {
            switch(UxMenu_GetData(pCtrl,MNU_CURITM))
            {
                case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK:
                {
                    Ux_CloseWindow(&UIMenuWndPrint_PrintDPOFCtrl,0);
                    Ux_SendEvent(&UIPrintObjCtrl,NVTEVT_PRINT_START_DPOF,0);
                    break;
                }

                case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL:
                {
                    Ux_CloseWindow(&UIMenuWndPrint_ConfirmCtrl,0);
                    break;
                }

                default:
                {
                    break;
                }
            }
            break;
        }

        case UIMenuWndPrint_Confirm_STATE_CONFIRM_DPOF_CONTINUE:
        {
            switch(UxMenu_GetData(pCtrl,MNU_CURITM))
            {
                case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK:
                {
                    Ux_CloseWindow(&UIMenuWndPrint_PrintDPOFCtrl,0);
                    Ux_SendEvent(&UIPrintObjCtrl,NVTEVT_PRINT_CONTINUE_DPOF,0);
                    break;
                }

                case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL:
                {
                    Ux_CloseWindow(&UIMenuWndPrint_ConfirmCtrl,0);
                    break;
                }

                default:
                {
                    break;
                }
            }
            break;
        }

        case UIMenuWndPrint_Confirm_STATE_CONFIRM_STOP:
        {
            Ux_CloseWindow(&UIMenuWndPrint_ConfirmCtrl,0);
            switch(UxMenu_GetData(pCtrl,MNU_CURITM))
            {
                case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK:
                {

                    Ux_SendEvent(&UIPrintObjCtrl,NVTEVT_PRINT_STOP_PRINT,0);
                    break;
                }

                case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL:
                {
                    break;
                }

                default:
                {
                    break;
                }
            }
            break;
        }

        case UIMenuWndPrint_Confirm_STATE_PRINTING:
        {
            switch(UIMenuWndPrintConfirmCurrDpsEvent)
            {
                case DPS_EVENT_DISCONNET_ENABLE:
                {
                    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
                    {
                        case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK:
                        {
                            Ux_CloseWindow(&UIMenuWndPrint_ConfirmCtrl,0);
                            break;
                        }

                        default:
                        {
                            break;
                        }
                    }
                    break;
                }

                case DPS_EVENT_START_JOB_FAIL:
                {
                    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
                    {
                        case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK:
                        {
                            Ux_CloseWindow(&UIMenuWndPrint_ConfirmCtrl,0);
                            break;
                        }

                        default:
                        {
                            break;
                        }
                    }
                    break;
                }

                case DPS_EVENT_PRINT_FINISH:
                {
                    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
                    {
                        case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK:
                        {
                            Ux_CloseWindow(&UIMenuWndPrint_PrintProgressCtrl, 0);
                            break;
                        }

                        default:
                        {
                            break;
                        }
                    }
                    break;
                }

                case DPS_EVENT_WARNING:
                case DPS_EVENT_WARNING_PAPER:
                case DPS_EVENT_WARNING_PAPER_EMPTY:
                case DPS_EVENT_WARNING_PAPER_LOAD:
                case DPS_EVENT_WARNING_PAPER_EJECT:
                case DPS_EVENT_WARNING_PAPER_MEDIA:
                case DPS_EVENT_WARNING_PAPER_JAM:
                case DPS_EVENT_WARNING_PAPER_NEARLY_EMPTY:
                case DPS_EVENT_WARNING_PAPER_NOT_FOUND:
                //Warning:Ink:23
                case DPS_EVENT_WARNING_INK:
                case DPS_EVENT_WARNING_INK_EMPTY:
                case DPS_EVENT_WARNING_INK_LOW:
                case DPS_EVENT_WARNING_INK_WASTE:
                //Warning:Hardware:27
                case DPS_EVENT_WARNING_HARDWARE:
                case DPS_EVENT_WARNING_HARDWARE_FATAL_ERROR:
                case DPS_EVENT_WARNING_HARDWARE_SERVICE_CALL:
                case DPS_EVENT_WARNING_HARDWARE_UNAVAILABLE:
                case DPS_EVENT_WARNING_HARDWARE_BUSY:
                case DPS_EVENT_WARNING_HARDWARE_LEVER:
                case DPS_EVENT_WARNING_HARDWARE_COVER_OPEN:
                case DPS_EVENT_WARNING_HARDWARE_MARKING_AGENT:
                case DPS_EVENT_WARNING_HARDWARE_INK_OPEN:
                case DPS_EVENT_WARNING_HARDWARE_NO_INK:
                //Warning:File:37
                case DPS_EVENT_WARNING_FILE:
                case DPS_EVENT_WARNING_FILE_PRINTINFO:
                case DPS_EVENT_WARNING_FILE_DECODE:
                {
                    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
                    {
                        case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK:
                        {
                            #if (UIPRINT_SUPPORT_ABORT_JOB|UIPRINT_SUPPORT_CONTINUE_JOB)
                            Ux_CloseWindow(&UIMenuWndPrint_ConfirmCtrl,0);
                            #else
                            Ux_CloseWindow(&UIMenuWndPrint_PrintProgressCtrl, 0);
                            #endif
                            break;
                        }

                        case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL:
                        {
                            Ux_SendEvent(&UIPrintObjCtrl,NVTEVT_PRINT_STOP_PRINT,0);
                            break;
                        }

                        case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CONTINUE:
                        {
                            Ux_SendEvent(&UIPrintObjCtrl,NVTEVT_PRINT_CONTINUE_PRINT,0);
                            break;
                        }

                        default:
                        {
                            break;
                        }
                    }
                    break;
                }

                //Fatal Error:Paper:40
                case DPS_EVENT_ERROR:
                case DPS_EVENT_ERROR_PAPER:
                case DPS_EVENT_ERROR_PAPER_EMPTY:
                case DPS_EVENT_ERROR_PAPER_LOAD:
                case DPS_EVENT_ERROR_PAPER_EJECT:
                case DPS_EVENT_ERROR_PAPER_MEDIA:
                case DPS_EVENT_ERROR_PAPER_JAM:
                case DPS_EVENT_ERROR_PAPER_NEARLY_EMPTY:
                case DPS_EVENT_ERROR_PAPER_NOT_FOUND:
                //Fatal Error:Ink:49
                case DPS_EVENT_ERROR_INK:
                case DPS_EVENT_ERROR_INK_EMPTY:
                case DPS_EVENT_ERROR_INK_LOW:
                case DPS_EVENT_ERROR_INK_WASTE:
                //Fatal Error:Hardware:53
                case DPS_EVENT_ERROR_HARDWARE:
                case DPS_EVENT_ERROR_HARDWARE_FATAL_ERROR:
                case DPS_EVENT_ERROR_HARDWARE_SERVICE_CALL:
                case DPS_EVENT_ERROR_HARDWARE_UNAVAILABLE:
                case DPS_EVENT_ERROR_HARDWARE_BUSY:
                case DPS_EVENT_ERROR_HARDWARE_LEVER:
                case DPS_EVENT_ERROR_HARDWARE_COVER_OPEN:
                case DPS_EVENT_ERROR_HARDWARE_MARKING_AGENT:
                case DPS_EVENT_ERROR_HARDWARE_INK_OPEN:
                case DPS_EVENT_ERROR_HARDWARE_NO_INK:
                //Fatal Error:File:63
                case DPS_EVENT_ERROR_FILE:
                case DPS_EVENT_ERROR_FILE_PRINTINFO:
                case DPS_EVENT_ERROR_FILE_DECODE:
                //Unknow Error status:66
                case DPS_EVENT_UNKNOWN_ERROR_STATUS:
                //XML syntax error:67
                case DPS_EVENT_XML_SYNTAX_ERROR:
                {
                    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
                    {
                        case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK:
                        {
                            #if (UIPRINT_SUPPORT_ABORT_JOB|UIPRINT_SUPPORT_CONTINUE_JOB)
                            Ux_CloseWindow(&UIMenuWndPrint_ConfirmCtrl,0);
                            #else
                            Ux_CloseWindow(&UIMenuWndPrint_PrintProgressCtrl, 0);
                            #endif
                            break;
                        }

                        case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL:
                        {
                            Ux_SendEvent(&UIPrintObjCtrl,NVTEVT_PRINT_STOP_PRINT,0);
                            break;
                        }

                        default:
                        {
                            break;
                        }
                    }
                    break;
                }

                default:
                {
                    break;
                }
            }
            break;
        }

        case UIMenuWndPrint_Confirm_STATE_NON_PRINTING:
        {
            switch(UIMenuWndPrintConfirmCurrDpsEvent)
            {
                case DPS_EVENT_DISCONNET_ENABLE:
                {
                    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
                    {
                        case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK:
                        {
                            Ux_CloseWindow(&UIMenuWndPrint_ConfirmCtrl,0);
                            break;
                        }

                        default:
                        {
                            break;
                        }
                    }
                    break;
                }

                case DPS_EVENT_PRINT_FINISH:
                {
                    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
                    {
                        case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK:
                        {
                            Ux_CloseWindow(&UIMenuWndPrint_ConfirmCtrl, 0);
                            break;
                        }

                        default:
                        {
                            break;
                        }
                    }
                    break;
                }

                case DPS_EVENT_WARNING:
                case DPS_EVENT_WARNING_PAPER:
                case DPS_EVENT_WARNING_PAPER_EMPTY:
                case DPS_EVENT_WARNING_PAPER_LOAD:
                case DPS_EVENT_WARNING_PAPER_EJECT:
                case DPS_EVENT_WARNING_PAPER_MEDIA:
                case DPS_EVENT_WARNING_PAPER_JAM:
                case DPS_EVENT_WARNING_PAPER_NEARLY_EMPTY:
                case DPS_EVENT_WARNING_PAPER_NOT_FOUND:
                //Warning:Ink:23
                case DPS_EVENT_WARNING_INK:
                case DPS_EVENT_WARNING_INK_EMPTY:
                case DPS_EVENT_WARNING_INK_LOW:
                case DPS_EVENT_WARNING_INK_WASTE:
                //Warning:Hardware:27
                case DPS_EVENT_WARNING_HARDWARE:
                case DPS_EVENT_WARNING_HARDWARE_FATAL_ERROR:
                case DPS_EVENT_WARNING_HARDWARE_SERVICE_CALL:
                case DPS_EVENT_WARNING_HARDWARE_UNAVAILABLE:
                case DPS_EVENT_WARNING_HARDWARE_BUSY:
                case DPS_EVENT_WARNING_HARDWARE_LEVER:
                case DPS_EVENT_WARNING_HARDWARE_COVER_OPEN:
                case DPS_EVENT_WARNING_HARDWARE_MARKING_AGENT:
                case DPS_EVENT_WARNING_HARDWARE_INK_OPEN:
                case DPS_EVENT_WARNING_HARDWARE_NO_INK:
                //Warning:File:37
                case DPS_EVENT_WARNING_FILE:
                case DPS_EVENT_WARNING_FILE_PRINTINFO:
                case DPS_EVENT_WARNING_FILE_DECODE:
                //Fatal Error:Paper:40
                case DPS_EVENT_ERROR:
                case DPS_EVENT_ERROR_PAPER:
                case DPS_EVENT_ERROR_PAPER_EMPTY:
                case DPS_EVENT_ERROR_PAPER_LOAD:
                case DPS_EVENT_ERROR_PAPER_EJECT:
                case DPS_EVENT_ERROR_PAPER_MEDIA:
                case DPS_EVENT_ERROR_PAPER_JAM:
                case DPS_EVENT_ERROR_PAPER_NEARLY_EMPTY:
                case DPS_EVENT_ERROR_PAPER_NOT_FOUND:
                //Fatal Error:Ink:49
                case DPS_EVENT_ERROR_INK:
                case DPS_EVENT_ERROR_INK_EMPTY:
                case DPS_EVENT_ERROR_INK_LOW:
                case DPS_EVENT_ERROR_INK_WASTE:
                //Fatal Error:Hardware:53
                case DPS_EVENT_ERROR_HARDWARE:
                case DPS_EVENT_ERROR_HARDWARE_FATAL_ERROR:
                case DPS_EVENT_ERROR_HARDWARE_SERVICE_CALL:
                case DPS_EVENT_ERROR_HARDWARE_UNAVAILABLE:
                case DPS_EVENT_ERROR_HARDWARE_BUSY:
                case DPS_EVENT_ERROR_HARDWARE_LEVER:
                case DPS_EVENT_ERROR_HARDWARE_COVER_OPEN:
                case DPS_EVENT_ERROR_HARDWARE_MARKING_AGENT:
                case DPS_EVENT_ERROR_HARDWARE_INK_OPEN:
                case DPS_EVENT_ERROR_HARDWARE_NO_INK:
                //Fatal Error:File:63
                case DPS_EVENT_ERROR_FILE:
                case DPS_EVENT_ERROR_FILE_PRINTINFO:
                case DPS_EVENT_ERROR_FILE_DECODE:
                //Unknow Error status:66
                case DPS_EVENT_UNKNOWN_ERROR_STATUS:
                //XML syntax error:67
                case DPS_EVENT_XML_SYNTAX_ERROR:
                {
                    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
                    {
                        case UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK:
                        {
                            Ux_CloseWindow(&UIMenuWndPrint_ConfirmCtrl,0);
                            break;
                        }

                        default:
                        {
                            break;
                        }
                    }
                    break;
                }

                default:
                {
                    break;
                }
            }
            break;
        }

        default:
        {
            break;
        }
    }

    UIMenuWndPrintConfirmCheck = TRUE;
    UIPrint_PostNextDpsEvent();
    Ux_Redraw();
}
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_Confirm_ErrorProcess(DPS_EVENT_ID EventId)
{
    switch(EventId)
    {
        case DPS_EVENT_WARNING:
        case DPS_EVENT_WARNING_PAPER:
        case DPS_EVENT_WARNING_PAPER_EMPTY:
        case DPS_EVENT_WARNING_PAPER_LOAD:
        case DPS_EVENT_WARNING_PAPER_EJECT:
        case DPS_EVENT_WARNING_PAPER_MEDIA:
        case DPS_EVENT_WARNING_PAPER_JAM:
        case DPS_EVENT_WARNING_PAPER_NEARLY_EMPTY:
        case DPS_EVENT_WARNING_PAPER_NOT_FOUND:
        //Warning:Ink:23
        case DPS_EVENT_WARNING_INK:
        case DPS_EVENT_WARNING_INK_EMPTY:
        case DPS_EVENT_WARNING_INK_LOW:
        case DPS_EVENT_WARNING_INK_WASTE:
        //Warning:Hardware:27
        case DPS_EVENT_WARNING_HARDWARE:
        case DPS_EVENT_WARNING_HARDWARE_FATAL_ERROR:
        case DPS_EVENT_WARNING_HARDWARE_SERVICE_CALL:
        case DPS_EVENT_WARNING_HARDWARE_UNAVAILABLE:
        case DPS_EVENT_WARNING_HARDWARE_BUSY:
        case DPS_EVENT_WARNING_HARDWARE_LEVER:
        case DPS_EVENT_WARNING_HARDWARE_COVER_OPEN:
        case DPS_EVENT_WARNING_HARDWARE_MARKING_AGENT:
        case DPS_EVENT_WARNING_HARDWARE_INK_OPEN:
        case DPS_EVENT_WARNING_HARDWARE_NO_INK:
        //Warning:File:37
        case DPS_EVENT_WARNING_FILE:
        case DPS_EVENT_WARNING_FILE_PRINTINFO:
        case DPS_EVENT_WARNING_FILE_DECODE:
        {
            UxMenu_SetData(
                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                MNU_CURITM,
                UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK);

            switch(UIMenuWndPrintConfirmState)
            {
                case UIMenuWndPrint_Confirm_STATE_PRINTING:
                #if (UIPRINT_SUPPORT_ABORT_JOB|UIPRINT_SUPPORT_CONTINUE_JOB)
                {
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK,
                        MNUITM_STATUS,
                        STATUS_ENABLE);
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL,
                        MNUITM_STATUS,
                        STATUS_ENABLE);
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CONTINUE,
                        MNUITM_STATUS,
                        STATUS_ENABLE);
                    break;
                }
                #elif UIPRINT_SUPPORT_ABORT_JOB
                {
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK,
                        MNUITM_STATUS,
                        STATUS_ENABLE);
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL,
                        MNUITM_STATUS,
                        STATUS_ENABLE);
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CONTINUE,
                        MNUITM_STATUS,
                        STATUS_DISABLE);
                    break;
                }
                #elif UIPRINT_SUPPORT_CONTINUE_JOB
                {
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK,
                        MNUITM_STATUS,
                        STATUS_ENABLE);
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL,
                        MNUITM_STATUS,
                        STATUS_DISABLE);
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CONTINUE,
                        MNUITM_STATUS,
                        STATUS_ENABLE);
                    break;
                }
                #endif

                case UIMenuWndPrint_Confirm_STATE_NON_PRINTING:
                {
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK,
                        MNUITM_STATUS,
                        STATUS_ENABLE);
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL,
                        MNUITM_STATUS,
                        STATUS_DISABLE);
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CONTINUE,
                        MNUITM_STATUS,
                        STATUS_DISABLE);
                    break;
                }

                default:
                {
                    break;
                }
            }
            break;
        }
        //Fatal Error:Paper:40
        case DPS_EVENT_ERROR:
        case DPS_EVENT_ERROR_PAPER:
        case DPS_EVENT_ERROR_PAPER_EMPTY:
        case DPS_EVENT_ERROR_PAPER_LOAD:
        case DPS_EVENT_ERROR_PAPER_EJECT:
        case DPS_EVENT_ERROR_PAPER_MEDIA:
        case DPS_EVENT_ERROR_PAPER_JAM:
        case DPS_EVENT_ERROR_PAPER_NEARLY_EMPTY:
        case DPS_EVENT_ERROR_PAPER_NOT_FOUND:
        //Fatal Error:Ink:49
        case DPS_EVENT_ERROR_INK:
        case DPS_EVENT_ERROR_INK_EMPTY:
        case DPS_EVENT_ERROR_INK_LOW:
        case DPS_EVENT_ERROR_INK_WASTE:
        //Fatal Error:Hardware:53
        case DPS_EVENT_ERROR_HARDWARE:
        case DPS_EVENT_ERROR_HARDWARE_FATAL_ERROR:
        case DPS_EVENT_ERROR_HARDWARE_SERVICE_CALL:
        case DPS_EVENT_ERROR_HARDWARE_UNAVAILABLE:
        case DPS_EVENT_ERROR_HARDWARE_BUSY:
        case DPS_EVENT_ERROR_HARDWARE_LEVER:
        case DPS_EVENT_ERROR_HARDWARE_COVER_OPEN:
        case DPS_EVENT_ERROR_HARDWARE_MARKING_AGENT:
        case DPS_EVENT_ERROR_HARDWARE_INK_OPEN:
        case DPS_EVENT_ERROR_HARDWARE_NO_INK:
        //Fatal Error:File:63
        case DPS_EVENT_ERROR_FILE:
        case DPS_EVENT_ERROR_FILE_PRINTINFO:
        case DPS_EVENT_ERROR_FILE_DECODE:
        //Unknow Error status:66
        case DPS_EVENT_UNKNOWN_ERROR_STATUS:
        //XML syntax error:67
        case DPS_EVENT_XML_SYNTAX_ERROR:
        {
            UxMenu_SetData(
                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                MNU_CURITM,
                UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK);

            switch(UIMenuWndPrintConfirmState)
            {
                case UIMenuWndPrint_Confirm_STATE_PRINTING:
                #if UIPRINT_SUPPORT_ABORT_JOB
                {
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK,
                        MNUITM_STATUS,
                        STATUS_ENABLE);
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL,
                        MNUITM_STATUS,
                        STATUS_ENABLE);
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CONTINUE,
                        MNUITM_STATUS,
                        STATUS_DISABLE);
                    break;
                }
                #endif

                case UIMenuWndPrint_Confirm_STATE_NON_PRINTING:
                {
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK,
                        MNUITM_STATUS,
                        STATUS_ENABLE);
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL,
                        MNUITM_STATUS,
                        STATUS_DISABLE);
                    UxMenu_SetItemData(
                        &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                        UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CONTINUE,
                        MNUITM_STATUS,
                        STATUS_DISABLE);
                    break;
                }

                default:
                {
                    break;
                }
            }
            break;
        }

        default:
        {
            break;
        }
    }

    switch(EventId)
    {
        case DPS_EVENT_WARNING:
        case DPS_EVENT_ERROR:
        case DPS_EVENT_UNKNOWN_ERROR_STATUS:
        case DPS_EVENT_XML_SYNTAX_ERROR:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_PRINT_ERROR);
            break;
        }
        case DPS_EVENT_WARNING_PAPER:
        case DPS_EVENT_ERROR_PAPER:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_PAPER_ERROR);
            break;
        }
        case DPS_EVENT_WARNING_PAPER_EMPTY:
        case DPS_EVENT_ERROR_PAPER_EMPTY:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_PAPER_OUT);
            break;
        }
        case DPS_EVENT_WARNING_PAPER_LOAD:
        case DPS_EVENT_ERROR_PAPER_LOAD:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_PAPER_LOAD_ERROR);
            break;
        }
        case DPS_EVENT_WARNING_PAPER_EJECT:
        case DPS_EVENT_ERROR_PAPER_EJECT:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_PAPER_EJECT_ERROR);
            break;
        }
        case DPS_EVENT_WARNING_PAPER_MEDIA:
        case DPS_EVENT_ERROR_PAPER_MEDIA:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_PAPER_MEDIA_ERROR);
            break;
        }
        case DPS_EVENT_WARNING_PAPER_JAM:
        case DPS_EVENT_ERROR_PAPER_JAM:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_PAPER_JAMMED);
            break;
        }
        case DPS_EVENT_WARNING_PAPER_NEARLY_EMPTY:
        case DPS_EVENT_ERROR_PAPER_NEARLY_EMPTY:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_PAPER_NEAR_EMPTY);
            break;
        }
        case DPS_EVENT_WARNING_PAPER_NOT_FOUND:
        case DPS_EVENT_ERROR_PAPER_NOT_FOUND:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_PAPER_NOT_SUPPORT);
            break;
        }
        case DPS_EVENT_WARNING_INK:
        case DPS_EVENT_ERROR_INK:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_INK_ERROR);
            break;
        }
        case DPS_EVENT_WARNING_INK_EMPTY:
        case DPS_EVENT_ERROR_INK_EMPTY:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_INK_EMPTY);
            break;
        }
        case DPS_EVENT_WARNING_INK_LOW:
        case DPS_EVENT_ERROR_INK_LOW:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_INK_LOW);
            break;
        }
        case DPS_EVENT_WARNING_INK_WASTE:
        case DPS_EVENT_ERROR_INK_WASTE:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_INK_WASTE);
            break;
        }
        case DPS_EVENT_WARNING_HARDWARE:
        case DPS_EVENT_ERROR_HARDWARE:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_HW_ERROR);
            break;
        }
        case DPS_EVENT_WARNING_HARDWARE_FATAL_ERROR:
        case DPS_EVENT_ERROR_HARDWARE_FATAL_ERROR:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_HW_FATAL);
            break;
        }
        case DPS_EVENT_WARNING_HARDWARE_SERVICE_CALL:
        case DPS_EVENT_ERROR_HARDWARE_SERVICE_CALL:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_HW_SERVICE_CALL);
            break;
        }
        case DPS_EVENT_WARNING_HARDWARE_UNAVAILABLE:
        case DPS_EVENT_ERROR_HARDWARE_UNAVAILABLE:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_HW_UNAVAILABLE);
            break;
        }
        case DPS_EVENT_WARNING_HARDWARE_BUSY:
        case DPS_EVENT_ERROR_HARDWARE_BUSY:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_HW_BUSY);
            break;
        }
        case DPS_EVENT_WARNING_HARDWARE_LEVER:
        case DPS_EVENT_ERROR_HARDWARE_LEVER:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_HW_LEVER);
            break;
        }
        case DPS_EVENT_WARNING_HARDWARE_COVER_OPEN:
        case DPS_EVENT_ERROR_HARDWARE_COVER_OPEN:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_HW_COVER_OPEN);
            break;
        }
        case DPS_EVENT_WARNING_HARDWARE_MARKING_AGENT:
        case DPS_EVENT_ERROR_HARDWARE_MARKING_AGENT:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_HW_NO_MARKING_AGENT);
            break;
        }
        case DPS_EVENT_WARNING_HARDWARE_INK_OPEN:
        case DPS_EVENT_ERROR_HARDWARE_INK_OPEN:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_HW_COVER_OPEN);
            break;
        }
        case DPS_EVENT_WARNING_HARDWARE_NO_INK:
        case DPS_EVENT_ERROR_HARDWARE_NO_INK:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_HW_NO_INK_CARTRIDGE);
            break;
        }
        case DPS_EVENT_WARNING_FILE:
        case DPS_EVENT_ERROR_FILE:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_FILE_ERROR);
            break;
        }
        case DPS_EVENT_WARNING_FILE_PRINTINFO:
        case DPS_EVENT_ERROR_FILE_PRINTINFO:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_FILE_PRINT_INFO);
            break;
        }
        case DPS_EVENT_WARNING_FILE_DECODE:
        case DPS_EVENT_ERROR_FILE_DECODE:
        {
            UxState_SetData(
                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                STATE_CURITEM,
                UIMenuWndPrint_Confirm_Text_Status_STRID_FILE_DECODE_ERROR);
            break;
        }

        default:
        {
            break;
        }
    }

    Ux_Redraw();
}
//---------------------UIMenuWndPrint_Confirm Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_Confirm)
CTRL_LIST_ITEM(UIMenuWndPrint_Confirm_Content_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_Confirm_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_Confirm_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_Confirm_Confirm_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_Confirm_Text_Status)
CTRL_LIST_END

//----------------------UIMenuWndPrint_Confirm Event---------------------------
INT32 UIMenuWndPrint_Confirm_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Confirm_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Confirm_OnPrintDpsEvent(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_Confirm)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPrint_Confirm_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPrint_Confirm_OnClose)
EVENT_ITEM(NVTEVT_CB_PRINT_DPS_EVENT,UIMenuWndPrint_Confirm_OnPrintDpsEvent)
EVENT_END

INT32 UIMenuWndPrint_Confirm_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);

    if(paramNum > 0)
    {
        UIMenuWndPrintConfirmState = paramArray[0];
        UIMenuWndPrintConfirmCheck = FALSE;

        switch(UIMenuWndPrintConfirmState)
        {
            case UIMenuWndPrint_Confirm_STATE_CONFIRM_NORMAL:
            case UIMenuWndPrint_Confirm_STATE_CONFIRM_ALL:
            case UIMenuWndPrint_Confirm_STATE_CONFIRM_INDEX:
            case UIMenuWndPrint_Confirm_STATE_CONFIRM_DPOF:
            case UIMenuWndPrint_Confirm_STATE_CONFIRM_DPOF_CONTINUE:
            {
                UxState_SetData(
                    &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                    STATE_CURITEM,
                    UIMenuWndPrint_Confirm_Text_Status_STRID_START_PRINTING);
                UxMenu_SetData(
                    &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                    MNU_CURITM,
                    UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK);

                UxMenu_SetItemData(
                    &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                    UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK,
                    MNUITM_STATUS,
                    STATUS_ENABLE);
                UxMenu_SetItemData(
                    &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                    UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL,
                    MNUITM_STATUS,
                    STATUS_ENABLE);
                UxMenu_SetItemData(
                    &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                    UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CONTINUE,
                    MNUITM_STATUS,
                    STATUS_DISABLE);
                break;
            }

            case UIMenuWndPrint_Confirm_STATE_CONFIRM_STOP:
            {
                UxState_SetData(
                    &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                    STATE_CURITEM,
                    UIMenuWndPrint_Confirm_Text_Status_STRID_CANCEL);
                UxMenu_SetData(
                    &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                    MNU_CURITM,
                    UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK);

                UxMenu_SetItemData(
                    &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                    UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK,
                    MNUITM_STATUS,
                    STATUS_ENABLE);
                UxMenu_SetItemData(
                    &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                    UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL,
                    MNUITM_STATUS,
                    STATUS_ENABLE);
                UxMenu_SetItemData(
                    &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                    UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CONTINUE,
                    MNUITM_STATUS,
                    STATUS_DISABLE);
                break;
            }

            case UIMenuWndPrint_Confirm_STATE_PRINTING:
            case UIMenuWndPrint_Confirm_STATE_NON_PRINTING:
            {
                if(paramNum > 1)
                {
                    UIMenuWndPrintConfirmCurrDpsEvent = paramArray[1];

                    switch(UIMenuWndPrintConfirmCurrDpsEvent)
                    {
                        case DPS_EVENT_DISCONNET_ENABLE:
                        {
                            UxState_SetData(
                                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                                STATE_CURITEM,
                                UIMenuWndPrint_Confirm_Text_Status_STRID_PRINTER_DISCONNECTABLE);
                            UxMenu_SetData(
                                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                                MNU_CURITM, UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK);

                            UxMenu_SetItemData(
                                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                                UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK,
                                MNUITM_STATUS,
                                STATUS_ENABLE);
                            UxMenu_SetItemData(
                                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                                UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL,
                                MNUITM_STATUS,
                                STATUS_DISABLE);
                            UxMenu_SetItemData(
                                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                                UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CONTINUE,
                                MNUITM_STATUS,
                                STATUS_DISABLE);
                            break;
                        }

                        case DPS_EVENT_START_JOB_FAIL:
                        {

                            UxState_SetData(
                                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                                STATE_CURITEM,
                                UIMenuWndPrint_Confirm_Text_Status_STRID_PRINT_ERROR);
                            UxMenu_SetData(
                                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                                MNU_CURITM, UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK);

                            UxMenu_SetItemData(
                                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                                UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK,
                                MNUITM_STATUS,
                                STATUS_ENABLE);
                            UxMenu_SetItemData(
                                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                                UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL,
                                MNUITM_STATUS,
                                STATUS_DISABLE);
                            UxMenu_SetItemData(
                                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                                UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CONTINUE,
                                MNUITM_STATUS,
                                STATUS_DISABLE);
                            break;
                        }

                        case DPS_EVENT_PRINT_FINISH:
                        {
                            UxState_SetData(
                                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                                STATE_CURITEM,
                                UIMenuWndPrint_Confirm_Text_Status_STRID_PRINT_FINISHED);
                            UxMenu_SetData(
                                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                                MNU_CURITM, UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK);

                            UxMenu_SetItemData(
                                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                                UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK,
                                MNUITM_STATUS,
                                STATUS_ENABLE);
                            UxMenu_SetItemData(
                                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                                UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL,
                                MNUITM_STATUS,
                                STATUS_DISABLE);
                            UxMenu_SetItemData(
                                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                                UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CONTINUE,
                                MNUITM_STATUS,
                                STATUS_DISABLE);
                            break;
                        }

                        default:
                        {
                            break;
                        }
                    }

                    UIMenuWndPrint_Confirm_ErrorProcess(UIMenuWndPrintConfirmCurrDpsEvent);
                }
                break;
            }

            default:
            {
                break;
            }
        }
    }
    Ux_Redraw();
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Confirm_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Confirm_OnPrintDpsEvent(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum > 0)
    {
        if(UIMenuWndPrintConfirmCheck)
        {
            UIMenuWndPrintConfirmCheck = FALSE;
            UIMenuWndPrintConfirmCurrDpsEvent = paramArray[0];

            switch(UIMenuWndPrintConfirmCurrDpsEvent)
            {
                case DPS_EVENT_END:
                {
                    Ux_CloseWindow(&UIMenuWndPrintCtrl, 1, DPS_EVENT_END);
                    UxState_SetData(
                        &UIFlowWndPrint_PicBridge_Text_StatusCtrl,
                        STATE_CURITEM,
                        UIFlowWndPrint_PicBridge_Text_Status_STRID_PLEASE_WAIT);
                    break;
                }

                default:
                {
                    switch(UIMenuWndPrintConfirmCurrDpsEvent)
                    {
                        case DPS_EVENT_PRINT_FINISH:
                        {
                            UxState_SetData(
                                &UIMenuWndPrint_Confirm_Text_StatusCtrl,
                                STATE_CURITEM,
                                UIMenuWndPrint_Confirm_Text_Status_STRID_PRINT_FINISHED);
                            UxMenu_SetData(
                                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                                MNU_CURITM,
                                UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK);

                            UxMenu_SetItemData(
                                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                                UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK,
                                MNUITM_STATUS,
                                STATUS_ENABLE);
                            UxMenu_SetItemData(
                                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                                UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL,
                                MNUITM_STATUS,
                                STATUS_DISABLE);
                            UxMenu_SetItemData(
                                &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                                UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CONTINUE,
                                MNUITM_STATUS,
                                STATUS_DISABLE);
                            break;
                        }

                        case DPS_EVENT_ABORT_JOB_OK:
                        {
                            UIMenuWndPrintConfirmCheck = TRUE;
                        }

                        case DPS_EVENT_ABORT_JOB_FAIL:
                        case DPS_EVENT_CONTINUE_JOB_OK:
                        {
                            Ux_CloseWindow(&UIMenuWndPrint_ConfirmCtrl,0);
                            break;
                        }

                        case DPS_EVENT_CONTINUE_JOB_FAIL:
                        {
                            Ux_CloseWindow(&UIMenuWndPrint_PrintProgressCtrl,0);
                            break;
                        }

                        default:
                        {
                            break;
                        }
                    }

                    UIMenuWndPrint_Confirm_ErrorProcess(UIMenuWndPrintConfirmCurrDpsEvent);
                    break;
                }
            }
        }
        else
        {
            UIPrint_AddDpsEvent(paramArray[0]);
            if(paramArray[0] == DPS_EVENT_PRINT_FINISH)
            {
                switch(UIMenuWndPrintConfirmCurrDpsEvent)
                {
                    case DPS_EVENT_WARNING:
                    case DPS_EVENT_WARNING_PAPER:
                    case DPS_EVENT_WARNING_PAPER_EMPTY:
                    case DPS_EVENT_WARNING_PAPER_LOAD:
                    case DPS_EVENT_WARNING_PAPER_EJECT:
                    case DPS_EVENT_WARNING_PAPER_MEDIA:
                    case DPS_EVENT_WARNING_PAPER_JAM:
                    case DPS_EVENT_WARNING_PAPER_NEARLY_EMPTY:
                    case DPS_EVENT_WARNING_PAPER_NOT_FOUND:
                    //Warning:Ink:23
                    case DPS_EVENT_WARNING_INK:
                    case DPS_EVENT_WARNING_INK_EMPTY:
                    case DPS_EVENT_WARNING_INK_LOW:
                    case DPS_EVENT_WARNING_INK_WASTE:
                    //Warning:Hardware:27
                    case DPS_EVENT_WARNING_HARDWARE:
                    case DPS_EVENT_WARNING_HARDWARE_FATAL_ERROR:
                    case DPS_EVENT_WARNING_HARDWARE_SERVICE_CALL:
                    case DPS_EVENT_WARNING_HARDWARE_UNAVAILABLE:
                    case DPS_EVENT_WARNING_HARDWARE_BUSY:
                    case DPS_EVENT_WARNING_HARDWARE_LEVER:
                    case DPS_EVENT_WARNING_HARDWARE_COVER_OPEN:
                    case DPS_EVENT_WARNING_HARDWARE_MARKING_AGENT:
                    case DPS_EVENT_WARNING_HARDWARE_INK_OPEN:
                    case DPS_EVENT_WARNING_HARDWARE_NO_INK:
                    //Warning:File:37
                    case DPS_EVENT_WARNING_FILE:
                    case DPS_EVENT_WARNING_FILE_PRINTINFO:
                    case DPS_EVENT_WARNING_FILE_DECODE:
                    //Fatal Error:Paper:40
                    case DPS_EVENT_ERROR:
                    case DPS_EVENT_ERROR_PAPER:
                    case DPS_EVENT_ERROR_PAPER_EMPTY:
                    case DPS_EVENT_ERROR_PAPER_LOAD:
                    case DPS_EVENT_ERROR_PAPER_EJECT:
                    case DPS_EVENT_ERROR_PAPER_MEDIA:
                    case DPS_EVENT_ERROR_PAPER_JAM:
                    case DPS_EVENT_ERROR_PAPER_NEARLY_EMPTY:
                    case DPS_EVENT_ERROR_PAPER_NOT_FOUND:
                    //Fatal Error:Ink:49
                    case DPS_EVENT_ERROR_INK:
                    case DPS_EVENT_ERROR_INK_EMPTY:
                    case DPS_EVENT_ERROR_INK_LOW:
                    case DPS_EVENT_ERROR_INK_WASTE:
                    //Fatal Error:Hardware:53
                    case DPS_EVENT_ERROR_HARDWARE:
                    case DPS_EVENT_ERROR_HARDWARE_FATAL_ERROR:
                    case DPS_EVENT_ERROR_HARDWARE_SERVICE_CALL:
                    case DPS_EVENT_ERROR_HARDWARE_UNAVAILABLE:
                    case DPS_EVENT_ERROR_HARDWARE_BUSY:
                    case DPS_EVENT_ERROR_HARDWARE_LEVER:
                    case DPS_EVENT_ERROR_HARDWARE_COVER_OPEN:
                    case DPS_EVENT_ERROR_HARDWARE_MARKING_AGENT:
                    case DPS_EVENT_ERROR_HARDWARE_INK_OPEN:
                    case DPS_EVENT_ERROR_HARDWARE_NO_INK:
                    //Fatal Error:File:63
                    case DPS_EVENT_ERROR_FILE:
                    case DPS_EVENT_ERROR_FILE_PRINTINFO:
                    case DPS_EVENT_ERROR_FILE_DECODE:
                    //Unknow Error status:66
                    case DPS_EVENT_UNKNOWN_ERROR_STATUS:
                    //XML syntax error:67
                    case DPS_EVENT_XML_SYNTAX_ERROR:
                    {
                        UxMenu_SetData(
                            &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                            MNU_CURITM,
                            UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK);

                        UxMenu_SetItemData(
                            &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                            UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK,
                            MNUITM_STATUS,
                            STATUS_ENABLE);
                        UxMenu_SetItemData(
                            &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                            UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL,
                            MNUITM_STATUS,
                            STATUS_DISABLE);
                        UxMenu_SetItemData(
                            &UIMenuWndPrint_Confirm_Confirm_MenuCtrl,
                            UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CONTINUE,
                            MNUITM_STATUS,
                            STATUS_DISABLE);
                        break;
                    }

                    default:
                    {
                        break;
                    }
                }
            }
        }
    }
    UxCtrl_SetDirty(pCtrl, TRUE);
    Ux_Redraw();
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPrint_Confirm_Content_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_Confirm_Content_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_Confirm_Content_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Confirm_Content_Panel)
EVENT_END

//---------------------UIMenuWndPrint_Confirm_Title_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_Confirm_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_Confirm_Title_Text_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_Confirm_Title_Icon_Status)
CTRL_LIST_END

//----------------------UIMenuWndPrint_Confirm_Title_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Confirm_Title_Panel)
EVENT_END

//----------------------UIMenuWndPrint_Confirm_Title_Text_Status Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Confirm_Title_Text_Status)
EVENT_END

//----------------------UIMenuWndPrint_Confirm_Title_Icon_Status Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Confirm_Title_Icon_Status)
EVENT_END

//---------------------UIMenuWndPrint_Confirm_End_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_Confirm_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_Confirm_End_Dir_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_Confirm_End_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Confirm_End_Panel)
EVENT_END

//---------------------UIMenuWndPrint_Confirm_End_Dir_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_Confirm_End_Dir_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_Confirm_End_Dir_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Confirm_End_Dir_Panel)
EVENT_END

//----------------------UIMenuWndPrint_Confirm_Confirm_Menu Event---------------------------
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_Confirm_Confirm_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_UP == UIPRINT_KEYMAP_UP)
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_DOWN == UIPRINT_KEYMAP_DOWN)
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_RIGHT == UIPRINT_KEYMAP_RIGHT)
    UIMenuWndPrint_Confirm_Confirm_Menu_Confirm(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ENTER == UIPRINT_KEYMAP_ENTER)
    UIMenuWndPrint_Confirm_Confirm_Menu_Confirm(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ZOOMOUT == UIPRINT_KEYMAP_DOWN)
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ZOOMIN == UIPRINT_KEYMAP_UP)

    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_SHUTTER2 == UIPRINT_KEYMAP_ENTER)
    UIMenuWndPrint_Confirm_Confirm_Menu_Confirm(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPrint_Confirm_Text_Status Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Confirm_Text_Status)
EVENT_END

