//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPRINT_CROP_H
#define UIMENUWNDPRINT_CROP_H

#include "UIFramework.h"
//-------------------------------------------------------------------------------------------------
//#NT#2011/06/14#Chris Chung -begin
//#NT#modify for initial location and move speed
#define UIMenuWndPrint_Crop_WIN_STEP    4
#define UIMenuWndPrint_Crop_WIN_X1      30
#define UIMenuWndPrint_Crop_WIN_Y1      30
#define UIMenuWndPrint_Crop_WIN_X2      290
#define UIMenuWndPrint_Crop_WIN_Y2      210
//#NT#2011/06/14#Chris Chung -end
//-------------------------------------------------------------------------------------------------
extern VControl UIMenuWndPrint_CropCtrl;

extern VControl UIMenuWndPrint_Crop_Title_Text_StatusCtrl;

typedef enum
{
UIMenuWndPrint_Crop_Title_Text_Status_STRID_CROP,
UIMenuWndPrint_Crop_Title_Text_Status_MAX
}UIMenuWndPrint_Crop_Title_Text_Status_Setting;
extern VControl UIMenuWndPrint_Crop_End_Dir_Menu_PanelCtrl;
//-------------------------------------------------------------------------------------------------
typedef enum
{
    UIMenuWndPrint_Crop_OPER_NONE,
    UIMenuWndPrint_Crop_OPER_SIZE,
    UIMenuWndPrint_Crop_OPER_POS
}UIMenuWndPrint_Crop_OPER_ENUM;
//-------------------------------------------------------------------------------------------------
#endif
