//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPrint_SelectImagesRes.c"
#include "UIMenuWndPrint_SelectImages.h"
//-------------------------------------------------------------------------------------------------
#include "UIPrintObj.h"
#include "UIFlow.h"

//-------------------------------------------------------------------------------------------------
extern int sprintf(char * /*s*/, const char * /*format*/, ...);
static UINT8 UIMenuWndPrint_SelectImages_String_Images[10];
static UINT8 UIMenuWndPrint_SelectImages_String_Copy[10];
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_SelectImages_Menu_Menu_UpdateImagesAndCopy(void)
{
    sprintf((char*)UIMenuWndPrint_SelectImages_String_Images,"%03d-%04d",UIPrint_Playback_GetDirId(),UIPrint_Playback_GetFileId());
    UxState_SetItemData(&UIMenuWndPrint_SelectImages_Images_StatusCtrl,0,STATE_ITEM_STRID,Txt_Pointer(UIMenuWndPrint_SelectImages_String_Images));
    sprintf((char*)UIMenuWndPrint_SelectImages_String_Copy,"%d/%d",UIPrint_Image_GetCopy(),UIPrint_Image_GetPrintCopy());
    UxState_SetItemData(&UIMenuWndPrint_SelectImages_Copy_StatusCtrl,0,STATE_ITEM_STRID,Txt_Pointer(UIMenuWndPrint_SelectImages_String_Copy));

    if( UIPrintDpsCapa.croppings & DPS_CAP_CROPPINGS_ON &&
        UIPrint_Image_GetCopy() > 0)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_SelectImages_Menu_MenuCtrl,
            UIMenuWndPrint_SelectImages_Menu_Menu_STRID_CROP,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }
    else
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_SelectImages_Menu_MenuCtrl,
            UIMenuWndPrint_SelectImages_Menu_Menu_STRID_CROP,
            MNUITM_STATUS,
            STATUS_DISABLE);
    }

    if(UIPrint_Image_GetPrintCopy() > 0)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_SelectImages_Menu_MenuCtrl,
            UIMenuWndPrint_SelectImages_Menu_Menu_STRID_PRINT_SETTING,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }
    else
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_SelectImages_Menu_MenuCtrl,
            UIMenuWndPrint_SelectImages_Menu_Menu_STRID_PRINT_SETTING,
            MNUITM_STATUS,
            STATUS_DISABLE);
    }
}
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyUpAndDown(VControl *pCtrl)
{
    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
    {
        case UIMenuWndPrint_SelectImages_Menu_Menu_STRID_IMAGES:
        case UIMenuWndPrint_SelectImages_Menu_Menu_STRID_COPY:
        {
            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_End_Dir_Menu_PanelCtrl, TRUE);
            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_End_Dir2_Menu_PanelCtrl, FALSE);

            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_Images_StatusCtrl, TRUE);
            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_Copy_StatusCtrl, TRUE);
            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_Dir_Left_PanelCtrl, TRUE);
            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_Dir_Right_PanelCtrl, TRUE);
            break;
        }

        case UIMenuWndPrint_SelectImages_Menu_Menu_STRID_CROP:
        case UIMenuWndPrint_SelectImages_Menu_Menu_STRID_PRINT_SETTING:
        {
            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_End_Dir_Menu_PanelCtrl, FALSE);
            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_End_Dir2_Menu_PanelCtrl, TRUE);

            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_Images_StatusCtrl, TRUE);
            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_Copy_StatusCtrl, TRUE);
            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_Dir_Left_PanelCtrl, TRUE);
            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_Dir_Right_PanelCtrl, TRUE);
            break;
        }

        case UIMenuWndPrint_SelectImages_Menu_Menu_STRID_RETURN:
        {
            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_End_Dir_Menu_PanelCtrl, FALSE);
            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_End_Dir2_Menu_PanelCtrl, TRUE);

            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_Images_StatusCtrl, FALSE);
            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_Copy_StatusCtrl, FALSE);
            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_Dir_Left_PanelCtrl, FALSE);
            UxCtrl_SetShow(&UIMenuWndPrint_SelectImages_Dir_Right_PanelCtrl, FALSE);
            break;
        }

        default:
        {
            break;
        }
    }
}
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_SelectImages_Menu_Menu_Select(VControl *pCtrl, BOOL IsRight)
{
    UINT32  TempCopyAmount;

    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
    {
        case UIMenuWndPrint_SelectImages_Menu_Menu_STRID_IMAGES:
        {
            if(IsRight)
            {
                Ux_SendEvent(&UIPrintObjCtrl,NVTEVT_PLAYNEXT,0);
            }
            else
            {
                Ux_SendEvent(&UIPrintObjCtrl,NVTEVT_PLAYPREV,0);
            }
            UIMenuWndPrint_SelectImages_Menu_Menu_UpdateImagesAndCopy();

            if( UIPrint_Image_GetCopy() == 0 &&
                UIPrint_Image_CheckArrayFull())
            {
                UxMenu_SetItemData(
                    &UIMenuWndPrint_SelectImages_Menu_MenuCtrl,
                    UIMenuWndPrint_SelectImages_Menu_Menu_STRID_COPY,
                    MNUITM_STATUS,
                    STATUS_DISABLE);
            }
            else
            {
                UxMenu_SetItemData(
                    &UIMenuWndPrint_SelectImages_Menu_MenuCtrl,
                    UIMenuWndPrint_SelectImages_Menu_Menu_STRID_COPY,
                    MNUITM_STATUS,
                    STATUS_ENABLE);
            }
            break;
        }

        case UIMenuWndPrint_SelectImages_Menu_Menu_STRID_COPY:
        {
            TempCopyAmount = UIPrint_Image_GetCopy();
            if(IsRight)
            {
                TempCopyAmount++;
            }
            else
            {
                if(TempCopyAmount>0)
                {
                    TempCopyAmount--;
                }
            }
            UIPrint_Image_SetCopy(TempCopyAmount);
            UIMenuWndPrint_SelectImages_Menu_Menu_UpdateImagesAndCopy();
            break;
        }

        default:
        {
            break;
        }
    }

    Ux_Redraw();
}
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_SelectImages_Menu_Menu_Confirm(VControl *pCtrl)
{
    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
    {
        case UIMenuWndPrint_SelectImages_Menu_Menu_STRID_CROP:
        {
            Ux_OpenWindow(&UIMenuWndPrint_CropCtrl, 0);
            break;
        }

        case UIMenuWndPrint_SelectImages_Menu_Menu_STRID_PRINT_SETTING:
        {
            Ux_OpenWindow(&UIMenuWndPrint_PrintSettingCtrl, 0);
            break;
        }

        case UIMenuWndPrint_SelectImages_Menu_Menu_STRID_RETURN:
        {
            Ux_CloseWindow(&UIMenuWndPrint_SelectImagesCtrl, 0);
            break;
        }

        default:
        {
            break;
        }
    }

    Ux_Redraw();
}
//---------------------UIMenuWndPrint_SelectImages Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_SelectImages)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Content_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Menu_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Images_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Copy_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Dir_Left_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Dir_Right_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_SelectImages Event---------------------------
INT32 UIMenuWndPrint_SelectImages_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_OnPrintDpsEvent(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_OnKeyMenu(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_SelectImages)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPrint_SelectImages_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPrint_SelectImages_OnClose)
EVENT_ITEM(NVTEVT_CB_PRINT_DPS_EVENT,UIMenuWndPrint_SelectImages_OnPrintDpsEvent)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPrint_SelectImages_OnKeyMenu)
EVENT_END

INT32 UIMenuWndPrint_SelectImages_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);

    UxMenu_SetData(&UIMenuWndPrint_SelectImages_Menu_MenuCtrl, MNU_CURITM, 0);
    UIPrint_Image_Init();
    Ux_SendEvent(
        &UIPrintObjCtrl,
        NVTEVT_PRINT_SET_JOB_CONFIG,
        2,
        DPS_CAPITEM_CROPPINGS,
        DPS_CAP_CROPPINGS_DEF);
    UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyUpAndDown(&UIMenuWndPrint_SelectImages_Menu_MenuCtrl);
    UIMenuWndPrint_SelectImages_Menu_Menu_UpdateImagesAndCopy();
    Ux_Redraw();
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_OnPrintDpsEvent(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum > 0)
    {
        switch(paramArray[0])
        {
            case DPS_EVENT_CAPABILITY_CHANGED:
            {
                Ux_CloseWindow(&UIMenuWndPrintCtrl, 1, paramArray[0]);
                break;
            }

            default:
            {
                UIPrint_ShowNotification(
                    UIMenuWndPrint_Confirm_STATE_NON_PRINTING,
                    paramArray[0]);
                break;
            }
        }
    }
    Ux_Redraw();
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndPrint_SelectImagesCtrl, 0);
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPrint_SelectImages_Content_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_SelectImages_Content_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_SelectImages_Content_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Content_Panel)
EVENT_END

//---------------------UIMenuWndPrint_SelectImages_Title_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_SelectImages_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Title_Text_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Title_Icon_Status)
CTRL_LIST_END

//----------------------UIMenuWndPrint_SelectImages_Title_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Title_Panel)
EVENT_END

//----------------------UIMenuWndPrint_SelectImages_Title_Text_Status Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Title_Text_Status)
EVENT_END

//----------------------UIMenuWndPrint_SelectImages_Title_Icon_Status Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Title_Icon_Status)
EVENT_END

//---------------------UIMenuWndPrint_SelectImages_End_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_SelectImages_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_End_Dir_Menu_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_End_Dir2_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_SelectImages_End_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_End_Panel)
EVENT_END

//---------------------UIMenuWndPrint_SelectImages_End_Dir_Menu_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_SelectImages_End_Dir_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_SelectImages_End_Dir_Menu_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_End_Dir_Menu_Panel)
EVENT_END

//---------------------UIMenuWndPrint_SelectImages_End_Dir2_Menu_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_SelectImages_End_Dir2_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_SelectImages_End_Dir2_Menu_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_End_Dir2_Menu_Panel)
EVENT_END

//----------------------UIMenuWndPrint_SelectImages_Menu_Menu Event---------------------------
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Menu_Menu)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_DOWN == UIPRINT_KEYMAP_DOWN)
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyUpAndDown(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_UP == UIPRINT_KEYMAP_UP)
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyUpAndDown(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_LEFT == UIPRINT_KEYMAP_LEFT)
    UIMenuWndPrint_SelectImages_Menu_Menu_Select(pCtrl, FALSE);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_RIGHT == UIPRINT_KEYMAP_RIGHT)
    UIMenuWndPrint_SelectImages_Menu_Menu_Select(pCtrl, TRUE);
    UIMenuWndPrint_SelectImages_Menu_Menu_Confirm(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ENTER == UIPRINT_KEYMAP_ENTER)
    UIMenuWndPrint_SelectImages_Menu_Menu_Confirm(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ZOOMOUT == UIPRINT_KEYMAP_DOWN)
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyUpAndDown(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ZOOMIN == UIPRINT_KEYMAP_UP)
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyUpAndDown(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_SHUTTER2 == UIPRINT_KEYMAP_ENTER)
    UIMenuWndPrint_SelectImages_Menu_Menu_Confirm(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPrint_SelectImages_Images_Status Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Images_Status)
EVENT_END

//----------------------UIMenuWndPrint_SelectImages_Copy_Status Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Copy_Status)
EVENT_END

//---------------------UIMenuWndPrint_SelectImages_Dir_Left_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_SelectImages_Dir_Left_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_SelectImages_Dir_Left_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Dir_Left_Panel)
EVENT_END

//---------------------UIMenuWndPrint_SelectImages_Dir_Right_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_SelectImages_Dir_Right_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_SelectImages_Dir_Right_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Dir_Right_Panel)
EVENT_END

