//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPrint_PrintAllRes.c"
#include "UIMenuWndPrint_PrintAll.h"
//-------------------------------------------------------------------------------------------------
#include "UIPrintObj.h"
#include "UIFlow.h"
//-------------------------------------------------------------------------------------------------
extern int sprintf(char * /*s*/, const char * /*format*/, ...);
static UINT8 UIMenuWndPrint_PrintAll_String_Copy[10];
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_PrintAll_Menu_Menu_UpdateImagesAndCopy(void)
{
    sprintf((char*)UIMenuWndPrint_PrintAll_String_Copy,"%d",UIPrint_Image_GetPrintAllCopy());
    UxState_SetItemData(&UIMenuWndPrint_PrintAll_Copy_StatusCtrl,0,STATE_ITEM_STRID,Txt_Pointer(UIMenuWndPrint_PrintAll_String_Copy));

    if(UIPrint_Image_GetPrintAllCopy() > 0)
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintAll_Menu_MenuCtrl,
            UIMenuWndPrint_PrintAll_Menu_Menu_STRID_PRINT,
            MNUITM_STATUS,
            STATUS_ENABLE);
    }
    else
    {
        UxMenu_SetItemData(
            &UIMenuWndPrint_PrintAll_Menu_MenuCtrl,
            UIMenuWndPrint_PrintAll_Menu_Menu_STRID_PRINT,
            MNUITM_STATUS,
            STATUS_DISABLE);
    }
}
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_PrintAll_Menu_Menu_Select(VControl *pCtrl, BOOL IsRight)
{
    UINT32  TempCopyAmount;

    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
    {
        case UIMenuWndPrint_PrintAll_Menu_Menu_STRID_COPY:
        {
            TempCopyAmount = UIPrint_Image_GetPrintAllCopy();
            if(IsRight)
            {
                TempCopyAmount++;
            }
            else
            {
                if(TempCopyAmount>0)
                {
                    TempCopyAmount--;
                }
            }
            UIPrint_Image_SetPrintAllCopy(TempCopyAmount);
            UIMenuWndPrint_PrintAll_Menu_Menu_UpdateImagesAndCopy();
            break;
        }

        default:
        {
            break;
        }
    }

    Ux_Redraw();
}
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_PrintAll_Menu_Menu_Confirm(VControl *pCtrl)
{
    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
    {
        case UIMenuWndPrint_PrintAll_Menu_Menu_STRID_PRINT:
        {
            if(UIPrint_Image_GetPrintAllCopy() > 0)
            {
                Ux_OpenWindow(&UIMenuWndPrint_ConfirmCtrl, 1,UIMenuWndPrint_Confirm_STATE_CONFIRM_ALL);
            }
            break;
        }

        case UIMenuWndPrint_PrintAll_Menu_Menu_STRID_RETURN:
        {
            Ux_CloseWindow(&UIMenuWndPrint_PrintAllCtrl, 0);
            break;
        }

        default:
        {
            break;
        }
    }

    Ux_Redraw();
}
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyUpAndDown(VControl *pCtrl)
{
    BOOL    TempShow;

    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
    {
        case UIMenuWndPrint_PrintAll_Menu_Menu_STRID_COPY:
        {
            UxCtrl_SetShow(&UIMenuWndPrint_PrintAll_End_Dir_Menu_PanelCtrl, TRUE);
            UxCtrl_SetShow(&UIMenuWndPrint_PrintAll_End_Dir2_Menu_PanelCtrl, FALSE);
            break;
        }

        case UIMenuWndPrint_PrintAll_Menu_Menu_STRID_PRINT:
        case UIMenuWndPrint_PrintAll_Menu_Menu_STRID_RETURN:
        {
            UxCtrl_SetShow(&UIMenuWndPrint_PrintAll_End_Dir_Menu_PanelCtrl, FALSE);
            UxCtrl_SetShow(&UIMenuWndPrint_PrintAll_End_Dir2_Menu_PanelCtrl, TRUE);
            TempShow = TRUE;
            break;
        }

        default:
        {
            break;
        }
    }
}
//---------------------UIMenuWndPrint_PrintAll Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintAll)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_Content_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_Menu_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_Copy_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_Dir_Left_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_Dir_Right_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintAll Event---------------------------
INT32 UIMenuWndPrint_PrintAll_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_OnPrintDpsEvent(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_OnKeyMenu(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_PrintAll)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPrint_PrintAll_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPrint_PrintAll_OnClose)
EVENT_ITEM(NVTEVT_CB_PRINT_DPS_EVENT,UIMenuWndPrint_PrintAll_OnPrintDpsEvent)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPrint_PrintAll_OnKeyMenu)
EVENT_END

INT32 UIMenuWndPrint_PrintAll_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);

    UxMenu_SetData(&UIMenuWndPrint_PrintAll_Menu_MenuCtrl, MNU_CURITM, 0);
    UIPrint_Image_Init();
    UIMenuWndPrint_PrintAll_Menu_Menu_UpdateImagesAndCopy();
    Ux_Redraw();
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_OnPrintDpsEvent(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum > 0)
    {
        switch(paramArray[0])
        {
            case DPS_EVENT_CAPABILITY_CHANGED:
            {
                Ux_CloseWindow(&UIMenuWndPrintCtrl, 1, paramArray[0]);
                break;
            }

            default:
            {
                UIPrint_ShowNotification(
                    UIMenuWndPrint_Confirm_STATE_NON_PRINTING,
                    paramArray[0]);
                break;
            }
        }
    }
    Ux_Redraw();
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPrint_PrintAll_Content_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintAll_Content_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintAll_Content_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_Content_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintAll_Title_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintAll_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_Title_Text_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_Title_Icon_Status)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintAll_Title_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_Title_Panel)
EVENT_END

//----------------------UIMenuWndPrint_PrintAll_Title_Text_Status Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_Title_Text_Status)
EVENT_END

//----------------------UIMenuWndPrint_PrintAll_Title_Icon_Status Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_Title_Icon_Status)
EVENT_END

//---------------------UIMenuWndPrint_PrintAll_End_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintAll_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_End_Dir_Menu_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_End_Dir2_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintAll_End_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_End_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintAll_End_Dir_Menu_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintAll_End_Dir_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintAll_End_Dir_Menu_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_End_Dir_Menu_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintAll_End_Dir2_Menu_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintAll_End_Dir2_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintAll_End_Dir2_Menu_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_End_Dir2_Menu_Panel)
EVENT_END

//----------------------UIMenuWndPrint_PrintAll_Menu_Menu Event---------------------------
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_PrintAll_Menu_Menu)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_DOWN == UIPRINT_KEYMAP_DOWN)
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyUpAndDown(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_UP == UIPRINT_KEYMAP_UP)
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyUpAndDown(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_LEFT == UIPRINT_KEYMAP_LEFT)
    UIMenuWndPrint_PrintAll_Menu_Menu_Select(pCtrl, FALSE);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_RIGHT == UIPRINT_KEYMAP_RIGHT)
    UIMenuWndPrint_PrintAll_Menu_Menu_Select(pCtrl, TRUE);
    UIMenuWndPrint_PrintAll_Menu_Menu_Confirm(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ENTER == UIPRINT_KEYMAP_ENTER)
    UIMenuWndPrint_PrintAll_Menu_Menu_Confirm(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ZOOMOUT == UIPRINT_KEYMAP_DOWN)
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyUpAndDown(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ZOOMIN == UIPRINT_KEYMAP_UP)
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyUpAndDown(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_SHUTTER2 == UIPRINT_KEYMAP_ENTER)
    UIMenuWndPrint_PrintAll_Menu_Menu_Confirm(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPrint_PrintAll_Copy_Status Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_Copy_Status)
EVENT_END

//---------------------UIMenuWndPrint_PrintAll_Dir_Left_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintAll_Dir_Left_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintAll_Dir_Left_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_Dir_Left_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintAll_Dir_Right_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintAll_Dir_Right_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintAll_Dir_Right_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_Dir_Right_Panel)
EVENT_END

