//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPrint_PrintSettingRes.c"
#include "UIMenuWndPrint_PrintSetting.h"
//-------------------------------------------------------------------------------------------------
#include "UIPrintObj.h"
#include "UIFlow.h"
#include "UIFlowWndPrint.h"
#include "UIMenuWndPrint.h"
#include "UIMenuWndPrint_Confirm.h"
#include "UIMenuWndPrint_SelectImages.h"
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyUpAndDown(VControl *pCtrl)
{
    BOOL    TempShow;
    UINT32  i, TempItemPage, TempCurPage;

    TempCurPage = UxMenu_GetData(pCtrl,MNU_CURITM)/UxMenu_GetData(pCtrl, MNU_PAGEITEM);

    for(i=0; i<UIMenuWndPrint_PrintSetting_Menu_Menu_MAX; i++)
    {
        TempItemPage = i/UxMenu_GetData(pCtrl, MNU_PAGEITEM);
        if(TempItemPage == TempCurPage)
        {
            TempShow = TRUE;
        }
        else
        {
            TempShow = FALSE;
        }

        if(i == UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_QUALITY)
        {
            UxCtrl_SetShow(&UIMenuWndPrint_PrintSetting_Quality_MenuCtrl, TempShow);
        }
        else
        if(i == UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_PAPER_TYPE)
        {
            UxCtrl_SetShow(&UIMenuWndPrint_PrintSetting_PaperType_MenuCtrl, TempShow);
        }
        else
        if(i == UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_PAPER_SIZE)
        {
            UxCtrl_SetShow(&UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl, TempShow);
        }
        else
        if(i == UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_DATE_PRINT)
        {
            UxCtrl_SetShow(&UIMenuWndPrint_PrintSetting_DatePrint_MenuCtrl, TempShow);
        }
        else
        if(i == UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_FILENAME_PRINT)
        {
            UxCtrl_SetShow(&UIMenuWndPrint_PrintSetting_FilenamePrint_MenuCtrl, TempShow);
        }
        else
        if(i == UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_IMAGE_OPTIMIZE)
        {
            UxCtrl_SetShow(&UIMenuWndPrint_PrintSetting_ImageOptimizes_MenuCtrl, TempShow);
        }
        else
        if(i == UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_LAYOUT)
        {
            UxCtrl_SetShow(&UIMenuWndPrint_PrintSetting_Layout_MenuCtrl, TempShow);
        }
        else
        if(i == UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_FIXED_SIZE)
        {
            UxCtrl_SetShow(&UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl, TempShow);
        }
    }

    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
    {
        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_QUALITY:
        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_PAPER_TYPE:
        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_PAPER_SIZE:
        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_DATE_PRINT:
        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_FILENAME_PRINT:
        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_IMAGE_OPTIMIZE:
        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_LAYOUT:
        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_FIXED_SIZE:
        {
            UxCtrl_SetShow(&UIMenuWndPrint_PrintSetting_End_Dir_Menu_PanelCtrl, TRUE);
            UxCtrl_SetShow(&UIMenuWndPrint_PrintSetting_End_Dir2_Menu_PanelCtrl, FALSE);
            UxCtrl_SetShow(&UIMenuWndPrint_PrintSetting_Dir_Left_PanelCtrl, TRUE);
            UxCtrl_SetShow(&UIMenuWndPrint_PrintSetting_Dir_Right_PanelCtrl, TRUE);
            break;
        }

        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_PRINT:
        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_RETURN:
        {
            UxCtrl_SetShow(&UIMenuWndPrint_PrintSetting_End_Dir_Menu_PanelCtrl, FALSE);
            UxCtrl_SetShow(&UIMenuWndPrint_PrintSetting_End_Dir2_Menu_PanelCtrl,TRUE);
            UxCtrl_SetShow(&UIMenuWndPrint_PrintSetting_Dir_Left_PanelCtrl, FALSE);
            UxCtrl_SetShow(&UIMenuWndPrint_PrintSetting_Dir_Right_PanelCtrl, FALSE);
            break;
        }

        default:
        {
            break;
        }
    }

    Ux_Redraw();
}
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_PrintSetting_Menu_Menu_Select(VControl *pCtrl, BOOL IsRight)
{
    UINT32  TempAction, TempItem = 0;
    BOOL    IsLayoutSelect = FALSE, IsFixSizeSelect = FALSE;

    if(IsRight)
    {
        TempAction = NVTEVT_NEXT_ITEM;
    }
    else
    {
        TempAction = NVTEVT_PREVIOUS_ITEM;
    }

    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
    {
        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_QUALITY:
        {
            Ux_SendEvent(&UIMenuWndPrint_PrintSetting_Quality_MenuCtrl,TempAction,0);
            switch(UxMenu_GetData(&UIMenuWndPrint_PrintSetting_Quality_MenuCtrl, MNU_CURITM))
            {
                case UIMenuWndPrint_PrintSetting_Quality_Menu_STRID_DEFAULT:
                {
                    TempItem = DPS_CAP_QUALITY_DEF;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_Quality_Menu_STRID_NORMAL:
                {
                    TempItem = DPS_CAP_QUALITY_NOR;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_Quality_Menu_STRID_ECONOMY:
                {
                    TempItem = DPS_CAP_QUALITY_DRA;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_Quality_Menu_STRID_FINE:
                {
                    TempItem = DPS_CAP_QUALITY_FIN;
                    break;
                }

                default:
                {
                    break;
                }
            }
            Ux_SendEvent(
                &UIPrintObjCtrl,
                NVTEVT_PRINT_SET_JOB_CONFIG,
                2,
                DPS_CAPITEM_QUALITY,
                TempItem);
            break;
        }

        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_PAPER_TYPE:
        {
            Ux_SendEvent(&UIMenuWndPrint_PrintSetting_PaperType_MenuCtrl,TempAction,0);
            switch(UxMenu_GetData(&UIMenuWndPrint_PrintSetting_PaperType_MenuCtrl, MNU_CURITM))
            {
                case UIMenuWndPrint_PrintSetting_PaperType_Menu_STRID_DEFAULT:
                {
                    TempItem = DPS_CAP_PAPERTYPE_DEF;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperType_Menu_STRID_PLAIN_PAPER:
                {
                    TempItem = DPS_CAP_PAPERTYPE_PLA;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperType_Menu_STRID_PHOTO_PAPER:
                {
                    TempItem = DPS_CAP_PAPERTYPE_PHO;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperType_Menu_STRID_FAST_PHOTO:
                {
                    TempItem = DPS_CAP_PAPERTYPE_FPHO;
                    break;
                }

                default:
                {
                    break;
                }
            }
            Ux_SendEvent(
                &UIPrintObjCtrl,
                NVTEVT_PRINT_SET_JOB_CONFIG,
                2,
                DPS_CAPITEM_PAPERTYPE,
                TempItem);
            break;
        }

        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_PAPER_SIZE:
        {
            Ux_SendEvent(&UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl,TempAction,0);
            switch(UxMenu_GetData(&UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl, MNU_CURITM))
            {
                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_DEFAULT:
                {
                    TempItem = DPS_CAP_PAPERSIZE_DEF;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_L:
                {
                    TempItem = DPS_CAP_PAPERSIZE_01L;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_2L:
                {
                    TempItem = DPS_CAP_PAPERSIZE_02L;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_POSTCARD:
                {
                    TempItem = DPS_CAP_PAPERSIZE_POS;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_CARD:
                {
                    TempItem = DPS_CAP_PAPERSIZE_CARD;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_100X150:
                {
                    TempItem = DPS_CAP_PAPERSIZE_150;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_4X6:
                {
                    TempItem = DPS_CAP_PAPERSIZE_4x6;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_8X10:
                {
                    TempItem = DPS_CAP_PAPERSIZE_8x10;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_LETTER:
                {
                    TempItem = DPS_CAP_PAPERSIZE_LET;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_11X17:
                {
                    TempItem = DPS_CAP_PAPERSIZE_11x17;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A0:
                {
                    TempItem = DPS_CAP_PAPERSIZE_A0;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A1:
                {
                    TempItem = DPS_CAP_PAPERSIZE_A1;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A2:
                {
                    TempItem = DPS_CAP_PAPERSIZE_A2;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A3:
                {
                    TempItem = DPS_CAP_PAPERSIZE_A3;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A4:
                {
                    TempItem = DPS_CAP_PAPERSIZE_A4;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A5:
                {
                    TempItem = DPS_CAP_PAPERSIZE_A5;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A6:
                {
                    TempItem = DPS_CAP_PAPERSIZE_A6;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A7:
                {
                    TempItem = DPS_CAP_PAPERSIZE_A7;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A8:
                {
                    TempItem = DPS_CAP_PAPERSIZE_A8;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A9:
                {
                    TempItem = DPS_CAP_PAPERSIZE_A9;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B0:
                {
                    TempItem = DPS_CAP_PAPERSIZE_B0;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B1:
                {
                    TempItem = DPS_CAP_PAPERSIZE_B1;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B2:
                {
                    TempItem = DPS_CAP_PAPERSIZE_B2;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B3:
                {
                    TempItem = DPS_CAP_PAPERSIZE_B3;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B4:
                {
                    TempItem = DPS_CAP_PAPERSIZE_B4;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B5:
                {
                    TempItem = DPS_CAP_PAPERSIZE_B5;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B6:
                {
                    TempItem = DPS_CAP_PAPERSIZE_B6;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B7:
                {
                    TempItem = DPS_CAP_PAPERSIZE_B7;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B8:
                {
                    TempItem = DPS_CAP_PAPERSIZE_B8;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_B9:
                {
                    TempItem = DPS_CAP_PAPERSIZE_B9;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_L_ROLLS:
                {
                    TempItem = DPS_CAP_PAPERSIZE_89RO;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_2L_ROLLS:
                {
                    TempItem = DPS_CAP_PAPERSIZE_127RO;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_4_ROLLS:
                {
                    TempItem = DPS_CAP_PAPERSIZE_100RO;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_PaperSize_Menu_STRID_A4_ROLLS:
                {
                    TempItem = DPS_CAP_PAPERSIZE_210RO;
                    break;
                }

                default:
                {
                    break;
                }
            }
            Ux_SendEvent(
                &UIPrintObjCtrl,
                NVTEVT_PRINT_SET_JOB_CONFIG,
                2,
                DPS_CAPITEM_PAPERSIZE,
                TempItem);
            UxMenu_SetData(&UIMenuWndPrint_PrintSetting_PaperType_MenuCtrl, MNU_CURITM, 0);
            UxMenu_SetData(&UIMenuWndPrint_PrintSetting_Layout_MenuCtrl, MNU_CURITM, 0);
            Ux_SendEvent(
                &UIPrintObjCtrl,
                NVTEVT_PRINT_GET_CAPABILITY_PAPERTYPE,
                1,
                TempItem);
            UIPrintDpsCapa.paperTypes = UIPrint_GetPaperType();
            Ux_SendEvent(
                &UIPrintObjCtrl,
                NVTEVT_PRINT_GET_CAPABILITY_LAYOUT,
                1,
                TempItem);
            UIPrintDpsCapa.layouts = UIPrint_Getlayout();
            UIFlowWndPrint_OnPrintDpsEvent_ResetCapa();
            break;
        }

        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_DATE_PRINT:
        {
            Ux_SendEvent(&UIMenuWndPrint_PrintSetting_DatePrint_MenuCtrl,TempAction,0);
            switch(UxMenu_GetData(&UIMenuWndPrint_PrintSetting_DatePrint_MenuCtrl, MNU_CURITM))
            {
                case UIMenuWndPrint_PrintSetting_DatePrint_Menu_STRID_DEFAULT:
                {
                    TempItem = DPS_CAP_DATEPRINT_DEF;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_DatePrint_Menu_STRID_ON:
                {
                    TempItem = DPS_CAP_DATEPRINT_ON;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_DatePrint_Menu_STRID_OFF:
                {
                    TempItem = DPS_CAP_DATEPRINT_OFF;
                    break;
                }

                default:
                {
                    break;
                }
            }
            Ux_SendEvent(
                &UIPrintObjCtrl,
                NVTEVT_PRINT_SET_JOB_CONFIG,
                2,
                DPS_CAPITEM_DATEPRINTS,
                TempItem);
            break;
        }

        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_FILENAME_PRINT:
        {
            Ux_SendEvent(&UIMenuWndPrint_PrintSetting_FilenamePrint_MenuCtrl,TempAction,0);
            switch(UxMenu_GetData(&UIMenuWndPrint_PrintSetting_FilenamePrint_MenuCtrl, MNU_CURITM))
            {
                case UIMenuWndPrint_PrintSetting_FilenamePrint_Menu_STRID_DEFAULT:
                {
                    TempItem = DPS_CAP_NAMEPRINT_DEF;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FilenamePrint_Menu_STRID_ON:
                {
                    TempItem = DPS_CAP_NAMEPRINT_ON;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FilenamePrint_Menu_STRID_OFF:
                {
                    TempItem = DPS_CAP_NAMEPRINT_OFF;
                    break;
                }

                default:
                {
                    break;
                }
            }
            Ux_SendEvent(
                &UIPrintObjCtrl,
                NVTEVT_PRINT_SET_JOB_CONFIG,
                2,
                DPS_CAPITEM_NAMEPRINTS,
                TempItem);
            break;
        }

        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_IMAGE_OPTIMIZE:
        {
            Ux_SendEvent(&UIMenuWndPrint_PrintSetting_ImageOptimizes_MenuCtrl,TempAction,0);
            switch(UxMenu_GetData(&UIMenuWndPrint_PrintSetting_ImageOptimizes_MenuCtrl, MNU_CURITM))
            {
                case UIMenuWndPrint_PrintSetting_ImageOptimizes_Menu_STRID_DEFAULT:
                {
                    TempItem = DPS_CAP_IMGOPT_DEF;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_ImageOptimizes_Menu_STRID_ON:
                {
                    TempItem = DPS_CAP_IMGOPT_ON;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_ImageOptimizes_Menu_STRID_OFF:
                {
                    TempItem = DPS_CAP_IMGOPT_OFF;
                    break;
                }

                default:
                {
                    break;
                }
            }
            Ux_SendEvent(
                &UIPrintObjCtrl,
                NVTEVT_PRINT_SET_JOB_CONFIG,
                2,
                DPS_CAPITEM_IMGOPT,
                TempItem);
            break;
        }

        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_LAYOUT:
        {
            Ux_SendEvent(&UIMenuWndPrint_PrintSetting_Layout_MenuCtrl,TempAction,0);
            switch(UxMenu_GetData(&UIMenuWndPrint_PrintSetting_Layout_MenuCtrl, MNU_CURITM))
            {
                case UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_DEFAULT:
                {
                    TempItem = DPS_CAP_LAYOUT_DEF;
                    IsLayoutSelect = FALSE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_1UP:
                {
                    TempItem = DPS_CAP_LAYOUT_01;
                    IsLayoutSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_2UP:
                {
                    TempItem = DPS_CAP_LAYOUT_02;
                    IsLayoutSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_3UP:
                {
                    TempItem = DPS_CAP_LAYOUT_03;
                    IsLayoutSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_4UP:
                {
                    TempItem = DPS_CAP_LAYOUT_04;
                    IsLayoutSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_5UP:
                {
                    TempItem = DPS_CAP_LAYOUT_05;
                    IsLayoutSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_6UP:
                {
                    TempItem = DPS_CAP_LAYOUT_06;
                    IsLayoutSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_7UP:
                {
                    TempItem = DPS_CAP_LAYOUT_07;
                    IsLayoutSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_8UP:
                {
                    TempItem = DPS_CAP_LAYOUT_08;
                    IsLayoutSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_9UP:
                {
                    TempItem = DPS_CAP_LAYOUT_09;
                    IsLayoutSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_10UP:
                {
                    TempItem = DPS_CAP_LAYOUT_10;
                    IsLayoutSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_250UP:
                {
                    TempItem = DPS_CAP_LAYOUT_250UP;
                    IsLayoutSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_INDEX:
                {
                    TempItem = DPS_CAP_LAYOUT_IDX;
                    IsLayoutSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_Layout_Menu_STRID_1UP_BORDERLESS:
                {
                    TempItem = DPS_CAP_LAYOUT_NOB;
                    IsLayoutSelect = TRUE;
                    break;
                }

                default:
                {
                    break;
                }
            }

            if(IsLayoutSelect)
            {
                UxMenu_SetItemData(
                    &UIMenuWndPrint_PrintSetting_Menu_MenuCtrl,
                    UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_FIXED_SIZE,
                    MNUITM_STATUS,
                    STATUS_DISABLE);
            }
            else
            {
                UxMenu_SetItemData(
                    &UIMenuWndPrint_PrintSetting_Menu_MenuCtrl,
                    UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_FIXED_SIZE,
                    MNUITM_STATUS,
                    STATUS_ENABLE);
            }

            Ux_SendEvent(
                &UIPrintObjCtrl,
                NVTEVT_PRINT_SET_JOB_CONFIG,
                2,
                DPS_CAPITEM_LAYOUTS,
                TempItem);
            break;
        }

        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_FIXED_SIZE:
        {
            Ux_SendEvent(&UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl,TempAction,0);
            switch(UxMenu_GetData(&UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl, MNU_CURITM))
            {
                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_DEFAULT:
                {
                    TempItem = DPS_CAP_FIXSIZE_DEF;
                    IsFixSizeSelect = FALSE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_25X325:
                {
                    TempItem = DPS_CAP_FIXSIZE_2x3;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_35X5:
                {
                    TempItem = DPS_CAP_FIXSIZE_3x5;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_4X6:
                {
                    TempItem = DPS_CAP_FIXSIZE_4x6;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_2L:
                {
                    TempItem = DPS_CAP_FIXSIZE_5x7;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_8X10:
                {
                    TempItem = DPS_CAP_FIXSIZE_8x10;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_254X178:
                {
                    TempItem = DPS_CAP_FIXSIZE_254;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_110X74:
                {
                    TempItem = DPS_CAP_FIXSIZE_110;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_89X55:
                {
                    TempItem = DPS_CAP_FIXSIZE_89;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_POSTCARD:
                {
                    TempItem = DPS_CAP_FIXSIZE_100;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_6X8:
                {
                    TempItem = DPS_CAP_FIXSIZE_6_8;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_7X10:
                {
                    TempItem = DPS_CAP_FIXSIZE_7_10;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_9X13:
                {
                    TempItem = DPS_CAP_FIXSIZE_9_13;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_100X150:
                {
                    TempItem = DPS_CAP_FIXSIZE_10_15;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_13X18:
                {
                    TempItem = DPS_CAP_FIXSIZE_13_18;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_15X21:
                {
                    TempItem = DPS_CAP_FIXSIZE_15_21;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_18X24:
                {
                    TempItem = DPS_CAP_FIXSIZE_18_24;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_A4:
                {
                    TempItem = DPS_CAP_FIXSIZE_A4;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                case UIMenuWndPrint_PrintSetting_FixedSize_Menu_STRID_LETTER:
                {
                    TempItem = DPS_CAP_FIXSIZE_LETTER;
                    IsFixSizeSelect = TRUE;
                    break;
                }

                default:
                {
                    break;
                }
            }

            if(IsFixSizeSelect)
            {
                UxMenu_SetItemData(
                    &UIMenuWndPrint_PrintSetting_Menu_MenuCtrl,
                    UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_LAYOUT,
                    MNUITM_STATUS,
                    STATUS_DISABLE);
            }
            else
            {
                UxMenu_SetItemData(
                    &UIMenuWndPrint_PrintSetting_Menu_MenuCtrl,
                    UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_LAYOUT,
                    MNUITM_STATUS,
                    STATUS_ENABLE);
            }

            Ux_SendEvent(
                &UIPrintObjCtrl,
                NVTEVT_PRINT_SET_JOB_CONFIG,
                2,
                DPS_CAPITEM_FIXSIZE,
                TempItem);
            break;
        }

        default:
        {
            break;
        }
    }

    Ux_Redraw();
}
//-------------------------------------------------------------------------------------------------
void UIMenuWndPrint_PrintSetting_Menu_Menu_Confirm(VControl *pCtrl)
{
    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
    {
        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_PRINT:
        {
            Ux_OpenWindow(&UIMenuWndPrint_ConfirmCtrl, 1,UIMenuWndPrint_Confirm_STATE_CONFIRM_NORMAL);
            break;
        }

        case UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_RETURN:
        {
            Ux_CloseWindow(&UIMenuWndPrint_PrintSettingCtrl, 0);
            break;
        }

        default:
        {
            break;
        }
    }

    Ux_Redraw();
}
//---------------------UIMenuWndPrint_PrintSetting Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintSetting)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Content_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Menu_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Quality_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_PaperType_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_PaperSize_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_DatePrint_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_FilenamePrint_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_ImageOptimizes_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Layout_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_FixedSize_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Dir_Left_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Dir_Right_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintSetting Event---------------------------
INT32 UIMenuWndPrint_PrintSetting_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_OnPrintDpsEvent(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_OnKeyMenu(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_PrintSetting)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPrint_PrintSetting_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPrint_PrintSetting_OnClose)
EVENT_ITEM(NVTEVT_CB_PRINT_DPS_EVENT,UIMenuWndPrint_PrintSetting_OnPrintDpsEvent)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPrint_PrintSetting_OnKeyMenu)
EVENT_END

INT32 UIMenuWndPrint_PrintSetting_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);

    UxMenu_SetData(&UIMenuWndPrint_PrintSetting_Menu_MenuCtrl, MNU_CURITM, 0);
    UxMenu_SetData(&UIMenuWndPrint_PrintSetting_Quality_MenuCtrl, MNU_CURITM, 0);
    UxMenu_SetData(&UIMenuWndPrint_PrintSetting_PaperType_MenuCtrl, MNU_CURITM, 0);
    UxMenu_SetData(&UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl, MNU_CURITM, 0);
    UxMenu_SetData(&UIMenuWndPrint_PrintSetting_DatePrint_MenuCtrl, MNU_CURITM, 0);
    UxMenu_SetData(&UIMenuWndPrint_PrintSetting_FilenamePrint_MenuCtrl, MNU_CURITM, 0);
    UxMenu_SetData(&UIMenuWndPrint_PrintSetting_ImageOptimizes_MenuCtrl, MNU_CURITM, 0);
    UxMenu_SetData(&UIMenuWndPrint_PrintSetting_Layout_MenuCtrl, MNU_CURITM, 0);
    UxMenu_SetData(&UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl, MNU_CURITM, 0);
    UxMenu_SetItemData(
        &UIMenuWndPrint_PrintSetting_Menu_MenuCtrl,
        UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_LAYOUT,
        MNUITM_STATUS,
        STATUS_ENABLE);
    UxMenu_SetItemData(
        &UIMenuWndPrint_PrintSetting_Menu_MenuCtrl,
        UIMenuWndPrint_PrintSetting_Menu_Menu_STRID_FIXED_SIZE,
        MNUITM_STATUS,
        STATUS_ENABLE);
    UIPrint_ResetCappability();

    UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyUpAndDown(&UIMenuWndPrint_PrintSetting_Menu_MenuCtrl);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_OnPrintDpsEvent(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum > 0)
    {
        switch(paramArray[0])
        {
            case DPS_EVENT_CAPABILITY_CHANGED:
            {
                Ux_CloseWindow(&UIMenuWndPrintCtrl, 1, paramArray[0]);
                break;
            }

            default:
            {
                UIPrint_ShowNotification(
                    UIMenuWndPrint_Confirm_STATE_NON_PRINTING,
                    paramArray[0]);
                break;
            }
        }
    }
    Ux_Redraw();
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndPrint_SelectImagesCtrl, 0);
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPrint_PrintSetting_Content_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintSetting_Content_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintSetting_Content_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Content_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintSetting_Title_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintSetting_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Title_Text_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Title_Icon_Status)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintSetting_Title_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Title_Panel)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_Title_Text_Status Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Title_Text_Status)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_Title_Icon_Status Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Title_Icon_Status)
EVENT_END

//---------------------UIMenuWndPrint_PrintSetting_End_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintSetting_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_End_Dir_Menu_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_End_Dir2_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintSetting_End_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_End_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintSetting_End_Dir_Menu_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintSetting_End_Dir_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintSetting_End_Dir_Menu_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_End_Dir_Menu_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintSetting_End_Dir2_Menu_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintSetting_End_Dir2_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintSetting_End_Dir2_Menu_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_End_Dir2_Menu_Panel)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_Menu_Menu Event---------------------------
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Menu_Menu)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_DOWN == UIPRINT_KEYMAP_DOWN)
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyUpAndDown(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_UP == UIPRINT_KEYMAP_UP)
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyUpAndDown(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_LEFT == UIPRINT_KEYMAP_LEFT)
    UIMenuWndPrint_PrintSetting_Menu_Menu_Select(pCtrl,FALSE);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_RIGHT == UIPRINT_KEYMAP_RIGHT)
    UIMenuWndPrint_PrintSetting_Menu_Menu_Select(pCtrl,TRUE);
    UIMenuWndPrint_PrintSetting_Menu_Menu_Confirm(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ENTER == UIPRINT_KEYMAP_ENTER)
    UIMenuWndPrint_PrintSetting_Menu_Menu_Confirm(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ZOOMOUT == UIPRINT_KEYMAP_DOWN)
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyUpAndDown(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_ZOOMIN == UIPRINT_KEYMAP_UP)
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyUpAndDown(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum >0)
    {
        switch(paramArray[0])
        {
            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_PRESS)
            case NVTEVT_KEY_PRESS:
            {
                break;
            }
            #endif

            #if (UIPRINT_KEYACT_TYPE&UIPRINT_KEYACT_RELEASE)
            case NVTEVT_KEY_RELEASE:
            {
                break;
            }
            #endif

            default:
            {
                return NVTEVT_CONSUME;
            }
        }
    }

    #if (UIPRINT_KEY_SHUTTER2 == UIPRINT_KEYMAP_ENTER)
    UIMenuWndPrint_PrintSetting_Menu_Menu_Confirm(pCtrl);
    #endif
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPrint_PrintSetting_Quality_Menu Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Quality_Menu)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_PaperType_Menu Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_PaperType_Menu)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_PaperSize_Menu Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_PaperSize_Menu)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_DatePrint_Menu Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_DatePrint_Menu)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_FilenamePrint_Menu Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_FilenamePrint_Menu)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_ImageOptimizes_Menu Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_ImageOptimizes_Menu)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_Layout_Menu Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Layout_Menu)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_FixedSize_Menu Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_FixedSize_Menu)
EVENT_END

//---------------------UIMenuWndPrint_PrintSetting_Dir_Left_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintSetting_Dir_Left_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintSetting_Dir_Left_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Dir_Left_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintSetting_Dir_Right_Panel Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintSetting_Dir_Right_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintSetting_Dir_Right_Panel Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Dir_Right_Panel)
EVENT_END

