//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPRINT_CONFIRM_H
#define UIMENUWNDPRINT_CONFIRM_H

#include "UIFramework.h"

extern VControl UIMenuWndPrint_ConfirmCtrl;

extern VControl UIMenuWndPrint_Confirm_Content_PanelCtrl;

extern VControl UIMenuWndPrint_Confirm_Title_PanelCtrl;

extern VControl UIMenuWndPrint_Confirm_Title_Text_StatusCtrl;

typedef enum
{
UIMenuWndPrint_Confirm_Title_Text_Status_STRID_PICTBRIDGE,
UIMenuWndPrint_Confirm_Title_Text_Status_MAX
}UIMenuWndPrint_Confirm_Title_Text_Status_Setting;
extern VControl UIMenuWndPrint_Confirm_Title_Icon_StatusCtrl;

typedef enum
{
UIMenuWndPrint_Confirm_Title_Icon_Status_ICON_MENU_PRINT_OFF,
UIMenuWndPrint_Confirm_Title_Icon_Status_MAX
}UIMenuWndPrint_Confirm_Title_Icon_Status_Setting;
extern VControl UIMenuWndPrint_Confirm_End_PanelCtrl;

extern VControl UIMenuWndPrint_Confirm_End_Dir_PanelCtrl;

extern VControl UIMenuWndPrint_Confirm_Confirm_MenuCtrl;

typedef enum
{
UIMenuWndPrint_Confirm_Confirm_Menu_STRID_OK,
UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CANCEL,
UIMenuWndPrint_Confirm_Confirm_Menu_STRID_CONTINUE,
UIMenuWndPrint_Confirm_Confirm_Menu_MAX
}UIMenuWndPrint_Confirm_Confirm_Menu_Setting;
extern VControl UIMenuWndPrint_Confirm_Text_StatusCtrl;

typedef enum
{
UIMenuWndPrint_Confirm_Text_Status_STRID_NULL,
UIMenuWndPrint_Confirm_Text_Status_STRID_START_PRINTING,
UIMenuWndPrint_Confirm_Text_Status_STRID_PRINT_ERROR,
UIMenuWndPrint_Confirm_Text_Status_STRID_PRINTER_DISCONNECTABLE,
UIMenuWndPrint_Confirm_Text_Status_STRID_PAPER_ERROR,
UIMenuWndPrint_Confirm_Text_Status_STRID_PAPER_OUT,
UIMenuWndPrint_Confirm_Text_Status_STRID_PAPER_LOAD_ERROR,
UIMenuWndPrint_Confirm_Text_Status_STRID_PAPER_EJECT_ERROR,
UIMenuWndPrint_Confirm_Text_Status_STRID_PAPER_MEDIA_ERROR,
UIMenuWndPrint_Confirm_Text_Status_STRID_PAPER_JAMMED,
UIMenuWndPrint_Confirm_Text_Status_STRID_PAPER_NEAR_EMPTY,
UIMenuWndPrint_Confirm_Text_Status_STRID_PAPER_NOT_SUPPORT,
UIMenuWndPrint_Confirm_Text_Status_STRID_INK_ERROR,
UIMenuWndPrint_Confirm_Text_Status_STRID_INK_EMPTY,
UIMenuWndPrint_Confirm_Text_Status_STRID_INK_LOW,
UIMenuWndPrint_Confirm_Text_Status_STRID_INK_WASTE,
UIMenuWndPrint_Confirm_Text_Status_STRID_HW_ERROR,
UIMenuWndPrint_Confirm_Text_Status_STRID_HW_FATAL,
UIMenuWndPrint_Confirm_Text_Status_STRID_HW_SERVICE_CALL,
UIMenuWndPrint_Confirm_Text_Status_STRID_HW_UNAVAILABLE,
UIMenuWndPrint_Confirm_Text_Status_STRID_HW_BUSY,
UIMenuWndPrint_Confirm_Text_Status_STRID_HW_LEVER,
UIMenuWndPrint_Confirm_Text_Status_STRID_HW_COVER_OPEN,
UIMenuWndPrint_Confirm_Text_Status_STRID_HW_NO_MARKING_AGENT,
UIMenuWndPrint_Confirm_Text_Status_STRID_HW_INK_COVER_OPEN,
UIMenuWndPrint_Confirm_Text_Status_STRID_HW_NO_INK_CARTRIDGE,
UIMenuWndPrint_Confirm_Text_Status_STRID_FILE_ERROR,
UIMenuWndPrint_Confirm_Text_Status_STRID_FILE_PRINT_INFO,
UIMenuWndPrint_Confirm_Text_Status_STRID_FILE_DECODE_ERROR,
UIMenuWndPrint_Confirm_Text_Status_STRID_CANCEL,
UIMenuWndPrint_Confirm_Text_Status_STRID_PRINT_CANCELED,
UIMenuWndPrint_Confirm_Text_Status_STRID_PRINT_FINISHED,
UIMenuWndPrint_Confirm_Text_Status_MAX
}UIMenuWndPrint_Confirm_Text_Status_Setting;
//-------------------------------------------------------------------------------------------------
typedef enum
{
    UIMenuWndPrint_Confirm_STATE_CONFIRM_NORMAL,
    UIMenuWndPrint_Confirm_STATE_CONFIRM_ALL,
    UIMenuWndPrint_Confirm_STATE_CONFIRM_INDEX,
    UIMenuWndPrint_Confirm_STATE_CONFIRM_DPOF,
    UIMenuWndPrint_Confirm_STATE_CONFIRM_DPOF_CONTINUE,
    UIMenuWndPrint_Confirm_STATE_CONFIRM_STOP,
    UIMenuWndPrint_Confirm_STATE_PRINTING,
    UIMenuWndPrint_Confirm_STATE_NON_PRINTING
}UIMenuWndPrint_Confirm_STATE_ENUM;
//-------------------------------------------------------------------------------------------------
#endif
